#!/usr/bin/env python3
"""Original v0.26 scenarios. Regenerate from any working directory.
Each scene has three decisions, multiple outcomes, explicit eligibility and named
follow-ups. Job/major scenes describe the work rather than reskinning random wins.
"""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
EVENTS, ECHOES = [], []

def O(text, effects=None, weight=1, **kwargs):
    return dict(text=text, effects=effects or {}, weight=weight, **kwargs)

def C(label, a, b, **kwargs):
    return dict(label=label, outcomes=[a, b], **kwargs)

def E(key, title, text, conditions, choices, themes, icon='🌱', **kwargs):
    assert len(choices) >= 3 and all(len(c['outcomes']) >= 2 for c in choices)
    e = dict(id='ctx.'+key, icon=icon, title=title, text=text, conditions={'life':['human','royal','vampire','witch','super','revenant'], **conditions}, choices=choices, themes=themes, weight=5, cooldown=7, **kwargs)
    EVENTS.append(e)
    return e

def echo(source, title, text, cond=None):
    key=source['id']+'.echo'
    # Consequences exist only when the triggering choice actually happened.
    source['choices'][0]['outcomes'][0]['schedule']={'event':key, 'years':[1,3]}
    ECHOES.append(dict(id=key, icon='📬', title=title, text=text,
        conditions={'life':['human','royal','vampire','witch','super','revenant'], **(cond or {})}, followup_only=True, weight=1,
        choices=[
            C('Follow through', O('I kept the promise when it had stopped being exciting. Somebody noticed.',{'happiness':4,'karma':2,'stress':2}), O('I tried to follow through, but the circumstances had changed. It still took effort.',{'stress':3,'smarts':1})),
            C('Renegotiate what I can do', O('I explained what had changed. We found a smaller version that still mattered.',{'stress':-3,'happiness':2}), O('They heard an excuse where I meant an explanation.',{'happiness':-3,'stress':2})),
            C('Let it go', O('I let that chapter close. Relief and regret arrived together.',{'stress':-3,'happiness':-1}), O('The chance went to somebody else. I was more disappointed than I expected.',{'happiness':-4,'smarts':1}))]))

# id, field, salary, education, preferred/required majors, title ladder,
# the problem and three approaches, then the specific opportunity.
JOBS = [
('data_analyst','Tech',52000,'bachelor',['computer_science','economics'],'Junior Data Analyst|Data Analyst|Analytics Lead','The dashboard says the campaign worked. You discover that returning customers were counted twice.','Rebuild the numbers before presenting','Explain the uncertainty in the meeting','Ship the attractive chart','A local clinic asks for a waiting-list dashboard that its staff can actually read.'),
('cybersecurity','Tech',57000,'bachelor',['computer_science'],'Security Analyst|Incident Responder|Security Lead','An employee reports a strange login just before everyone leaves for a long weekend.','Investigate and isolate the account','Ask for a second analyst before acting','Assume it is a harmless login','Your team can run its first incident drill, but people resent losing an afternoon.'),
('ux_research','Design',49000,'bachelor',['psychology','graphic_design'],'UX Research Assistant|UX Researcher|Research Lead','Test users cannot finish the checkout. The designer says they are using it wrong.','Show the recordings without blaming anyone','Test a simpler prototype with users','Approve the design to meet the deadline','You can interview people who normally get left out of product tests.'),
('technical_writer','Media',45000,'bachelor',['english','communications','computer_science'],'Junior Technical Writer|Technical Writer|Documentation Lead','A safety instruction changes meaning when translated. Nobody owns the final review.','Trace the instruction with an engineer','Ask the translator to explain the ambiguity','Publish the old wording','A new manual could turn a confusing first day into a calm one.'),
('game_producer','Tech',51000,'bachelor',['game_dev','business','communications'],'Associate Producer|Game Producer|Production Director','The demo works only when the lead programmer is watching. A showcase is days away.','Cut the risky feature and explain why','Arrange a focused bug triage','Promise that overtime will fix it','A small accessibility feature is ready, if you can protect its place on the schedule.'),
('renewable_tech','Energy',34000,'high_school',['engineering'],'Solar Installation Assistant|Renewable Technician|Site Supervisor','A roof measurement is wrong and the crew has already started lifting panels.','Stop the lift and remeasure','Call the supervisor for a revised plan','Keep going and improvise','A community centre needs a reliable installation more than an impressive sales pitch.'),
('urban_planner','Government',48000,'bachelor',['architecture','political_science','economics'],'Planning Assistant|Urban Planner|Planning Director','A proposed bus stop helps commuters but removes the last benches used by older residents.','Visit the street and redesign it','Hold a meeting with both groups','Use the cheapest plan','An empty lot could become useful public space if the neighbours can agree.'),
('environment_officer','Environment',41000,'bachelor',['biology','engineering'],'Environmental Assistant|Environmental Officer|Programme Lead','Water samples look unusual downstream from a major employer. One sample label is smudged.','Retest before making a public claim','Document the uncertainty and notify the team','Leave the awkward result out','A school wants to help monitor a stream without putting children at risk.'),
('food_scientist','Science',47000,'bachelor',['biology','culinary'],'Food Lab Assistant|Food Scientist|Quality Lead','A new recipe tastes good but fails the shelf-life test on one batch.','Repeat the test and pause release','Investigate storage conditions','Sign off the best-looking batch','You could help make an inexpensive meal both nutritious and safe to store.'),
('community_worker','Care',33000,'bachelor',['psychology','criminal_justice','education'],'Community Support Worker|Case Coordinator|Service Manager','Two households need the last appointment. One is louder; the other has stopped asking.','Use need rather than pressure to prioritise','Find another service that can help','Give the slot to whoever complains most','A drop-in group might reach people who never complete the forms.'),
('care_assistant','Care',27000,'high_school',['nursing','psychology'],'Care Assistant|Senior Care Assistant|Care Team Lead','A resident refuses the routine that keeps the shift on schedule.','Ask what is upsetting them','Bring in a familiar colleague','Rush through the routine','A resident remembers a hobby that could make the common room feel less like a waiting room.'),
('logistics_planner','Logistics',39000,'high_school',['business','engineering'],'Dispatch Assistant|Logistics Planner|Operations Lead','A delayed shipment carries medicine; the cheap reroute misses the refrigerated connection.','Protect the cold chain and explain the cost','Negotiate a safe transfer','Choose the cheapest reroute','A messy dispatch rota could be rebuilt around realistic breaks.'),
('event_coordinator','Hospitality',32000,'high_school',['business','communications'],'Event Assistant|Event Coordinator|Venue Manager','The venue has sold the same room to two parties. Both have travelled to be there.','Find a workable alternative and cover the difference','Negotiate a shared timetable','Blame the booking software','A community event needs a quiet space as much as it needs a stage.'),
('archivist','Media',38000,'bachelor',['english','political_science'],'Archives Assistant|Archivist|Collections Lead','A donor wants inconvenient letters removed before the collection is catalogued.','Keep the record intact and explain the policy','Seek a temporary access agreement','Remove the troublesome folder','You find recordings nobody has heard for decades, but restoring them takes patient work.'),
('sound_engineer','Media',35000,'high_school',['music','engineering'],'Audio Assistant|Sound Engineer|Studio Lead','The singer hears distortion that the producer insists is part of the sound.','Check the signal chain before the next take','Record a clean version as a comparison','Turn it louder to finish quickly','A tiny local band has one evening to capture a song they have rehearsed for a year.'),
('compliance','Finance',50000,'bachelor',['accounting','law','economics','criminal_justice'],'Compliance Associate|Compliance Analyst|Compliance Lead','An important client sends documents that almost match, except for the dates.','Verify the documents independently','Ask for clarification and pause approval','Wave them through to protect the account','A confusing internal rule could be rewritten so ordinary staff can follow it.'),
('museum_educator','Education',35000,'bachelor',['education','english','biology'],'Museum Learning Assistant|Museum Educator|Learning Lead','A school group arrives with needs the tour plan never considered.','Adapt the tour and ask the teachers for help','Split the visit into smaller groups','Deliver the planned talk unchanged','You can make a hands-on exhibit that welcomes children who do not enjoy reading labels.'),
('tour_guide','Hospitality',28000,'high_school',['communications','english'],'Tour Assistant|Tour Guide|Tour Operations Lead','A visitor wants a dangerous shortcut because the brochure promised a perfect photograph.','Explain the risk and offer another view','Ask the group to vote on a safe alternative','Take the shortcut to avoid a bad review','A walking route could include the neighbourhood shops that tourists usually miss.'),
('farm_manager','Environment',36000,'high_school',['biology','business'],'Farm Operations Assistant|Farm Manager|Regional Farm Lead','The soil is dry, the irrigation budget is thin, and rain is only a forecast.','Prioritise the most vulnerable beds','Ask neighbouring farms about sharing equipment','Water everything and hope','A trial plot could save water, but somebody must keep careful records.'),
('biomedical_engineer','Engineering',61000,'bachelor',['engineering','biology'],'Junior Biomedical Engineer|Biomedical Engineer|Clinical Engineering Lead','A device fault appears only after hours of use. Replacing it delays a crowded clinic.','Test the fault and take the device out of service','Arrange a checked backup unit','Restart it and send it back','Nurses can help redesign a device alarm that everybody has learned to ignore.'),
('public_defender','Legal',59000,'graduate',['law'],'Assistant Public Defender|Public Defender|Supervising Defender','A client wants to accept an offer without understanding what it would cost their future.','Explain the consequences in plain language','Ask for time to investigate another route','Push the quickest resolution','A file nobody has had time to review contains a detail that deserves another look.'),
('insurance_analyst','Finance',44000,'bachelor',['economics','accounting','business'],'Claims Analyst|Risk Analyst|Underwriting Lead','The model flags a claim as suspicious, but the customer has a consistent explanation.','Review the evidence rather than the score','Request the missing documents','Reject it automatically','Your team could make its letters understandable before another customer gives up.'),
('special_education','Education',40000,'bachelor',['education'],'Learning Support Teacher|Special Education Teacher|Inclusion Lead','A pupil is called disruptive when the classroom noise is what overwhelms them.','Build a quieter plan with the pupil','Work with the class on predictable routines','Increase punishment to restore order','A small change to an ordinary lesson might let a pupil take part for the first time.'),
('community_nurse','Healthcare',44000,'bachelor',['nursing'],'Community Nurse|Senior Community Nurse|Community Nursing Lead','A patient misses visits because getting to the clinic costs more than they can spare.','Coordinate care around their actual circumstances','Ask the team about a home visit','Mark them as non-compliant','A neighbourhood group wants clear advice rather than another leaflet nobody reads.'),
]

job_file=ROOT/'data/jobs.json'
base_jobs=[j for j in json.loads(job_file.read_text()) if j['id'] not in {x[0] for x in JOBS}]
for jid,field,salary,edu,majors,ranks,problem,a,b,c,opportunity in JOBS:
    regulated=jid in ['public_defender','special_education','community_nurse','biomedical_engineer']
    jd=dict(id=jid,field=field,salary=salary,edu=edu,min_age=22 if edu=='graduate' else 18,
            stress=4,ranks=ranks.split('|'),icon='🧰',preferred_majors=majors)
    if regulated: jd['majors']=majors
    years={'data_analyst':1960,'web_designer':1995,'cybersecurity':1980,'renewable_technician':1980,'paramedic':1960,'lab_technician':1900,'mental_health':1920,'logistics_planner':1920,'compliance':1930,'biomedical_engineer':1950,'special_education':1900}
    if jid in years: jd['era_min']=years[jid]
    if field=='Tech': jd['local_scenes']=['tech','studio']
    if field in ['Food','Hospitality']: jd['local_scenes']=['restaurant']
    if field in ['Engineering','Trades','Energy']: jd['local_scenes']=['construction']
    base_jobs.append(jd)
    scene=E('job.'+jid, 'The part the job advert left out', problem, {'age':[18,85],'job':jid}, [
        C(a, O('I did the careful work. It delayed the easy answer, but the result held up when somebody checked.', {'job_perf':5,'stress':3,'karma':2},2,stat_bonus={'smarts':.35}), O('I was right to check, but the delay still landed on me. Being careful did not make the deadline disappear.',{'job_perf':-2,'stress':5,'smarts':1})),
        C(b, O('We found a compromise that people could actually use. I learned who was willing to help.',{'job_perf':3,'happiness':2,'stress':1},2), O('The compromise left everyone slightly dissatisfied. I had to explain it twice.',{'job_perf':-1,'stress':4})),
        C(c, O('Nobody asked another question that day. I knew that was not the same as getting it right.',{'stress':-2,'karma':-2}), O('The shortcut surfaced at the worst possible moment. I had to own it.',{'job_perf':-7,'stress':7,'happiness':-3},2))], ['work'],icon='💼')
    echo(scene, 'The work came back', 'The decision you made on the job has reached the next team. They want to know whether you will stand behind it.', {'employed':True})
    E('job.'+jid+'.opportunity','Something worth doing',opportunity,{'age':[18,85],'job':jid},[
        C('Take responsibility for it', O('I made something useful rather than merely presentable. I kept the work as evidence of what I could do.',{'job_perf':5,'stress':3,'happiness':3},2,market={'training':{'field':field}}), O('I took it on and underestimated the hours. I learned, but the rest of my work slipped.',{'job_perf':-2,'stress':6,'smarts':1})),
        C('Share it with a colleague', O('We divided the work properly. Sharing credit was easier than carrying it alone.',{'job_perf':3,'stress':-2,'happiness':2}), O('We each assumed the other had finished the last piece. I will write down responsibilities next time.',{'job_perf':-3,'stress':4})),
        C('Keep to my normal workload', O('I protected my evenings. It was a reasonable decision, even if somebody else got the credit.',{'stress':-3,'happiness':1}), O('I watched the opportunity become someone else\'s promotion story.',{'happiness':-3,'stress':1}))],['work'],icon='🧰')
job_file.write_text(json.dumps(base_jobs,ensure_ascii=False,indent=1)+'\n')

# Region and weather: heat and snow require actual annual conditions.
ENV = [
('hot_bus','The bus with no air conditioning','The bus in {city} is stuck in traffic during the hottest part of the year. Someone nearby looks unwell.',{'weather':['heat']},[16,85],'Help them find shade and call for help','Get off and walk the shaded route','Stay seated and hope the bus moves'),
('hot_child','A playground too hot to touch','The playground equipment is hot enough to hurt. Your child wants to play anyway.',{'weather':['heat'],'lifestyle_all':['caregiver']},[18,70],'Find an indoor activity together','Wait for the cooler evening','Let them play while I watch'),
('snow_school','The cancelled school bus','Snow has stopped the school bus. The school sends a worksheet, and your friends propose a snow fort.',{'weather':['snow']},[6,17],'Finish the work before going out','Build the fort and study together later','Pretend the cancellation means no homework'),
('snow_work','The commute nobody planned for','Snow has stopped traffic around {city}. Your manager still expects a normal start time.',{'weather':['snow'],'lifestyle_all':['working']},[18,70],'Explain the delay and propose useful work','Arrange a safe shared journey','Rush out without checking the route'),
('wet_books','The book bag in the rain','A sudden downpour gets into your school bag. Your carefully written notes are beginning to dissolve.',{'weather':['rain']},[6,17],'Dry what I can and ask for copies','Tell the teacher before the deadline','Hand in the damaged pages without explanation'),
('wet_shop','Water under the shop door','Rain in {city} is finding its way under the shop door. The morning delivery is still outside.',{'weather':['rain'],'field':['Retail','Food']},[18,80],'Protect the delivery and call for help','Close briefly and explain to customers','Carry on and hope it stays shallow'),
('dry_garden','The water restriction','Your young plants look thirsty. The district has asked households to conserve water.',{'weather':['dry'],'lifestyle_any':['active','retired']},[18,90],'Reuse suitable water and mulch the beds','Let the least hardy plants go','Water everything before anybody sees'),
('cold_parent','The heating left off','An older relative says the house is warm enough, while sitting indoors in a coat.',{'weather':['cold','snow'],'lifestyle_any':['family']},[30,85],'Ask about the bills and help with a plan','Arrange another warm place to spend afternoons','Accept that they know their own house'),
('mild_walk','An invitation to get outside','A walking group in {city} offers a gentle route, with a shorter way home for anyone who needs it.',{'weather':['mild'],'lifestyle_any':['frail','retired']},[50,95],'Try the shorter route','Invite somebody and set our own pace','Stay home this time'),
('spring_club','A spring without an audience','A local club is starting again for spring. Joining means being new at something in front of strangers.',{'season':['spring']},[13,85],'Join the beginners session','Go with a friend and watch first','Wait until I feel more confident'),
('autumn_shift','The daylight disappears','Autumn darkens your journey home from work. The route that felt easy in summer feels different now.',{'season':['autumn'],'lifestyle_all':['working']},[18,80],'Plan a better-lit route','Ask about a different shift','Keep the old routine'),
('summer_job','The summer vacancy','A seasonal employer needs help for summer. The pay is modest; the experience could matter more.',{'season':['summer']},[16,24],'Ask what I would actually learn','Apply with friends and share transport','Keep the summer free'),
('monsoon_door','The rain arrives sideways','The seasonal rains in {city} reach a window that has never leaked before.',{'climate':['monsoon'],'weather':['rain']},[18,85],'Document it and arrange a repair','Move belongings and ask neighbours for advice','Put down towels and wait'),
('desert_water','The queue at the refill point','Another dry spell means a queue for water. A neighbour who cannot carry much is waiting behind you.',{'climate':['arid','semi_arid'],'weather':['dry','heat']},[16,85],'Carry an extra container for them','Help organise a shared delivery','Take my water and go'),
('hok_snow','Before the first heavy snow','In Hokkaido, a neighbour checks whether you have prepared for the cold. It sounds fussy until the forecast arrives.',{'region':['hok'],'season':['winter']},[18,85],'Prepare before the rush','Ask what a newcomer usually forgets','Decide the ordinary coat will do'),
('ber_bike','The temporary cycle lane','A new cycle lane in Berlin changes the route to somewhere you visit every week. Drivers and cyclists both have opinions.',{'region':['ber'],'lifestyle_any':['active','working']},[16,85],'Try the route cautiously','Attend the neighbourhood discussion','Keep using the familiar route'),
('man_music','The rehearsal above the shop','A small venue in Manchester needs someone to help an amateur music night. Your evening is suddenly spoken for if you agree.',{'region':['man']},[16,85],'Help with the evening','Offer a smaller task I can finish','Go as an audience member'),
('city_room','A room somebody else needs','In an expensive housing market, a friend asks whether your spare corner could be somewhere to stay temporarily.',{'region':['ny','ldn','tok'],'lifestyle_any':['social','family']},[22,80],'Agree on a short stay and clear boundaries','Help them search and offer practical support','Say I cannot share the space'),
]
for key,title,text,context,age,a,b,c in ENV:
    e=E(key,title,text,{'age':age,'context':context},[
        C(a,O('I made a practical plan and followed it. The situation became manageable, though it took part of the day.',{'health':2,'stress':-2,'happiness':3},2),O('I tried to help, but the problem was larger than the plan. I needed help of my own.',{'health':-1,'stress':4,'smarts':1})),
        C(b,O('Another person knew a detail I had missed. We found a workable answer together.',{'happiness':3,'stress':-1,'karma':1}),O('Getting everybody organised took longer than expected. The eventual answer was imperfect.',{'stress':3,'happiness':1})),
        C(c,O('Nothing terrible happened. I had a quieter day, but the problem was still there.',{'stress':-1}),O('The small problem grew while I left it alone. Next time I will make a different choice.',{'health':-2,'stress':4,'happiness':-2}))],['weather','daily'],icon='🌦️')
    if key in ['hot_bus','wet_shop','cold_parent','spring_club','monsoon_door','desert_water']: echo(e,'After that season','Something you set in motion during that season has become part of everyday life. Someone asks whether you will keep it going.')

# Each major has a specific professional question, not just a smarts button.
MAJOR_SCENES = {
'computer_science':('A useful bug','Your programme works on the demonstration data, then fails on a messy file from a real user.','Trace the failure with the user','Write tests around the awkward cases','Clean the data until the demo works'),
'nursing':('The patient behind the chart','A placement supervisor asks you to explain a care plan to a patient who is frightened rather than uninformed.','Ask what the patient is worried about','Practise explaining the plan with a mentor','Repeat the technical explanation'),
'business':('The business that almost works','A class project turns a profit only by assuming unpaid overtime.','Rewrite the staffing model','Test whether customers would pay more','Keep the profitable spreadsheet'),
'criminal_justice':('Two versions of one report','A case exercise contains two witnesses whose accounts disagree in small but important ways.','Compare what each could actually observe','Ask what evidence could distinguish the stories','Pick the more confident witness'),
'education':('The lesson nobody understood','Your practice lesson is tidy. Half the class has quietly stopped following it.','Ask pupils to show where they got lost','Try a different explanation','Finish every slide anyway'),
'engineering':('A bridge on paper','A model passes the standard test but shakes when loads move across it.','Investigate the moving load','Ask another group to challenge the design','Submit the successful static result'),
'biology':('The unexpected control','The control sample changes more than the treated one. Your group wants to discard it.','Repeat the experiment','Check the sample handling','Write around the inconvenient control'),
'psychology':('The question that leads','Your survey asks participants to agree that a stressful experience made them stronger.','Rewrite the loaded question','Run a small neutral pilot','Keep the question because it is engaging'),
'graphic_design':('The poster in small print','The client loves your poster; someone with low vision cannot read the essential detail.','Redesign the hierarchy and contrast','Test it at actual viewing distance','Keep the approved version'),
'communications':('The statement before the facts','A mock press office must respond while the facts are still coming in.','Say what is known and what is not','Prepare an update and a correction process','Write the most reassuring statement'),
'economics':('An average nobody lives','An economic model treats every household as equally able to absorb a price rise.','Model different household budgets','Explain the limitation beside the results','Report the average as the whole story'),
'culinary':('A meal with constraints','A practical exam asks for a good meal with a small budget and two dietary restrictions.','Build the recipe around the constraints','Test substitutions before serving','Make the familiar dish and explain later'),
'music':('A rehearsal that will not settle','The ensemble sounds right individually and wrong together.','Listen and rebuild the difficult passage','Ask the group to change the arrangement','Practise my own part louder'),
'political_science':('The consultation with empty chairs','A policy exercise attracts only people who already agree with the proposal.','Find the missing voices','Record who did not take part','Call the result a clear mandate'),
'english':('The passage you cannot paraphrase','A seminar interpretation sounds convincing until someone reads the whole passage aloud.','Revise the argument from the text','Compare two defensible interpretations','Defend the first reading at any cost'),
'architecture':('The building without a welcome','Your studio design has a beautiful entrance that wheelchair users cannot reach directly.','Redesign the entrance as part of the building','Test routes with prospective users','Put an access route around the back'),
'accounting':('The account that balances too neatly','A practice set balances only after a vague adjustment called miscellaneous.','Trace the underlying transactions','Explain the unresolved difference','Keep the balanced total'),
'game_dev':('A player breaks the tutorial','A playtester solves your tutorial in a way you did not expect and then gets stuck.','Follow the player rather than the script','Redesign the confusing feedback','Add a longer instruction screen'),
'law':('The argument and the client','A case exercise offers a clever argument that would expose a client to another serious risk.','Discuss the trade-off with the client','Find a narrower defensible argument','Chase the impressive courtroom win'),
'medicine':('The finding that does not fit','A teaching case has one symptom that contradicts the obvious diagnosis.','Revisit the differential with the supervisor','Check what information is still missing','Commit to the common diagnosis'),
'mba':('The acquisition slide','A proposed merger looks efficient only if you leave employee turnover out of the costs.','Include the missing costs','Model a slower integration','Pitch the headline saving'),
'dentistry':('The anxious appointment','A supervised patient cannot tolerate the planned procedure today.','Discuss a staged plan with the supervisor','Work on the patient\'s immediate concern first','Push to finish the scheduled procedure'),
'pharmacy':('The similar boxes','Two teaching prescriptions have nearly identical names but different doses.','Check each order against the source','Ask for a second independent check','Use the most familiar dose'),
'veterinary':('The animal and the owner','A teaching case needs care its owner cannot easily afford.','Explore a workable plan with the supervisor','Explain priorities and available support','Give the standard plan without discussing cost'),
'phd':('The result you hoped to find','A promising result disappears when you repeat the analysis with the original settings.','Document the failed replication','Ask another researcher to check the method','Keep the exciting version'),
}
for mid,(title,text,a,b,c) in MAJOR_SCENES.items():
    field={'computer_science':'Tech','nursing':'Healthcare','business':'Business','criminal_justice':'Government','education':'Education','engineering':'Engineering','biology':'Science','psychology':'Care','graphic_design':'Design','communications':'Media','economics':'Finance','culinary':'Food','music':'Media','political_science':'Government','english':'Media','architecture':'Design','accounting':'Finance','game_dev':'Tech','law':'Legal','medicine':'Healthcare','mba':'Business','dentistry':'Healthcare','pharmacy':'Science','veterinary':'Healthcare','phd':'Science'}[mid]
    e=E('study.'+mid,title,text,{'age':[18,85],'university':True,'context':{'current_major':[mid]}},[
        C(a,O('The careful answer held up when the situation changed. I kept the project as a useful work sample.',{'school':4,'smarts':2,'stress':2},2,market={'training':{'field':field}}),O('I found more uncertainty than a simple answer. The tutor valued the reasoning, but the work took longer.',{'school':1,'stress':4,'smarts':1})),
        C(b,O('Working through it with somebody else made the lesson stick.',{'school':3,'happiness':2,'stress':1}),O('We disagreed about the approach. I learned to explain my assumptions.',{'smarts':2,'stress':3})),
        C(c,O('The presentation went smoothly. It taught me less than I wanted to admit.',{'school':1,'stress':-1}),O('The tutor asked the question I had avoided. I had to go back to the beginning.',{'school':-5,'stress':5,'smarts':1},2))],['school','work'],icon='🎓')
    echo(e,'The work sample','Someone reviewing your work asks about the problem you studied, and how you would approach it now.')

# Life stages and lifestyle have concrete conflicts and distinct outcomes.
STORIES = [
('child_secret','A promise in the playground','A friend asks you to keep a secret that makes you worried about their safety.',{'age':[6,12]},'Tell a trusted adult privately','Ask my friend to tell someone with me','Keep the promise exactly'),
('teen_online','The post that escaped the group chat','A joke meant for three friends reaches your classmates. Somebody it names has read it.',{'age':[13,17]},'Apologise directly and take it down','Ask the group to stop sharing it','Claim it was never serious'),
('teen_team','The last place on the team','You are offered the last team place, but training conflicts with a subject you are struggling in.',{'age':[12,17]},'Agree a realistic study and training plan','Ask about a smaller role this term','Take the place and ignore the timetable'),
('young_home','The keys and the silence','Your first evening away from the family home is quieter than you expected.',{'age':[18,25],'housing':['apartment','dorm']},'Invite someone for a simple meal','Build a small routine of my own','Fill the silence with expensive plans'),
('young_peer','Everybody else seems ahead','A reunion becomes a comparison of jobs, degrees and relationships. You leave feeling behind.',{'age':[20,32]},'Ask a friend how things really are','Choose one goal that is mine','Try to catch up with all of them'),
('care_schedule','Three people, one afternoon','Your child needs you, a relative has an appointment, and your work has a deadline.',{'age':[25,65],'context':{'lifestyle_all':['caregiver','working']}},'Ask for help and name the actual conflict','Rearrange the deadline honestly','Promise all three I will be there'),
('middle_pivot','The job I never tried','You meet somebody doing the work you once wanted. Starting over would affect more than your title.',{'age':[35,60],'employed':True},'Ask about a practical route into the field','Try a small project before leaving anything','Dismiss the idea before it unsettles me'),
('retired_time','A Tuesday with nowhere to be','Without the working week, an ordinary Tuesday feels surprisingly large.',{'age':[55,95],'retired':True},'Commit to a regular local activity','Enjoy the empty day and plan tomorrow','Wait for somebody else to make plans'),
('elder_access','The familiar shop changes','The shop you use every week rearranges everything and removes the chairs by the door.',{'age':[70,100]},'Explain what would make the shop usable','Ask someone to come with me for now','Stop going without saying why'),
('frail_trip','The journey and the stairs','An invitation sounds lovely until you discover how many stairs are involved.',{'age':[18,95],'max_stat':{'health':39}},'Ask for an accessible plan','Suggest another place to meet','Go without mentioning the difficulty'),
('stress_email','The message after midnight','You keep checking work messages in bed. One arrives just as you almost fall asleep.',{'age':[18,75],'employed':True,'min_stat':{'stress':71}},'Set a boundary and explain it tomorrow','Arrange a clear on-call rota','Reply immediately again'),
('active_injury','The ache I cannot train through','A training ache lasts into the next week. The race you wanted is approaching.',{'age':[16,80],'context':{'lifestyle_all':['active']}},'Reduce training and ask for assessment','Switch to a gentler routine','Train harder so I do not fall behind'),
('student_work','A shift before the exam','A manager asks you to cover a shift the evening before an important exam.',{'age':[18,45],'university':True,'employed':True},'Explain the exam and offer another shift','Trade with someone who needs my later shift','Take it and study through the night'),
('money_repair','A repair at the wrong time','Something essential breaks in the week your cash balance is already frightening.',{'age':[18,90],'context':{'lifestyle_all':['struggling']}},'Ask about a safe repair and payment plan','Borrow the thing until I can replace it','Choose the cheapest unverified fix'),
('wealth_request','The request that came through family','A relative presents a business idea as if your savings make the risk unimportant.',{'age':[25,95],'context':{'lifestyle_all':['wealthy','family']}},'Ask for figures and discuss a limit','Offer advice rather than money','Fund it because saying no feels awkward'),
('gambling_limit','The win that made the loss disappear','A recent win is easier to remember than everything you spent chasing it.',{'age':[18,90],'context':{'lifestyle_all':['gambling']}},'Look at the full record and take a break','Set aside ordinary expenses before returning','Increase the next stake to recover everything'),
('mentor_window','An offer of somebody\'s time','A professional you respect offers a short mentoring session. You need a question worth asking.',{'age':[18,60],'context':{'lifestyle_any':['job_seeking','studious']}},'Bring a work sample and a precise question','Ask what beginners misunderstand','Ask them to get me a job'),
('social_cancel','The cancelled plan again','You cancel on the same friend for the third time. This reply has no smiley face.',{'age':[16,90],'context':{'lifestyle_any':['social','working']}},'Make a smaller promise I can keep','Explain what has been overwhelming me','Wait for them to get over it'),
]
for key,title,text,cond,a,b,c in STORIES:
    themes=['daily','social']
    if key.startswith(('stress','middle','mentor')): themes=['work','life']
    if key.startswith(('frail','active')): themes=['health','daily']
    e=E(key,title,text,cond,[
        C(a,O('I dealt with the actual problem rather than the version that made me look best. It helped, and it required something of me.',{'happiness':4,'stress':-2,'smarts':1},2),O('I tried the honest approach. It did not solve everything, but it made the next conversation possible.',{'stress':3,'karma':2})),
        C(b,O('A smaller, workable answer was enough. I felt less trapped by the perfect one.',{'happiness':3,'stress':-2}),O('The compromise had costs of its own. I had to admit which one I could live with.',{'stress':3,'happiness':-1})),
        C(c,O('For a while, the easy answer worked. The underlying problem stayed where I had left it.',{'happiness':1,'stress':1}),O('The easy answer made the next problem harder. I wished I had spoken sooner.',{'happiness':-4,'stress':5},2))],themes)
    if key in ['child_secret','teen_online','care_schedule','middle_pivot','retired_time','frail_trip','stress_email','active_injury','gambling_limit','mentor_window']: echo(e,'The conversation continues','What you decided has changed what someone expects from you. There is another conversation to have.')

# Rare, opt-in pivots. They do not forcibly replace a career or make education free.
e=E('twist.retraining','The door I thought had closed','A former colleague tells you about a funded retraining placement. It could change the work you do, but it would consume the year you had planned.',{'age':[25,60],'context':{'lifestyle_any':['job_seeking','working']}},[
 C('Apply and rearrange the year',O('I got a place. The funding covered the course, not the ordinary bills. I learned a new field and had to make room for it.',{'money':-1200,'stress':6,'smarts':4},market={'training':{'field':'Tech','gain':3}},milestone='began a career retraining placement'),O('I reached the final list and missed the place. The application still showed me what I need next.',{'stress':4,'happiness':-3,'smarts':2})),
 C('Try a smaller evening route',O('The evening course fit my existing life. Progress was slower, but it was progress.',{'money':-200,'stress':3},market={'training':{'field':'Tech'}}),O('I could not keep both timetables. I learned why a transition needs more than enthusiasm.',{'money':-200,'stress':5})),
 C('Keep the life I have',O('I declined. Choosing the familiar life was still a choice.',{'stress':-3,'happiness':2}),O('I declined, and watched the deadline pass with mixed feelings.',{'happiness':-2,'stress':1}))],['twist','work'],icon='✨',twist=True,once=True)
echo(e,'A different direction','The placement has ended. A new direction is possible, but no employer owes you an offer.')
e=E('twist.care','The phone call that changes the timetable','A relative can no longer manage alone. No one in the family has a plan, and everyone thinks you might.',{'age':[28,75],'context':{'lifestyle_any':['family']}},[
 C('Build a shared care plan',O('We arranged help and divided the work. I lost money and free evenings, but I was no longer pretending this was temporary.',{'money':-800,'stress':6,'karma':4,'happiness':2},milestone='reorganised life around family care'),O('I organised the first week. The family agreed in principle and disappeared in practice.',{'money':-600,'stress':10,'happiness':-4})),
 C('Arrange professional support',O('Finding suitable help took time. Sharing the work made care more sustainable.',{'money':-1200,'stress':-2,'karma':2}),O('The first arrangement fell through. We had to start the search again.',{'money':-500,'stress':7})),
 C('Say I cannot be the main carer',O('It was a difficult conversation. We found another plan without pretending I could do everything.',{'stress':3,'happiness':-1}),O('The family heard refusal rather than limits. I still needed to live with the decision.',{'stress':6,'happiness':-4}))],['twist','family'],icon='☎️',twist=True,once=True)
echo(e,'The new ordinary','Care has become part of the family timetable. It is time to discuss whether the arrangement can last.')

for name,events in [('contextual.json',EVENTS),('contextual_echoes.json',ECHOES)]:
    (ROOT/'data/events'/name).write_text(json.dumps(events,ensure_ascii=False,indent=1)+'\n')
print(f'Contextual content: {len(EVENTS)} scenes, {len(ECHOES)} follow-ups, {len(JOBS)} new jobs')
