from prison_lib import *

# ====================================================================== the outside (re-entry, v1.3)
# Every event here needs the `reentry` tag: the three years after the gate opens.

def R(id, icon, title, text, *choices, extra=None, **kw):
    tags = ["reentry"] + (extra or [])
    E(id, icon, title, text, tags, *choices, cooldown=kw.pop("cooldown", 40), **kw)

R("re.first", "🍽️", "The first meal",
  "Nobody tells you how many decisions there are. A man behind a counter asks what you want, and what you want turns out to be a very large question. The menu has forty things on it. You've eaten from a tray for years.",
  C("Order what you remember",
    O("A cheeseburger, which tasted like grease and salt and a memory. I ate it slowly and thought it was the best thing I'd ever had, and also that something was missing, and the thing missing was the noise.", {"happiness": 6}, {"stab": 3}),
    O("I ordered the thing I'd thought about for years. It was fine. The thinking had been better. I sat in the window and watched people walk past as though it was nothing.", {"happiness": 3}, {"stab": 2})),
  C("Let someone else order",
    O("I said 'whatever you're having'. The waitress smiled. It was the first time anybody had decided something for me kindly.", {"happiness": 4}, {"stab": 3, "support": 2}),
    O("I let the person with me choose. I realised halfway through the meal that I was eating with my arm round the plate. I took it away, slowly.", {"happiness": 2, "stress": 2}, {"stab": 2})),
  C("Leave without eating",
    O("It was too much: the light, the choice, the noise. I stood outside and breathed. Somebody asked if I was alright. I said yes, and meant it a little.", {"stress": 6}, {"stab": -2}),
    O("I walked out. I got a sandwich from a shop, in a bag, and ate it on a wall by myself. It was exactly what I needed, and I did not mind that nobody knew.", {"stress": 3, "happiness": 2}, {"stab": 1})),
  once=True)

R("re.phone", "📱", "The phone",
  "Everything is a screen. The bus has one, the bank has one, the form for the job has one and the form wants to know your email address, a thing you've never had. A teenager on the bus helps you without looking up.",
  C("Ask someone to show you",
    O("A boy of about twelve took it out of my hand, did it in four seconds and handed it back. 'It's easy,' he said, kindly. I thanked him far too much.", {"smarts": 1, "happiness": 2}, {"stab": 3}),
    O("A woman at the library desk sat with me for an hour. She never asked why I didn't know. I have never forgotten it.", {"smarts": 2, "happiness": 4}, {"stab": 4, "support": 3})),
  C("Work it out alone",
    O("It took a week and a great deal of swearing. I got there. There was pride in it that was disproportionate to the achievement.", {"smarts": 2, "stress": 4}, {"stab": 2}),
    O("I got it wrong several times, including once in front of a queue. I went red. Then I got it right and nobody noticed.", {"stress": 5}, {"stab": 1})),
  C("Avoid it entirely",
    O("I did without. It meant forms in person, queues, cash. It meant being the one with the paper. I got by, but the world is built for the other kind of person.", {"stress": 6}, {"stab": -4}),
    O("I kept to places that did not need it. It's a way to live. It's a narrow one.", {"stress": 4}, {"stab": -3})),
  once=True)

R("re.interview", "💼", "The question on the form",
  "It's the fifth interview. It's gone well. The manager likes you. Then the form comes out, and there's the box, and you know that however you answer, the room is going to change.",
  C("Tell the whole truth",
    O("I said it plainly: what, when, how long, and what I'd done with the time. He listened without writing. 'I'll be honest, that gives me pause. But the rest of what you've said doesn't.' I got the job.", {"happiness": 8}, {"stab": 8, "work": 1}),
    O("I told him everything. He thanked me for my honesty and said they'd be in touch. They weren't. Honesty doesn't always pay, but I could look at myself.", {"happiness": -2, "stress": 4}, {"stab": 2})),
  C("Give the short version",
    O("'A conviction, a long time ago, served in full.' He nodded as though I'd said something about the weather. I took the job and carried that sentence home with me for weeks.", {"stress": 4}, {"stab": 5, "work": 1}),
    O("I gave the short version. It worked, once. Then a background check found the rest, and it looked much worse for the missing detail.", {"stress": 8, "happiness": -4}, {"stab": -4})),
  C("Leave the box blank",
    O("They didn't check. I started on Monday, and spent two years waiting for someone to look.", {"stress": 8}, {"stab": 3, "work": 1, "heat": 4}),
    O("It came back to bite me. The HR woman was kind about it, which was worse. I was let go on a Friday with a box.", {"stress": 10, "happiness": -6}, {"stab": -8, "work": -1})),
  extra=["employed"], cooldown=40)

R("re.landlord", "🏘️", "The deposit",
  "The room is a decent one. The landlord is a tired man with a ring of keys. He wants a month's deposit, two references, and a look at your face while you say where you've been for the last few years.",
  C("Pay up front and explain",
    O("I counted out the cash and told him straight. He looked at the money for a long time. 'No trouble?' 'None.' 'Right,' he said, and held out a key.", {"money": -1200, "happiness": 4}, {"stab": 6, "home": 1}),
    O("I explained. He listened, then asked for six months' rent in advance. I paid it. It left me with very little, and a room.", {"money": -2500, "stress": 4}, {"stab": 4, "home": 1})),
  C("Ask family to vouch",
    O("My sister signed the form without a word and drove me to the door. She stood on the step until I had gone in, as though I might not.", {"happiness": 5}, {"stab": 5, "home": 1, "support": 4}),
    O("I asked, and they said yes, and I had to carry that: the weight of someone else's name on my lease.", {"stress": 4, "happiness": 2}, {"stab": 5, "home": 1, "support": 2})),
  C("Doss for now",
    O("A friend's floor, a hostel, a car for two weeks in March. It's survivable. It's not a life, and I could feel the margin thinning.", {"health": -2, "stress": 8}, {"stab": -6}),
    O("I took what was offered by the day: a sofa here, a bed in a church hall there. People are kinder than they should have to be.", {"stress": 6}, {"stab": -3, "support": 2})),
  extra=["employed"], cooldown=40)

R("re.officer", "🧾", "A very ordinary appointment",
  "The probation officer's office has a pot plant and a poster about domestic safety. She has your file open and a look on her face that is neither friendly nor unfriendly. 'How's it going?' she asks.",
  C("Be completely straight",
    O("I told her about the money, about the temptation, about the man I'd seen. She wrote it down, calmly. 'That's what the appointment is for.' It was the first time I'd ever been helped by an official.", {"stress": -4}, {"stab": 6}),
    O("I told her it was hard. She didn't flinch. She sent me to a programme and a man who helps with CVs. It was a better conversation than I'd expected.", {"stress": -2}, {"stab": 5, "support": 3})),
  C("Say all is fine",
    O("'All fine.' She nodded, and made a note, and there was a pause which told me she knew exactly what 'fine' was worth.", {"stress": 2}, {"stab": 1}),
    O("I said I was fine. I was not fine. She wrote 'doing well' and I walked out feeling worse than when I went in.", {"stress": 6}, {"stab": -2})),
  C("Skip it",
    O("I didn't go. A letter arrived. Then another. I went to the next one, and she said, very gently, that there is only one more of those before it becomes something else.", {"stress": 8}, {"stab": -5, "viol": 1}),
    O("I missed the appointment. The text from her said only 'please call.' It was the politest warning I have ever had.", {"stress": 6}, {"stab": -4, "viol": 1})),
  extra=["employed"], cooldown=40)

R("re.oldfriends", "🍻", "The old crowd",
  "Three of them are on the corner by the shop. They saw you before you saw them. One lifts a hand. They look older, and well, and there's a car in the road with the engine running that no one has mentioned.",
  C("Cross the street",
    O("I crossed. It cost me a feeling in the stomach. But I didn't turn round, and that night I slept better than I had in months.", {"stress": 4, "karma": 3}, {"stab": 5, "heat": -3}),
    O("I crossed the road and kept my head down. One of them called my name. I did not look back. It's the loneliest thing I've done.", {"stress": 6, "happiness": -3}, {"stab": 4})),
  C("Say hello and move on",
    O("I stopped, shook hands, asked after somebody's mother. Nobody asked me for anything. I felt the pull of it all the same, like a tide.", {"stress": 4}, {"stab": -1, "heat": 4}),
    O("We talked for ten minutes. One of them pressed a number into my hand, 'in case'. I put it in my pocket. I didn't throw it away.", {"stress": 5}, {"stab": -3, "heat": 6})),
  C("Get in the car",
    O("I got in. It was, for a while, wonderful. It was familiar, and warm, and everything I'd missed. Six weeks later, it wasn't.", {"happiness": 4, "stress": 6}, {"stab": -8, "heat": 15, "viol": 1, "pay": 600}),
    O("I got in. Nobody asked anything of me that night. Nobody had to.", {"happiness": 3}, {"stab": -6, "heat": 12, "pay": 300})),
  cooldown=30)

R("re.parent", "👵", "The funeral you can attend",
  "While you were inside, someone died. Now there's a grave, a stone, and a relative who says 'I'm sorry' and then, quietly, 'she asked for you'. The cemetery has gravel paths and a smell of cut grass.",
  C("Go and stand there",
    O("I stood at the stone for an hour. I said what I hadn't been able to say in letters. It didn't make anything right, but something in my chest unclenched a little.", {"happiness": -2, "stress": -6}, {"stab": 4, "support": 3}),
    O("I went at dawn, when the gates opened. I talked to the stone. A man cutting the grass pretended not to hear. I was grateful to him.", {"stress": -4}, {"stab": 3})),
  C("Bring flowers to the family",
    O("They didn't know what to say. We sat in the kitchen and said very little. My aunt gave me a photograph. It's on the shelf.", {"happiness": 3}, {"stab": 5, "support": 6}),
    O("It was awkward and kind. A cousin asked how long I was out for, and nobody laughed, and then everyone did.", {"happiness": 2, "stress": 2}, {"stab": 4, "support": 4})),
  C("Avoid it",
    O("I couldn't. I stayed in my room that week with the blind down. I told myself I'd go next month.", {"happiness": -6, "stress": 6}, {"stab": -5}),
    O("I told myself it was too late to matter. I know that's not true. I think about it most days.", {"happiness": -5, "stress": 4}, {"stab": -3})),
  cooldown=50, once=True)

R("re.child", "🧒", "The child who remembers",
  "She was six when you went in. She's tall now, with your jaw, and she looks at you across the table the way you'd look at a stranger who happened to know your name.",
  C("Be patient",
    O("I didn't push. I asked about school. She told me about a teacher. At the end she asked if I'd come to the school play. I said yes before she'd finished the sentence.", {"happiness": 8}, {"stab": 6, "support": 5}),
    O("I let her decide the pace. Months passed. One Sunday she knocked on the door with her homework. Neither of us spoke about why.", {"happiness": 7}, {"stab": 6, "support": 4})),
  C("Tell her everything",
    O("She listened to all of it, white-faced. At the end she said 'I knew that.' She had known for years. We sat for a long time in the same silence.", {"happiness": 2, "stress": 4}, {"stab": 3, "support": 3}),
    O("I told her. She cried, and was angry, and then she asked a question I'd not expected: 'were you scared?' I said yes. It was the first honest conversation either of us had had.", {"happiness": 3, "stress": 6}, {"stab": 4, "support": 5})),
  C("Make it up with presents",
    O("I bought her a phone I could not afford. She thanked me politely. We both knew.", {"money": -400, "stress": 3}, {"stab": -2, "support": 1}),
    O("Presents. Cinema. A day out that tried too hard. She was kind about it. I understood afterwards that she didn't want things.", {"money": -250, "stress": 2}, {"stab": 0, "support": 2})),
  extra=["kids"], cooldown=50, once=True)

R("re.stranger", "🪪", "Being recognised",
  "A woman at the checkout is looking at you in a certain way. Then she says, quietly, 'I know who you are. I read about it.' She isn't hostile. She isn't friendly. She is simply certain.",
  C("Own it",
    O("'That's right. I did the time. I'm doing something else now.' She nodded slowly. Her till beeped. 'Next,' she said, and the moment was over.", {"stress": 4, "happiness": 2}, {"stab": 4}),
    O("I told her it was true. She didn't say anything else. I went back to that shop for years. We never mentioned it again.", {"stress": 3}, {"stab": 3})),
  C("Deny it",
    O("'You've got me confused with someone else.' She let it go, with a look. It sat in my stomach all day, the lie, and the knowledge that she knew.", {"stress": 8, "happiness": -3}, {"stab": -2}),
    O("I denied it, and left my shopping. I did not go to that shop again.", {"stress": 6}, {"stab": -3})),
  C("Leave without a word",
    O("I put down the basket and walked out. In the street my hands shook. I had done nothing. That was precisely the point.", {"stress": 8}, {"stab": -3}),
    O("I paid, said nothing, and left. Later, I discovered she'd put a note in the bag. 'Good luck.' I still have it.", {"stress": 3, "happiness": 4}, {"stab": 4, "support": 2})),
  cooldown=40)

R("re.money", "💷", "The first wage",
  "It's in the account. It's real. It's not much, but it's earned, in a place with a time clock and a kettle and a man called Terry who nods at you every morning.",
  C("Save it",
    O("I put away every spare penny. By the end of the year I'd saved a sum. It's not large, but it is a margin, and a margin is the difference between a bad month and a bad year.", {"happiness": 3}, {"stab": 6, "pay": 400}),
    O("I saved the lot, and bought nothing. My sister said I was being silly. I told her it felt like a wall.", {"happiness": 2}, {"stab": 5, "pay": 300})),
  C("Spend some on the family",
    O("I took them for a meal, and paid. My mother cried, quietly, into a napkin. I counted the cost and decided it was cheap.", {"money": -250, "happiness": 7}, {"stab": 3, "support": 6}),
    O("I bought presents, and it felt like something. It was money well spent in a way no savings account can measure.", {"money": -200, "happiness": 6}, {"stab": 2, "support": 5})),
  C("Blow it",
    O("A weekend I can only partly remember. It was glorious. Then it was Monday, and it was nothing.", {"money": -500, "happiness": 4, "health": -2}, {"stab": -5}),
    O("I spent it fast, on things I'd been thinking about for years. The pleasure faded faster than the debt.", {"money": -450, "happiness": 2}, {"stab": -4})),
  extra=["employed"], cooldown=40)

R("re.counsel", "🪑", "A circle of chairs",
  "A man from the programme leans against the door. 'There's a meeting on Thursday. Church hall. Tea, biscuits, no one will ask you anything you don't want to say.' He doesn't push. He's been where you are.",
  C("Go",
    O("Eleven people in a circle. A woman spoke about her brother. A man spoke about a car. I said nothing. On the way home I said something to myself, under my breath, that I'd never said before.", {"stress": -5, "happiness": 3}, {"stab": 6}),
    O("I went for the biscuits and stayed for the people. By the third week I was putting the chairs out.", {"stress": -4, "happiness": 4}, {"stab": 7, "support": 3})),
  C("Think about it",
    O("I thought about it for a month. Then a bad night, and a phone call, and I turned up on a Thursday with my hands in my pockets.", {"stress": 4}, {"stab": 3}),
    O("I didn't go. He didn't ask again. The door stays open.", {"stress": 4}, {"stab": -1})),
  C("Say you're fine",
    O("'I'm fine.' He nodded. 'Right.' He went off in a way that said he'd heard the words a thousand times and didn't believe a single one.", {"stress": 5}, {"stab": -3}),
    O("I said I managed. I did, mostly, for another two months.", {"stress": 6}, {"stab": -2})),
  cooldown=40)

R("re.owed", "🏴", "What you were owed",
  "A message comes through a cousin: someone from the old wing says there's a debt, and now that you're out, it's fair game. The amount is small. The tone isn't.",
  C("Pay it",
    O("I took the money to a pub and handed it over in an envelope. He weighed it in his hand and nodded. 'We're square.' We were. I think.", {"money": -350, "stress": 4}, {"stab": 1, "heat": -4, "dues": -20}),
    O("I paid it all. It left me thin for a month. But the message stopped.", {"money": -500, "stress": 5}, {"stab": 1, "heat": -6, "dues": -30})),
  C("Refuse",
    O("I said no. Nothing happened for a month. Then a car followed me home. Then nothing again. You never know.", {"stress": 8}, {"stab": -3, "heat": 8}),
    O("I said I'd done my time. It got back to him. He sent a note saying only 'we'll see', and every footstep behind me for a year sounded like him.", {"stress": 10}, {"stab": -4, "heat": 10})),
  C("Tell my officer",
    O("It felt like the thing I'd spent years learning not to do. But she took it seriously, and the problem went away without my name on it.", {"stress": 4}, {"stab": 4, "heat": -8}),
    O("I told her. She wrote it up and made a call. A week later, a man was moved from one wing to another and that was the end of it.", {"stress": 3}, {"stab": 4, "heat": -6})),
  extra=["debt"], cooldown=40)

R("re.nightmare", "🌙", "Sleeping with the door open",
  "You still wake at 5.40 for a count that doesn't come. You still sit with your back to the wall. You still can't sleep without the door closed and the light a certain way, and last night the sound of someone's key in a lock two flats away put you on the floor.",
  C("Talk to someone",
    O("A GP, twenty minutes, a leaflet. I said the word out loud. 'It's very common, in people who've been inside.' That was all. It was enough.", {"stress": -6, "happiness": 3}, {"stab": 5}),
    O("I told a counsellor everything about the nights. He didn't flinch. We built a list of small things that help. I use it still.", {"stress": -8}, {"stab": 7})),
  C("Handle it myself",
    O("Routines, a light on in the hall, the radio low. It got easier slowly. It never fully stopped.", {"stress": 2}, {"stab": 2}),
    O("I got through it by being tired. I worked double shifts, so I'd sleep. It's not a solution.", {"health": -3, "stress": 4}, {"stab": 0})),
  C("Numb it",
    O("A drink, then another. It worked, until it didn't. A year on, I was on the edge of something I knew the shape of.", {"health": -5, "stress": 8}, {"stab": -7}),
    O("I found something to take the edge off. It took the rest as well.", {"health": -4, "stress": 6, "happiness": -4}, {"stab": -8})),
  cooldown=40, once=True)

R("re.compensation", "⚖️", "The apology that came with a cheque",
  "A letter in an official envelope, and a second, thicker one from a solicitor. The state regrets the error. The state has calculated the regret to the nearest pound, and it is not as much as you would have chosen.",
  C("Take it and rebuild",
    O("The money didn't give back a day, but it made a deposit, and a business loan, and a second chance. I used it carefully, because I know what the absence of it feels like.", {"happiness": 6}, {"stab": 8, "pay": 5000}),
    O("I took it, and put most of it away. The rest went on the things I'd waited years for. I don't regret any of it.", {"happiness": 6}, {"stab": 6, "pay": 3500})),
  C("Fight for more",
    O("It took two more years. A lawyer, a hearing, a thin extra sum, and a statement that I could read aloud. It felt like winning something.", {"stress": 8, "happiness": 2}, {"stab": 3, "pay": 6000}),
    O("I took it to the end of the road and the end of the road was the same figure. But I'd said what I had to say, in a room, with the right people listening.", {"stress": 10}, {"stab": 2, "pay": 1000})),
  C("Give it away",
    O("I gave most of it to the legal charity that had worked on my case. They looked at me as though they had not heard right.", {"happiness": 6, "karma": 8}, {"stab": 2, "pay": 500}),
    O("I split it between a charity and a few people who had written to me. It felt like the only right thing to do with it.", {"happiness": 5, "karma": 6}, {"stab": 2, "support": 4, "pay": 800})),
  extra=["inno"], cooldown=50, once=True)
