from prison_lib import *

# ====================================================================== the first weeks
E("p.first_night", "🌙", "The first night",
  "The door closes at nine. The light in the ceiling does not go out. Somewhere along the landing a man is singing very softly, and another is telling him to stop.",
  ["newbie"],
  C("Lie still and listen",
    O("I lay on my back with my eyes on the ceiling and learned the building from its noises: the pipes, the key-ring, the long tide of voices. By dawn I could tell the officers apart by their footsteps.", {"stress": -1}, {"intel": ["schedule", "The night officer does his round at ten past and again at four"]}),
    O("I listened, and what I heard was a boy two cells down crying into a blanket. I heard it for a week. I never mentioned it to anyone, and neither did he.", {"happiness": -4, "stress": 4}, {"respect": 1})),
  C("Introduce yourself to the cellmate",
    O("{c.first} looked me over for a while, and then moved a box off my bunk. 'Top or bottom,' he said, 'doesn't matter, you'll be here a while.' We were civil from that moment.", {"stress": -3, "happiness": 2}, {"respect": 1}),
    O("{c.first} said nothing at all, for most of the night. In the morning he said two words, and they were 'toilet etiquette', and a very detailed list followed.", {"stress": 1}, {"conduct": 1}),
    ),
  C("Write a letter you won't send",
    O("I wrote four pages to my mother, then burned them in the sink with a match I'd been given. It wasn't brave. It was the only door I had.", {"happiness": -3, "stress": -2}, {"support": 1}),
    O("I wrote to the person I'd done it to. I put no address on it, because I didn't have one, and folded it small. It's still in the Bible I was given.", {"stress": 1, "karma": 3}, {"parole_mood": 3})),
  roles=CELL, cooldown=40, once=True)

E("p.cellmate", "🛏️", "The man on the top bunk",
  "{c.first} has a way of doing things in the cell. He does them in a set order, at a set time, and he does not like it when they change. Today I changed one.",
  ["cellmate"],
  C("Apologise and learn the order",
    O("He took it with a nod. By the end of the month I knew his ritual better than my own, and we had a rhythm that made a seven-by-ten box feel almost like a room.", {"stress": -3}, {"conduct": 2}),
    O("He told me about the habits of a man who'd done twelve years already. It was the best education I got in that building.", {"smarts": 1, "stress": -2}, {"intel": ["rumour", "How the old hands read a new officer"]})),
  C("Stand my ground",
    O("There was a silence, then a long look. He moved one thing back, and we both pretended it hadn't happened.", {"stress": 4}, {"respect": 3}),
    O("It escalated. A shove, a raised voice, an officer at the door. Both of us got a write-up and neither of us got an apology.", {"stress": 8, "happiness": -3}, {"heat": 10, "conduct": -5, "respect": 2})),
  C("Ask to be moved",
    O("The request went in, and an officer read it and tore it in half. I stayed. In the end, I was glad.", {"stress": 3}, {"heat": 2}),
    O("A move, to a cell with a man who sang all night. I'd have given a great deal for the first one back.", {"stress": 6, "happiness": -3}, {"heat": 4})),
  roles=CELL, cooldown=8)

E("p.chow", "🍽️", "Whose table",
  "The mess hall has a geography. There are tables for the gangs, tables for the old hands, a table for the ones who talk to the staff. There's one empty seat, and I'm holding a tray.",
  ["newbie"],
  C("Sit at the empty seat",
    O("It was the table of the Quiet Men. They did not look up. They did not move their trays. At the end of the meal, one of them, without looking at me, said, 'Tomorrow the other end.'", {"stress": 2}, {"respect": 3, "rep": {"quiet": 8}}),
    O("It was the wrong seat. I knew it as soon as I'd sat, from the quality of the silence. A man at the end got up and I was moved, by a hand on my shoulder, to the floor.", {"stress": 6, "happiness": -2}, {"respect": -5, "heat": 3})),
  C("Eat standing at the edge",
    O("I ate quickly, at the end of the counter, and left. Nobody objected. Nobody noticed. For a few weeks I was a tray and a pair of hands.", {"stress": 2}, {"heat": -2}),
    O("A kitchen worker slid an extra piece of bread across the counter without looking at me. I took it. I did not know why, and I didn't ask.", {"happiness": 2}, {"conduct": 1})),
  C("Ask someone",
    O("I asked an older man who was sitting on his own. He looked at my shoes for a long while and said, 'Next to me. Don't talk.' I didn't. We've been in the same row for years.", {"stress": -2, "happiness": 2}, {"respect": 2}, ),
    O("I asked a younger man, who happened to be a member of the Brickhouse Boys. He was delighted to tell me everything, in exchange for something I didn't understand until it was too late.", {"stress": 3}, {"dues": 12, "rep": {"brickhouse": 6}})),
  cooldown=30, once=True)

E("p.test", "🥊", "The test",
  "It's the third week. I'm walking back from the library when a man steps into the corridor and doesn't step out. 'You got a light?' It's a question with a price.",
  ["newbie", "loner"],
  C("Give him a light, politely",
    O("He took it, nodded, and let me through. Everyone in the corridor watched. By lunchtime I had a reputation as someone who could be talked to. By dinner, as someone who could be talked into things.", {"stress": 4}, {"respect": -2, "heat": -2}),
    O("He lit up, looked at the match, and said, 'Fair.' It cost me a pack in the end, but I was left alone for a good while.", {"stress": 2}, {"respect": 1})),
  C("Say no, and mean it",
    O("It took about four seconds to go wrong. I held my ground, and got hit for it, and hit back. It was over before an officer came, and I had a story that preceded me.", {"health": -5, "stress": 7}, {"respect": 8, "heat": 10}),
    O("He looked at me, decided I was not worth the paperwork, and let me by. I walked the rest of the way with a shaking hand.", {"stress": 8}, {"respect": 4})),
  C("Turn round and go the long way",
    O("The long way took ten minutes. Everyone had seen it. A man in the library asked me if I was all right, in a voice that meant 'you're going to have a hard time'.", {"stress": 5}, {"respect": -5}),
    O("I walked the long way for six months. It's a good corridor. Nothing ever happened in it.", {"stress": 2}, {"respect": -3, "heat": -3})),
  cooldown=40, once=True)

E("p.protection", "🤝", "An offer",
  "Two men are waiting in my cell when I come back from the yard. One sits on my bunk. 'We've been asking about you,' he says. 'We think you'd do well with some friends.'",
  ["loner", "served>=1"],
  C("Accept their protection",
    O("It was done with a handshake and a piece of paper I never saw. The next week, a man who'd been leaning on me crossed the yard to avoid me. I belonged to someone, and everyone knew it.", {"stress": -5, "happiness": 2}, {"gang": "brickhouse", "respect": 6}),
    O("The Congregation took me in, with the soft menace of a church that knows where you live. I got prayer, a place at the table and a list of favours to be done.", {"stress": -4, "happiness": 2}, {"gang": "congregation", "respect": 4}),
    ),
  C("Decline, politely",
    O("'Think about it,' he said, and left a pack of cigarettes on the bunk. It sat there for a week. I did not touch it, and it stayed there.", {"stress": 3}, {"respect": 3, "heat": 2}),
    O("They took it well, which was worse. A few days later the man in the next cell was suddenly very interested in my commissary.", {"stress": 6}, {"respect": 1, "dues": 6})),
  C("Play for time",
    O("I told them I'd think. I thought for months. They watched, and waited. It was the nearest thing I'd had to a position in the whole place.", {"stress": 4}, {"respect": 2, "intel": ["rumour", "Who actually runs the east landing"]}),
    O("I told them I'd see. They said, 'Of course', in a voice that made it clear I'd said something stupid.", {"stress": 5}, {"respect": -3, "heat": 3})),
  cooldown=12)

E("p.debt", "💸", "What you owe",
  "It started with a pack of cigarettes and a game of cards. It is now eleven packs, the interest, and a man called {i.first} who stands next to me in the queue and says my name pleasantly.",
  ["debt"],
  C("Pay it, all of it",
    O("It took everything I had and some things I hadn't. {i.first} counted it, nodded, and said it was a pleasure doing business. I slept for the first time in a week.", {"stress": -8, "happiness": 3}, {"dues": -80}),
    O("I paid it by borrowing from someone else, and from there it never ended. But the moment I'd paid {i.first}, I felt a weight come off.", {"stress": -4}, {"dues": -40, "debt": 15})),
  C("Stall him",
    O("I said I'd have it on Friday. And then the next Friday. He smiled the whole time. On the fourth Friday he stopped smiling.", {"stress": 8}, {"dues": 10, "attack": 1}),
    O("I got three weeks. In three weeks I found a way of getting a thing from outside that paid it off. I shouldn't have done it, but it worked.", {"stress": 4}, {"dues": -60, "heat": 8, "stash": 1})),
  C("Go to the officers",
    O("The officer listened to the whole thing and then wrote a name in a book. The man vanished to another wing. I was left alone and marked as someone who talks.", {"stress": 2}, {"dues": -90, "respect": -15, "conduct": 3}),
    O("The officer shrugged, and said he'd see what he could do. The next day I was moved to a different landing. The debt came with me.", {"stress": 6}, {"heat": 3, "dues": 5})),
  roles=INM, cooldown=8)

E("p.shower", "🚿", "The shower block",
  "The shower block is the one place with no cameras. It is also the only place with hot water, and the water is on for four minutes. Today there are two men by the door.",
  ["served>=1", "respect<=50"],
  C("Go in anyway",
    O("They watched me go past. Four minutes of hot water, under a ceiling and a feeling. Nothing happened. Nothing happens, mostly, and that is the trick of it.", {"stress": 4, "health": 1}, {"respect": 1}),
    O("I got in and I got hurt. It was quick. They knew what they were doing. I was found by an orderly, and I told him I'd slipped.", {"health": -12, "stress": 10}, {"attack": 1, "respect": -4})),
  C("Wait until it's quiet",
    O("I waited. I waited until I had nearly missed it, and went in with the last men. Cold water, quick and safe.", {"stress": 2}, {}),
    O("I waited, and for a month I washed at the sink. It isn't dignity. It's a policy.", {"stress": 3, "looks": -2}, {"heat": -1})),
  C("Take someone with me",
    O("I asked the man in the next cell. He said yes at once. Nobody touched us. Having a friend, however slight, is a form of armour.", {"happiness": 2}, {"respect": 2, "friend": 1}),
    O("I asked, and he said no, and I went in on my own. I made it. I owe nobody anything, and it feels both ways.", {"stress": 3}, {"respect": 2})),
  cooldown=12)

# ====================================================================== work, study, faith
E("p.kitchen", "🍳", "In the kitchen",
  "The kitchen is the best job in the building and the most dangerous. There are knives, which are counted, and a loading bay, which is not. Today a man from the other side of the hatch asks me for a favour.",
  ["job:kitchen"],
  C("Pass the parcel through",
    O("It was small and in a cloth, and I didn't look. {off.first}, the officer, saw it and looked at the wall. I was given a bit of rank, and a reason to lie awake.", {"stress": 6}, {"stash": 1, "rep": {"cuervos": 8}, "heat": 6, "respect": 3}),
    O("It was a phone. I knew when I felt the weight. The man said, 'Thursday', and I knew that someone was going to ask me again.", {"stress": 8}, {"stash": 1, "respect": 4, "heat": 10})),
  C("Tell him no",
    O("He nodded, and went. In the morning there was salt in the porridge, and in the afternoon, in the bread. It would be a long month.", {"stress": 4}, {"respect": 2}),
    O("He took it well and stopped asking. But in the queue, afterwards, there were a few more hard looks than usual.", {"stress": 3}, {"respect": 1})),
  C("Tell the supervisor",
    O("He thanked me, and the man was gone by the end of the week. I got a better shift, and, for the rest of the sentence, a very short list of friends.", {"stress": 4}, {"conduct": 6, "respect": -10, "heat": -8}),
    O("The supervisor looked at me for a very long time. 'You'd better be right,' he said. I was, and it cost me.", {"stress": 6}, {"conduct": 4, "respect": -8})),
  roles=OFF, cooldown=10)

E("p.library", "📚", "The law library",
  "The law books are kept in a locked bay at the back, in a separate room, and you can sign up for an hour. Most people use it to look up other people. Today a man is sitting in the other chair, reading my case.",
  ["served>=2"],
  C("Ask him what he's found",
    O("He was a jailhouse lawyer with a broken nose and a flair for procedure. He'd noticed a deadline I'd missed and a form I'd never been given. In two hours he gave me more than my own lawyer had in four years.", {"smarts": 2, "stress": -2}, {"appeal": 8, "intel": ["case", "A missed disclosure in the original trial"]}),
    O("He was a con, and I realised too late. I'd handed him details he could sell, to a man in the next wing, for a pack of cigarettes.", {"stress": 6}, {"heat": 5, "respect": -3})),
  C("Close the book and leave",
    O("I closed it and left. It was a trap, or it wasn't. In prison you're not allowed to know.", {"stress": 2}, {}),
    O("I left and came back later, at a time I knew he wouldn't be there. I read in peace.", {"smarts": 1}, {"appeal": 2})),
  C("Ask him to represent me",
    O("He said it would cost me. He said it would cost me a packet of coffee a month, which was a lot of coffee. But he knew where the documents were.", {"stress": 2}, {"appeal": 6, "dues": 8}),
    O("He said no. He said he was already doing four cases, and had a real lawyer's disdain for the ones who'd been in the dark. But he gave me the forms.", {"smarts": 1}, {"appeal": 3})),
  cooldown=12)

E("p.faith", "🕯️", "The chapel door",
  "The chaplain has been leaving the chapel door open at the same time every Thursday for a year. He doesn't ask anyone to come in. Tonight I'm outside it, deciding.",
  ["served>=1"],
  C("Go in",
    O("It smelled of floor polish and candle smoke. Eight of us on plastic chairs. The chaplain said nothing about God for a long time. He asked what we were afraid of. I told him.", {"stress": -8, "happiness": 4}, {"conduct": 4, "program": "faith", "parole_mood": 3}),
    O("I went in for the warmth and stayed for the singing. I can't sing. The man next to me couldn't either, and it didn't matter.", {"stress": -6, "happiness": 3}, {"conduct": 3})),
  C("Stay outside, and listen",
    O("I stood in the corridor with my back against the wall and listened to a hymn I didn't know. Nobody saw me. It was a good ten minutes.", {"stress": -3}, {}),
    O("I stayed outside. The chaplain nodded when he came out, and said, 'Same time next week.' There's a lot to be said for patient men.", {"stress": -2, "happiness": 1}, {"conduct": 1})),
  C("Use the room for something else",
    O("The chapel is the one place nobody searches. I used it for a handover that ought not to have happened in a holy place. I felt bad about it for a long time.", {"stress": 5, "karma": -4}, {"stash": 1, "rep": {"cuervos": 5}, "heat": 4}),
    O("I used the chapel to speak to a man I couldn't speak to anywhere else. We sat in the back row and talked, like worshippers.", {"stress": 2}, {"intel": ["weakness", "A bent officer on the east landing"], "respect": 2})),
  cooldown=14)

E("p.letter_child", "✉️", "A drawing",
  "An envelope with a children's drawing in it: a house, a very large sun, a figure standing in the garden with enormous hands. Underneath, in careful pencil: DADDY / MUMMY. I don't know which one the child meant.",
  ["kids", "support>=20"],
  C("Pin it up above the bunk",
    O("It's been there since. The officers do their searches around it. The cellmate once moved a thing, and then moved it back. We have never discussed it.", {"happiness": 6, "stress": -4}, {"support": 6}),
    O("I pinned it up and the corners peeled, and I put it up again with toothpaste. It lasted for years, in the end.", {"happiness": 5}, {"support": 5})),
  C("Write back at length",
    O("It took me a week. I drew a picture, badly, of the garden. A reply came with a drawing of mine, much improved. We've been corresponding for years, in the language of the very young.", {"happiness": 7, "stress": -4}, {"support": 10}),
    O("I wrote four pages, and tore them up, and wrote one. The one is the best thing I have ever written.", {"happiness": 5}, {"support": 8})),
  C("Put it away, and don't look at it",
    O("I put it in the bottom of the box, where I would not see it. I needed to survive the day, and that was not a day for pictures.", {"happiness": -3, "stress": 2}, {"support": -3}),
    O("I looked at it once, put it away, and didn't write. There are things that you can't look at until you can.", {"happiness": -4, "stress": 3}, {"support": -4})),
  cooldown=10)

E("p.visit", "🪟", "The glass",
  "The visiting room has a table, a clock and a pane of scratched Perspex. {off.first} the officer stands by the door. On the other side of the glass is the person I've been waiting for since the last time.",
  ["partner", "support>=30"],
  C("Say what I've been rehearsing",
    O("I said it all. I said it badly. They listened and nodded and said a very simple sentence back that undid the rehearsal. We both cried, and the officer looked at the ceiling.", {"happiness": 8, "stress": -6}, {"support": 10}),
    O("I said it. It was the wrong way round, and somehow they heard the right thing. 'I know,' they said. It was enough.", {"happiness": 6, "stress": -4}, {"support": 8})),
  C("Talk about nothing",
    O("We talked about the weather, and the dog, and the price of tea. The clock ran down. I'd never loved anyone so much as in that talk about the price of tea.", {"happiness": 5}, {"support": 6}),
    O("We talked about nothing, and it was the right thing. At the end, they put their hand on the glass and I put mine on it.", {"happiness": 6}, {"support": 7})),
  C("Tell them not to come any more",
    O("I said it as kindly as I could. I said it was for their sake. They looked at me for a very long moment and said, 'No.' I didn't know whether to be relieved.", {"happiness": 2, "stress": 6}, {"support": 4}),
    O("I said it, and they believed it. They stopped coming. I told myself it was a gift. It took a long time to stop believing that.", {"happiness": -10, "stress": 8}, {"support": -25})),
  roles=OFF, cooldown=6)

# ====================================================================== the economy
E("p.cards", "🃏", "A game on the landing",
  "A game of cards has started on the third landing, and the stakes are not cigarettes. They are favours. Someone has just put down a name.",
  ["served>=1"],
  C("Sit in",
    O("I played the hand I had, which was the right hand. I won a favour from a man who couldn't afford to lose it. It's a currency I've been spending ever since.", {"happiness": 4}, {"respect": 5, "intel": ["rumour", "A debt that someone cannot pay"]}),
    O("I lost the hand and a name, a favour on the books for a man who would need it. I paid it, in time, in a way I won't go into.", {"happiness": -4, "stress": 6}, {"dues": 15, "heat": 5})),
  C("Watch from the rail",
    O("I stayed on the rail, and watched, and counted. A man who watches long enough knows who cheats.", {"smarts": 1}, {"intel": ["weakness", "The man who deals twice from the bottom"]}),
    O("I watched for an hour and left. Nobody invited me back. It was both a loss and a decision.", {}, {"respect": -1})),
  C("Tip off the officers",
    O("It was a snitch's move, and no one saw it. The game stopped for a month, and I was not the only one who suspected a rat.", {"stress": 6}, {"conduct": 5, "respect": -6, "heat": -4, "debt": 0}),
    O("I told an officer. He nodded and said he knew. I was left with the hot, small taste of having done something and not having helped.", {"stress": 5}, {"conduct": 2})),
  cooldown=10)

E("p.tattoo", "🖋️", "Ink",
  "There's a man on the second landing who does tattoos with a needle from a motor and ink from a melted comb. His chair is a plastic bucket. He has a queue.",
  ["served>=1"],
  C("Get one",
    O("It took three hours and hurt like hell. The name on my forearm is my daughter's. Hers is the first name I've had written on me. I look at it when the day goes bad.", {"happiness": 4, "health": -2}, {"heat": 4, "respect": 2}),
    O("It was the name of the block, the gang and a date. It's a bid for belonging. It's on my arm for life, and so is the price.", {"happiness": 2}, {"respect": 6, "gang_rank": 0, "heat": 6})),
  C("Offer to help run the queue",
    O("I held the lookout and counted the minutes. In the end I got a cut of the tobacco and a story to tell. The inked ones remembered who stood watch.", {"stress": 3}, {"respect": 4, "stash": 0, "heat": 4}),
    O("We were caught on the third day. The man took the blame and I took a lesser one. Both of us lost a few privileges.", {"stress": 6}, {"conduct": -4, "heat": 12})),
  C("Keep out of it",
    O("I stayed out. The queue went on without me. The man had to move his chair twice.", {}, {}),
    O("I stayed out. A month later, the whole landing was searched, and the chair was found in the third cell along. I had a clean sheet.", {"happiness": 1}, {"conduct": 2})),
  cooldown=14)

E("p.drone", "🛸", "Something on the roof",
  "At two in the morning a small shape crosses the beam of the floodlight and lands on the roof of the workshop. In the morning a man in the yard asks if I saw anything.",
  ["served>=2", "tension<=80"],
  C("Say I saw nothing",
    O("He nodded, and a week later I found a packet of tobacco under my pillow. I hadn't asked for it. That's how you know you're in.", {"stress": 4}, {"stash": 1, "respect": 3, "heat": 4}),
    O("He grinned and said, 'Good.' I didn't know what I'd agreed to, but I knew that I'd agreed.", {"stress": 4}, {"respect": 2, "rep": {"cuervos": 6}})),
  C("Tell an officer",
    O("The roof was searched, and a package was found. The officer wrote my name in a book and under it, a tick. I don't know what the tick means.", {"stress": 4}, {"conduct": 5, "respect": -8, "heat": -5}),
    O("I told {off.first}. He nodded, and made a note. The following week, I was given a job in the library.", {"stress": 3, "happiness": 2}, {"conduct": 4, "respect": -5})),
  C("Go up there yourself",
    O("It took two men and a ladder. In the bag there were four phones and a lot of small, expensive pills. I took one phone and left the rest. A man who takes everything gets caught.", {"stress": 8}, {"stash": 1, "heat": 10, "respect": 5, "intel": ["tool", "A route up to the workshop roof"]}),
    O("I got as far as the ledge, and the floodlight swung. I froze for a very long minute. Then it moved on, and I went back down with nothing.", {"stress": 8}, {"heat": 4, "respect": 1})),
  roles=OFF, cooldown=14)

# ====================================================================== the case
E("p.lawyer_drops", "📞", "She stopped returning calls",
  "My lawyer hasn't answered in five months. Today a letter arrives from her office on thin cream paper. It uses the word 'regrettably' twice.",
  ["inno", "served>=2"],
  C("Fight for her to stay",
    O("I wrote eleven letters, all polite. One reached her. She took the case back, grudgingly, with a few ground rules. It's a poor marriage but it's a marriage.", {"stress": 4}, {"appeal": 4}),
    O("I wrote to her firm, to the bar association and to her mother, who sent back a kind, evasive postcard. She stayed on.", {"stress": 3}, {"appeal": 3, "heat": 2})),
  C("Represent myself",
    O("I did it. I did it in the library at night with a dictionary and a sheaf of forms. I got a hearing, and the judge remarked on the quality of the drafting. It didn't help the case, but it helped me.", {"smarts": 3, "stress": 6}, {"appeal": 8}),
    O("I did it and got buried by the procedure. The judge was kind. The state's lawyer was not. I learned more about the law in a month than I had in the previous ten years.", {"smarts": 3, "stress": 8}, {"appeal": 3})),
  C("Look for another lawyer",
    O("A pro bono clinic took the file. It was an eager twenty-six-year-old with a law degree and a conscience. I asked her how many she'd saved. 'None,' she said. 'Yet.'", {"happiness": 4, "stress": -2}, {"appeal": 6, "lawyer": 12}),
    O("There was nobody. The waiting lists were years. I put my name on three of them.", {"stress": 4}, {"appeal": 2})),
  roles=LAW, cooldown=12)

E("p.dna", "🧬", "The test",
  "A student at the innocence clinic has found an unopened evidence box. Inside is a stain the lab never tested, and a signature on the chain-of-custody form that does not match.",
  ["inno", "appeal>=25"],
  C("Ask for the test, and wait",
    O("It took fourteen months. The result came back on a Tuesday: not mine. A second profile, no match on the database, and a hearing date. I had to sit down on the floor.", {"happiness": 12, "stress": 8}, {"appeal": 30}),
    O("The lab was backlogged. The test was done at last. It was inconclusive, a stain too degraded to read. It was the worst news I could imagine and, somehow, it kept the case open.", {"happiness": -4, "stress": 8}, {"appeal": 8})),
  C("Go to the press",
    O("A news programme ran it. The prosecutor made a statement. The pressure moved the hearing forward by half a year, but it also moved a lot of people's minds against me.", {"stress": 8}, {"appeal": 20, "heat": 6}),
    O("A journalist wrote a long piece. It was fair and generous. I was told it had been read in the prosecutor's office with a sense of professional alarm.", {"happiness": 6, "stress": 4}, {"appeal": 15})),
  C("Do nothing; be afraid of it",
    O("I let the student do all the work. I could not bear to get my hopes up again. When the box was opened I was on the yard, pretending it was a day like any other.", {"stress": 8, "happiness": -3}, {"appeal": 12}),
    O("I told the clinic to stop. I said it wasn't worth another heartbreak. They didn't stop. I was furious, and they were right.", {"stress": 6}, {"appeal": 15})),
  cooldown=30, once=True)

E("p.victim", "👤", "A letter from the family",
  "A letter has come through the victims' liaison office. It's addressed to me, and it is handwritten, and the handwriting is a woman's.",
  ["served>=3", "story:first"],
  C("Read it",
    O("It said that she hadn't forgiven me and wasn't going to. It said her son was eleven when it happened and was nineteen now. It said that she wanted me to know that a person had been lost. I read it once, and I have never forgotten a word.", {"happiness": -8, "stress": 8, "karma": 5}, {"parole_mood": 6, "conduct": 2}),
    O("I read it in the chapel. She wrote about her husband's hands. I wrote back. It took me months. I don't know if she read it.", {"happiness": -4, "stress": 6, "karma": 6}, {"parole_mood": 8})),
  C("Don't open it",
    O("I put it in my box, unopened, with the others. Eventually there were five.", {"stress": 4}, {"parole_mood": -3}),
    O("I gave it to the chaplain to hold. He said he'd keep it until I wanted it. He kept it for twelve years.", {"stress": 2}, {})),
  C("Write back, briefly",
    O("I said I was sorry, in the plainest words I could find. I said there wasn't anything I could do. I did not ask for anything. No answer came.", {"karma": 6, "stress": 4}, {"parole_mood": 7}),
    O("I wrote four lines. She replied with two. It was the beginning of a long, painful correspondence, and the most honest thing in my sentence.", {"karma": 8, "stress": 6}, {"parole_mood": 10})),
  cooldown=40, once=True)

E("p.deal", "📋", "A deal",
  "A man in a good coat is sitting in the interview room with a folder. He says that I am someone who knows things, and that there is a way of using them. He says 'cooperation', slowly, as if it were an old friend.",
  ["served>=3"],
  C("Hear him out",
    O("The offer was a reduced sentence and a transfer. All I had to do was say what I knew about a man called {i.first}. It was nothing I hadn't already guessed. I thought about it for a month.", {"stress": 6}, {"intel": ["deal", "The prosecutors want a name on the east landing"]}),
    O("He wanted a statement about a murder I knew a little about. He wanted my name on it. I left with a copy of the offer and a feeling I would carry like a stone.", {"stress": 8}, {"intel": ["deal", "An offer to testify"]})),
  C("Take the deal",
    O("I signed. I did it in a room with a window. Six months later I was gone, to another prison, with three years off. There wasn't a person in the building who didn't know why.", {"stress": 8, "happiness": -4}, {"sentence": -3, "transfer": "better", "respect": -30, "conduct": 6}),
    O("I took it. The man I named got fifteen years. I never saw him again, but I thought about him daily.", {"stress": 10, "karma": -8}, {"sentence": -2, "respect": -25, "conduct": 4, "transfer": "worse"})),
  C("Refuse",
    O("I said no. He didn't argue. He packed his folder and said, 'That's what they all say, the first time.' It was another four years before I saw anyone in a good coat.", {"stress": 4, "karma": 3}, {"respect": 4}),
    O("I said no, and said it loudly, in a corridor where others could hear it. It cost me nothing and bought me a great deal.", {"stress": 2}, {"respect": 10})),
  roles=INM, cooldown=30, once=True)

# ====================================================================== people
E("p.mentor", "🧓", "The old head",
  "He has been inside since before I could drive. He sits on the same bench every day and does the crossword in pencil. He has not said a word to me in two years. Today he says, 'Sit down.'",
  ["served>=2", "respect>=15"],
  C("Sit",
    O("He taught me for an hour: who to be careful of, what to eat, how to hold my face. 'The thing about time,' he said, 'is you don't do it. It does you. Be doing something.' I've never forgotten that.", {"smarts": 2, "stress": -4}, {"respect": 4, "conduct": 3, "friend": 1}),
    O("He told me a story about a man he'd known who'd lost his mind in the fourth year. He said, 'Don't be that man.' I said I wouldn't.", {"smarts": 1, "stress": -2}, {"respect": 3, "intel": ["rumour", "What the old heads say about the new warden"]})),
  C("Say I'm busy",
    O("He nodded, and went back to the crossword. I never got another invitation.", {"stress": 2}, {"respect": -2}),
    O("I told him I was busy. He smiled. 'Yes,' he said. 'You are.' It is the thing I regret most from the second year.", {"stress": 3}, {})),
  C("Ask him what he wants",
    O("'Nothing,' he said. 'That's the point.' It took me a long time to understand it.", {"smarts": 1}, {"respect": 1}),
    O("He wanted a favour, small, from the library. I did it. We were friends after that, if that's what you call an old man and a young one with a pencil between them.", {"happiness": 3}, {"respect": 3, "friend": 1})),
  cooldown=20, once=True)

E("p.young", "🧒", "The kid on the landing",
  "He is nineteen and he looks fifteen. He has been in for a week and he hasn't eaten. Someone has already spoken to him about the debt that he is going to owe.",
  ["served>=3", "respect>=20"],
  C("Take him under your wing",
    O("I taught him the order of things. I stood next to him in the mess hall, and nobody touched him. He called me 'sir' for a month. He was released four years later, and the first letter I received was from him.", {"happiness": 6, "karma": 6}, {"respect": 3, "friend": 1}),
    O("I took him on. It cost me. A debt of his became a debt of mine, and I didn't tell him. He's out now, and doing well. I'd do it again.", {"karma": 8, "stress": 4}, {"dues": 10, "respect": 5})),
  C("Keep out of it",
    O("I kept out of it. In a month he'd found someone else's wing. I did not see him again, and I know what that means.", {"karma": -4, "stress": 4}, {}),
    O("I looked away. It's a decision with a long half-life.", {"karma": -5, "happiness": -3}, {"respect": 0})),
  C("Use him",
    O("A boy who owes you is a pair of hands. He took parcels, kept watch, did what I asked. He thought I was kind. I'm not proud of it.", {"karma": -10, "stress": 4}, {"stash": 1, "respect": 6, "heat": 4}),
    O("I used him, in a small way. Nobody was hurt. But I saw his face when he realised what he had been, and I will not forget it.", {"karma": -8, "stress": 5}, {"respect": 4})),
  cooldown=14)

E("p.officer_kind", "👮", "Someone who calls you by name",
  "{off.first} has called me by name for six months. Not my number. My name. This morning at the cell door he said, 'Mind how you go, {off.first}'s not on tonight,' as though he were warning me about the weather.",
  ["served>=2"],
  C("Trust him a little",
    O("I told him about my daughter. He told me about his. It's the nearest thing to a friendship that the building permits, and it's not much, and it's a great deal.", {"happiness": 4, "stress": -3}, {"conduct": 3, "intel": ["schedule", "His shift pattern changes on the first of the month"]}),
    O("I told him one thing, and he told me one thing back. It was enough. It's amazing how little it takes.", {"happiness": 3}, {"conduct": 2})),
  C("Stay wary",
    O("In my experience, kindness is a form of leverage. I stayed civil, and gave nothing. He seemed to understand that. We nodded at each other for years.", {"stress": 2}, {"heat": -2}),
    O("I answered in monosyllables. He seemed hurt, and then, finally, bored. I felt both relief and loss.", {"stress": 2}, {})),
  C("Ask him for something",
    O("I asked for a book to be let in. A week later it came, with a note that said 'Don't make me regret it.' I haven't.", {"happiness": 3}, {"conduct": 1, "heat": 3}),
    O("I asked him to look the other way once. He did. A year later he asked me to look the other way. I haven't forgotten it.", {"stress": 5}, {"stash": 1, "heat": 6})),
  roles=OFF, cooldown=10)

E("p.officer_cruel", "👮", "Not a good one",
  "{off.first} is the kind of officer the building keeps. He finds a reason for a search, a delay, a cold meal, and then a reason to write it down. Today he has stopped at my cell with a clipboard and a smile.",
  ["served>=1"],
  C("Say nothing, and take it",
    O("It was a long afternoon, and a longer evening, and a night I didn't sleep. When he'd gone, I picked up the pieces and put them back. I told nobody.", {"stress": 8, "happiness": -4}, {"heat": 2}),
    O("I stood against the wall and took it. It's a form of dignity. He wrote nothing down, in the end, and I'm still not sure why.", {"stress": 5}, {})),
  C("Answer back",
    O("I said something. It was exactly the right thing, and it was exactly the wrong thing, and the charge sheet that followed listed it as 'insolence'.", {"stress": 10, "happiness": -3}, {"heat": 14, "conduct": -8, "respect": 3}),
    O("I answered back. The other prisoners had been waiting years for someone to. I got three days' segregation and a month of cold stares from the staff, and an inch of grudging respect from the wing.", {"stress": 8}, {"heat": 12, "respect": 6})),
  C("File a complaint",
    O("A form, a number, a stamp. It went through channels. A man in a suit came to ask me questions. {off.first} was moved to another wing. I wasn't thanked.", {"stress": 4, "happiness": 2}, {"conduct": 2, "heat": 4, "respect": -2}),
    O("The complaint was lost. The next month, I was moved to a worse cell. These two facts may or may not be connected.", {"stress": 8}, {"heat": 6})),
  roles=OFF, cooldown=10)

E("p.pen_pal", "💌", "A stranger's letters",
  "A woman I've never met has written to me. She says she saw my name on a list at her church. Her handwriting is very upright, and she asks no questions about what I did.",
  ["served>=2"],
  C("Write back",
    O("We wrote for six years. She never asked what I did. She sent photographs of her garden. When I got out, I found it exactly as she'd described it.", {"happiness": 6, "stress": -4}, {"support": 8}),
    O("I wrote back, and the correspondence grew. She sent a book each month. The books were the kind that change how a person thinks, and I'm grateful.", {"happiness": 5, "smarts": 2}, {"support": 6})),
  C("Wait",
    O("I held the letter for a month. Then I wrote, awkwardly, and she answered at once, as if no time had passed.", {"happiness": 3}, {"support": 4}),
    O("I waited, and waited, and in the end it was too late. A second letter came, and then no third. I don't know why I didn't answer.", {"happiness": -3}, {})),
  C("Suspect a con",
    O("I did the checks: the name, the church, the address. Everything was real. I wrote, and apologised for the delay. She answered in two lines: 'I'd have done the same.'", {"smarts": 1, "happiness": 3}, {"support": 4}),
    O("I suspected a con. I was right: it was a scheme, a request for a loan, and a moment of real disappointment. I had thought it was kindness.", {"happiness": -4, "stress": 3}, {"heat": 2})),
  cooldown=30, once=True)
