# Exec'd by gen_pets.py (shares E, C, O, HOME, OWN). Pets Life v0.21: the seasons, the vet, strangers, other animals.

E("pc.snow", "❄️", "The first snow",
  "I wake to a light that is the wrong colour, and a silence that is too thick. {o.first} opens the door and the world is white. It smells of nothing and everything.",
  HOME,
  C("Race out into it",
    O("I ploughed a long furrow across the garden, face first, and came back in with a beard of ice. {o.first} laughed until the kettle boiled over.", {"happiness": 8, "stress": -4}, {"fitness": 2, "bond": 3}),
    O("I discovered that snow can be eaten, rolled in and carried indoors. All three had consequences.", {"happiness": 6}, {"instinct": 3, "mischief": 1})),
  C("Test it with one paw",
    O("Cold. Interesting. Not an emergency. I stood in the doorway and supervised.", {"stress": -2, "happiness": 2}, {"bond": 1}),
    O("I went out, found it very serious, and returned to the radiator with an expression of deep betrayal.", {"happiness": 1}, {})),
  C("Stay by the heater",
    O("Nobody could make me move. I slept through the whole of the white day, and counted it a good one.", {"happiness": 4, "stress": -5}, {"belonging": 3}),
    O("I watched from the window. It looked like an expensive version of the world.", {"happiness": 3, "stress": -3}, {})),
  roles=OWN, cooldown=8)

E("pc.vet_bill", "💷", "The estimate",
  "The vet is kind and gentle and says a number out loud. Then she says it again, slower. {o.first} goes very quiet.",
  {"pet": ["has_home", "owner", "adult"]},
  C("Look as sorry for myself as possible",
    O("It worked, a little. {o.first} signed the form. We went home and I received a treat the size of my head.", {"happiness": 2, "stress": 3}, {"bond": 3, "means": -4}),
    O("It did not work, but {o.first} paid anyway. For a week the tins were the cheap ones.", {"happiness": 0, "stress": 3}, {"bond": 4, "means": -5})),
  C("Be brave on the table",
    O("I held still while they did the thing. The vet said I was a credit to my species. I wasn't, but I let her say it.", {"stress": 4, "health": 3}, {"obedience": 3, "bond": 2}),
    O("I was brave until the second needle. After that I was loud.", {"stress": 5, "health": 3}, {"bond": 2})),
  C("Try to leave",
    O("I got the door open and as far as the car park. The receptionist caught me by the collar and gave me a biscuit, which I resented.", {"stress": 5}, {"escapes": 1, "obedience": -2}),
    O("I wedged myself behind the bins. It took two staff and one tin of tuna to retrieve me.", {"stress": 5, "health": 2}, {"obedience": -3})),
  roles=OWN, cooldown=12)

E("pc.stranger_hand", "🖐️", "A stranger's hand",
  "A person I don't know has bent down to the garden fence. They smell of other animals and of pockets. They hold out a hand.",
  {"pet": ["has_home", "owner"]},
  C("Sniff, and allow it",
    O("They scratched the exact place behind my ear that I'd been trying to reach for a week. I became their friend for life, and told {o.first} all about it.", {"happiness": 5}, {"belonging": 2}),
    O("A decent hand, as hands go. {o.first} said, 'Don't be so friendly,' but I'd already decided.", {"happiness": 3}, {"belonging": 1})),
  C("Bark until they go",
    O("They went. {o.first} thanked me, gruffly. I'd have done it for free.", {"stress": 2, "happiness": 1}, {"instinct": 3, "territory": 3}),
    O("They went, laughing, which was worse than being frightened.", {"stress": 2}, {"instinct": 2, "territory": 2})),
  C("Watch from the window",
    O("I stayed where I was, one eye on them and one on the bowl. Neither of us blinked first.", {"stress": 1}, {}),
    O("I watched them walk the whole length of the road. They looked back at me twice.", {"happiness": 1}, {})),
  roles=OWN, cooldown=10)

E("pc.visiting_animal", "🐾", "Somebody else's animal",
  "A friend of the house has brought their own animal for the weekend. It is the wrong shape and the wrong smell and it is on my sofa.",
  {"pet": ["has_home", "owner"]},
  C("Share the sofa, with conditions",
    O("We agreed on a line down the middle. By Sunday I'd had to adjust it twice, in its favour.", {"happiness": 4}, {"belonging": 3, "obedience": 1}),
    O("A long stare, a nudge, a settling. It left on Monday and I found I minded.", {"happiness": 3}, {"belonging": 2})),
  C("Establish who's in charge",
    O("A short, loud business. I won, on technicalities. We parted on formal terms.", {"stress": 3, "happiness": 2}, {"standing": 4, "instinct": 2}),
    O("I lost. It's fine. I plan to challenge the result.", {"stress": 4}, {"standing": -3})),
  C("Retreat to the bedroom",
    O("I took the bed and the cushion and left the world to them. They broke a vase. I did not say 'I told you so', but I thought it very loudly.", {"stress": 1, "happiness": 1}, {"bond": 2}),
    O("I sulked on the stairs. {o.first} brought me my favourite blanket and sat with me.", {"happiness": 2, "stress": -2}, {"bond": 4})),
  roles=OWN, cooldown=12)

E("pc.holiday_boarding", "🧳", "The suitcases come out",
  "The big bag is on the bed. The small bag is on the floor. Everyone is being kind to me in a way I do not trust.",
  {"pet": ["has_home", "owner"]},
  C("Sit on the suitcase",
    O("It didn't help, but it was noticed. {o.first} cried a little and cuddled me and left anyway.", {"stress": 4, "happiness": -2}, {"bond": 3}),
    O("I got locked in the bedroom for it. Two hours. The suitcase stayed zipped.", {"stress": 3}, {"obedience": -2, "mischief": 1})),
  C("Go to the boarding place",
    O("A row of animals and a woman who called me 'sweetheart'. It was fine. It was fine. Please come back.", {"stress": 4, "happiness": -1}, {"belonging": -3}),
    O("I made a friend in the next kennel. We talked through the bars about our people.", {"stress": 2, "happiness": 2}, {"mischief": 0})),
  C("Stay with a neighbour",
    O("The neighbour fed me too much, walked me too far and let me on the bed. I returned home plumper and thoroughly corrupted.", {"happiness": 4}, {"belonging": 2, "mischief": 1}),
    O("The neighbour was kind but forgot my dinner twice. I forgave them, with an edge.", {"happiness": 1, "stress": 2}, {})),
  roles=OWN, cooldown=10)

E("pc.birdsong", "🐦", "The nest above the door",
  "Something small has built something small above the porch light. All day long it comes and goes, and I have lost my composure about it.",
  {"pet": ["has_home"]},
  C("Watch, and wait",
    O("Weeks of patience. I saw them hatch, fledge and fly. I am prouder than I have any right to be.", {"happiness": 6, "stress": -3}, {"instinct": 2}),
    O("I watched until the chicks left. Then I sat on the step for a day, bereft.", {"happiness": 4}, {"instinct": 2})),
  C("Try to get at them",
    O("I got as far as the porch roof. {o.first} took a photograph of me from below. I have asked for it to be destroyed.", {"stress": 3, "happiness": 2}, {"mischief": 2, "escapes": 0}),
    O("I fell off the bin. I was not hurt, only humiliated.", {"stress": 3, "health": -1}, {"mischief": 1})),
  C("Pretend not to be interested",
    O("I stared firmly in another direction. The birds knew. I knew.", {"happiness": 1}, {}),
    O("I looked at the wall for an hour. It was a very good wall.", {"happiness": 1}, {})),
  roles=OWN, cooldown=15)

E("pc.thunder_friend", "⛈️", "A shelter in the storm",
  "The sky has gone dark and the first drop sounds like a coin on the roof. A smaller, wetter animal has appeared at the window and is looking at me with huge eyes.",
  {"pet": ["has_home", "owner"]},
  C("Let them in",
    O("A cat, soaked through. {o.first} found a towel, and we spent the storm in a heap. The cat left in the morning. It came back the next week.", {"happiness": 6, "stress": -3}, {"mischief": 0, "belonging": 3}),
    O("A rather rude young dog, who took my water and my cushion and stayed until the weather cleared.", {"happiness": 3, "stress": 2}, {"mischief": 0})),
  C("Growl at the glass",
    O("It went away. I felt both safe and a little ashamed.", {"stress": 2}, {"territory": 2, "instinct": 2}),
    O("It went, and the storm took it. I thought about that for some time.", {"stress": 3, "happiness": -2}, {"instinct": 1})),
  C("Fetch {o.first}",
    O("I barked and pulled until they came. They opened the door. I'd like it known that this was my idea.", {"happiness": 5, "stress": -2}, {"bond": 5, "heroics": 1}),
    O("I made the noise I use for emergencies. It worked. They came running.", {"happiness": 4}, {"bond": 4})),
  roles=OWN, cooldown=18)

E("pc.old_friend_gone", "🌿", "The empty garden",
  "A neighbour's animal I've known all my life has stopped coming to the fence. There's a bowl in the garden that nobody has moved.",
  {"pet": ["has_home", "senior"]},
  C("Wait at the fence",
    O("I waited until the light went. {o.first} came out and sat with me. Neither of us said anything.", {"happiness": -4, "stress": 3}, {"bond": 5}),
    O("I watched the gap in the hedge for a month. Slowly I understood.", {"happiness": -5}, {"belonging": 2})),
  C("Carry on, differently",
    O("I made my rounds. It was a bit slower than before. I stopped at the fence each time anyway.", {"happiness": -1}, {"territory": 2}),
    O("I took the long way round and found a new friend, a younger one, who needed teaching.", {"happiness": 2}, {"mischief": 0})),
  C("Stay close to {o.first}",
    O("We sat together on the step most evenings that autumn. It was the nicest thing I did all year.", {"happiness": 3, "stress": -4}, {"bond": 6}),
    O("I followed them from room to room. They let me.", {"happiness": 2, "stress": -3}, {"bond": 5})),
  roles=OWN, cooldown=25)

E("pc.new_house_smell", "🏡", "Boxes",
  "The house is turning into cardboard. The chairs are in the hall. All my favourite places are being put in boxes, one by one, and I'm being told that it's fine.",
  {"pet": ["has_home", "owner"]},
  C("Guard my things",
    O("I sat in the box with my blanket in it. It was not moved. We went together.", {"stress": 3, "happiness": 1}, {"bond": 3}),
    O("They moved me with the blanket. Nobody was deceived but we all kept up the act.", {"stress": 3}, {"bond": 2})),
  C("Hide",
    O("I was found in a wardrobe at the last minute. {o.first} had gone through three rooms in a panic.", {"stress": 5}, {"bond": 1, "mischief": 1}),
    O("I hid in the car, which was the right instinct and the wrong car.", {"stress": 4}, {"mischief": 1})),
  C("Help with the packing",
    O("I removed one item from every box. Eventually there was a decent pile on the floor. It was not appreciated.", {"stress": 2, "happiness": 2}, {"mischief": 2}),
    O("I supervised. I have strong opinions about bubble wrap.", {"happiness": 2}, {"mischief": 1})),
  roles=OWN, cooldown=25)
