from prison_lib import *

# ====================================================================== a few more of the days
E("p.cat", "🐈", "The cat in the yard",
  "A thin tabby has been getting through the wire for a month. It sleeps in the workshop. This morning there are four men around it, and nobody has said a word, and nobody has tried to move it.",
  ["served>=2"],
  C("Feed it",
    O("I saved a corner of my bread. The cat accepted it. For two years it was the nearest thing the wing had to a mascot. Men who didn't speak to each other spoke about the cat.", {"happiness": 6, "stress": -5}, {"respect": 2, "conduct": 1}),
    O("I fed it. Another man gave it a name. A third built it a bed from a box. It's the one thing in the building that no officer ever mentioned.", {"happiness": 6, "stress": -5}, {"respect": 2})),
  C("Pick it up",
    O("It let me. It was warm. It smelled of oil and dust. I held it for a minute, and the four men watched, and none of us said anything. I had forgotten what it was to hold a living thing that wasn't afraid.", {"happiness": 8, "stress": -6}, {"respect": 1}),
    O("I picked it up. It bit me. I laughed, and so did the others. It was the first time I'd laughed in a month.", {"happiness": 6, "stress": -4}, {})),
  C("Report it",
    O("I told an officer. The cat was removed that afternoon, and I never found out where it went. I was not popular.", {"stress": 4, "happiness": -4}, {"conduct": 2, "respect": -6}),
    O("I reported it. The officer looked at me for a long time and said, 'You're a strange one.' The cat stayed.", {"stress": 3}, {"conduct": 1, "respect": -3})),
  cooldown=40, once=True)

E("p.heatwave", "🌡️", "The heat",
  "The thermometer in the officers' station reads thirty-nine. In the cells it is higher. The windows don't open. Men lie on concrete in their shorts and do not move. The tension is something you can feel on your skin.",
  ["tension>=35"],
  C("Lie still and endure",
    O("I lay on the floor with a wet towel and my eyes closed, for eleven days. It ended, as it does. I learned that I could do eleven days of anything.", {"health": -4, "stress": 6}, {"tension": 4}),
    O("I endured. A man two cells down was taken to the infirmary on the sixth day. I heard the trolley. I put the towel over my face.", {"health": -5, "stress": 8}, {"tension": 5})),
  C("Organise water for the landing",
    O("I got the kitchen to leave out the ice. I got an officer to turn a blind eye to buckets. We kept the landing alive. I'd earned something, though I didn't know what.", {"stress": 6, "karma": 4}, {"respect": 5, "tension": -6, "heat": 4}),
    O("I did the rounds with a bucket. The ones who'd been rude to me drank first. It's an odd sort of leadership.", {"stress": 6, "karma": 4}, {"respect": 4, "tension": -4})),
  C("Use the confusion",
    O("A heatwave is a distraction. In the long afternoon, with everyone half asleep, I walked the whole of the east side of the wing and noted what I saw.", {"stress": 4}, {"intel": ["blindspot", "The east stairwell camera is unplugged in the heat"]}),
    O("Half the cameras were out of order, the other half were pointed at the wall. I counted them. It was an education.", {"stress": 4}, {"intel": ["blindspot", "Half the cameras fail in a heatwave"]})),
  cooldown=16)

E("p.transfer", "🚌", "The list",
  "A list goes up on the noticeboard at six. My name is on it. 'Transfer: 0700 Thursday.' Nobody says where. Nobody ever does. I have three days to say goodbye to a building I have hated for years and can't picture leaving.",
  ["served>=4"],
  C("Accept it",
    O("The bus left at seven. I watched the old building go past through a gap in the blind. It was smaller from outside. The new place was brighter, noisier, newer, and had no history with me at all.", {"stress": 6, "happiness": -2}, {"transfer": "better"}),
    O("I accepted it. The new place was worse, which I had expected, and in some ways better, which I hadn't. For the first time in years nobody knew who I was.", {"stress": 8}, {"transfer": "worse"})),
  C("Fight it",
    O("I wrote to the governor. I wrote to my lawyer. The list was revised. A different man was moved in my place, and I never felt right about it.", {"stress": 8, "karma": -4}, {"conduct": -2}),
    O("I fought it. It was a long week and a futile one. I went anyway.", {"stress": 10}, {"transfer": "worse"})),
  C("Make the most of the last days",
    O("I said goodbye to everyone. I gave away my books and my radio and a half-written letter. I walked the wing at midnight with my hands behind my back, like a visitor.", {"happiness": 3, "stress": 2}, {"transfer": "better"}),
    O("I spent the days walking the yard. I had a last conversation with a man I'd hardly spoken to in six years. He said, 'I'll miss you.' I was surprised to find I would miss him.", {"happiness": 4}, {"transfer": "better"})),
  cooldown=40)

E("p.sports", "⚽", "The tournament",
  "The chaplain has organised a football tournament, the first in four years. There are eight teams, one from each landing. The warden has decreed that the winner will have an extra hour of rec every day for a month.",
  ["served>=2", "tension<=70"],
  C("Play",
    O("I was a midfielder on a bad team. We lost 6-0 in the first round and had the best time I've had in years. I was kicked in the shin by a murderer. We shook hands afterwards.", {"happiness": 8, "stress": -6, "health": 2}, {"respect": 3, "conduct": 2}),
    O("I played in goal. We reached the final and lost on penalties. I saved two. The other landing carried me round the pitch on their shoulders for a minute anyway.", {"happiness": 9, "stress": -6}, {"respect": 5})),
  C("Referee",
    O("It's a thankless job. I gave eleven yellow cards and one red. The red was to a man who'd done something I'll not describe. Nobody argued.", {"stress": 4, "happiness": 3}, {"respect": 4, "conduct": 2}),
    O("I refereed. Four hundred men watched me make decisions. For two hours, I was the most important man in the building. It's a heady feeling.", {"happiness": 5}, {"respect": 6})),
  C("Bet on it",
    O("A man on the second landing ran the book. I put down three packs on the underdogs. They won. I was owed an enormous amount of tobacco and a very mild threat.", {"happiness": 3}, {"stash": 2, "respect": 2, "heat": 4}),
    O("I bet, and lost. The sum was small, and it was, as such sums are, enormous.", {"stress": 4}, {"dues": 10, "heat": 2})),
  cooldown=20)

E("p.old", "🧓", "Getting old in here",
  "The doctor says the word 'geriatric' in a clinical voice. It's the first time I've heard it used about me. Men my age are going into the infirmary and not coming back. The stairs have become a negotiation.",
  ["age>=58", "served>=8"],
  C("Fight it",
    O("I walked the yard every morning until I couldn't. The doctor said it was good for me. A young man fell in beside me. We never talked about it, but we both knew why.", {"health": 3, "happiness": 2}, {"respect": 2}),
    O("I took up the gym again. The young ones watched, in the way you watch a very old dog trying to run. By the end of the year I was ahead of them on the bench.", {"health": 4, "happiness": 3}, {"respect": 4})),
  C("Accept it",
    O("I moved to the lower bunk. I took up the library's large-print section. I made my peace with the infirmary. It was a good peace.", {"stress": -3}, {}),
    O("I accepted it. I sat in the sun, on the bench by the wall, and watched the young men run. It was a kind of retirement.", {"stress": -3, "happiness": 2}, {})),
  C("Plan for after",
    O("I thought of the world outside, and what I'd do in it, if I ever saw it. The answer was nothing much. Walk. Sit. Ride a bus. It was a surprise to realise it was enough.", {"happiness": 3}, {"parole_mood": 3}),
    O("I wrote to a care home that takes ex-offenders. They said, 'We'll see.' It was the first 'we'll see' that hadn't felt like a no.", {"happiness": 3}, {"parole_mood": 3})),
  cooldown=24)

E("g.warden_clash", "🏛️", "An order I don't like",
  "{sup.first} brings word from the warden's office. All officers are to stop doing something that has kept the wing quiet for six years. It's an ordinary memo, with a signature at the bottom. Everybody who reads it knows it will cause trouble.",
  ["served>=3"],
  C("Follow the order",
    O("I followed it. The wing went wrong in a month. When it did, nobody remembered the memo. I remembered it.", {"stress": 6}, {"merit": 2, "control": -6, "tension": 8}),
    O("I followed it, and said nothing. In October it all went off. The warden said, afterwards, that the memo had been 'misapplied'.", {"stress": 8}, {"merit": 1, "control": -5, "tension": 6})),
  C("Quietly ignore it",
    O("I carried on as before. The wing stayed quiet. I was never caught. It's a sort of professional integrity, I think, to know which orders to break.", {"stress": 6}, {"control": 4, "integrity": -2, "ia_heat": 4}),
    O("I carried on. A colleague reported it. The finding was 'a failure to comply', and a note went on my file.", {"stress": 10}, {"control": 3, "ia_heat": 8, "merit": -3})),
  C("Challenge it",
    O("I wrote a one-page memo of my own, with numbers. The warden read it. He called me in. 'You're right,' he said. 'And you've made enemies.' The order was changed. I had.", {"stress": 8}, {"merit": 4, "standing": -3, "control": 4}),
    O("I challenged it. The reply came back in a week, three lines long. It was to the effect that I could keep my views to myself.", {"stress": 8}, {"merit": -2, "standing": -3})),
  role="guard", roles=SUP, cooldown=14)

E("g.phone_bust", "📱", "A phone on the landing",
  "A phone rings in the walls. It is a small, familiar sound. It has been ringing, every night, for a week. Tonight I follow the ring to cell twenty-two and find a boy of nineteen with the phone at his ear and the face of someone caught in a church.",
  ["served>=1"],
  C("Confiscate it",
    O("I took it. I took the SIM, the battery, the lot. I wrote a clean report. He said 'Please, boss, it's my mum.' I didn't know what to say. I gave him a form for the official phone.", {"stress": 6}, {"merit": 3, "control": 3, "integrity": 2}),
    O("I took it. He cried. I took it anyway. It's the right thing to do and it never feels it.", {"stress": 8, "happiness": -3}, {"merit": 3, "control": 3})),
  C("Let him finish the call",
    O("I turned and faced the wall for two minutes. When I turned back, he'd hung up. I put the phone in my pocket. 'Thank you,' he said. We didn't mention it again.", {"stress": 6, "karma": 3}, {"integrity": -3, "control": -1, "ia_heat": 2}),
    O("I let him finish. The conversation was short. I could hear a woman's voice, high and thin. When he hung up, I took it. 'Thank you,' he said, three times.", {"stress": 6, "karma": 3}, {"integrity": -3})),
  C("Ask where he got it",
    O("He told me. It was a name I knew. It led to a ring, and a search, and a man in an office. It was a good bust. It was also the end of a rare quiet period.", {"stress": 8}, {"merit": 6, "intel": ["corruption", "A phone route through the kitchen"], "tension": 3}),
    O("He told me nothing. I took the phone. A week later someone else's name was in the book.", {"stress": 6}, {"merit": 3})),
  role="guard", cooldown=10)

E("g.medical", "🏥", "A night like any other",
  "At 2.40 an inmate in cell nine says he is in pain. He says it in the voice of a man who says it every night. The nurse is asleep in the infirmary, and the doctor is off site. I have to decide whether this is a night like any other.",
  ["served>=2"],
  C("Call the nurse",
    O("She came in her slippers, took one look at him, and called an ambulance. It was a ruptured appendix. He lived. She said, 'You did the right thing', and went back to bed. I couldn't sleep.", {"stress": 8, "karma": 5}, {"merit": 3, "integrity": 3, "lives_saved": 1}),
    O("I called her. She said it was nothing, and then, on looking, that it was something. The ambulance took forty minutes. He lived. He sent me a card.", {"stress": 8, "karma": 5}, {"merit": 3, "integrity": 3, "lives_saved": 1})),
  C("Check on him later",
    O("I came back in an hour. He was worse. The ambulance took forty minutes, and he did not have forty minutes. An inquest followed.", {"stress": 16, "happiness": -10, "karma": -6}, {"trauma": 12, "ia_heat": 12, "incident": 1}),
    O("I came back in an hour. He was asleep. It was nothing. It's my fate, I think, to be right about the wrong things.", {"stress": 4}, {})),
  C("Sit with him",
    O("I stayed with him for two hours. I talked about nothing. By morning he was better. It was nothing. It's the kind of nothing you do for years.", {"stress": 4, "karma": 3}, {"integrity": 3, "trauma": -2}),
    O("I sat with him. He told me about his mother. By dawn, he was asleep, and I was a different person. I don't know which of us got more out of it.", {"stress": 2, "karma": 4}, {"integrity": 3})),
  role="guard", cooldown=10)

# ====================================================================== FOLLOW-UPS
F("f.p.gang", "🔗", "What the gang remembers", "The gang does not forget. It has been a year since the thing, and the man who runs the landing is waiting for me by the stairs with that mild expression that means he's decided.", [1, 3],
  ["p.protection", "p.gang_order", "p.cards"], ["gang"],
  C("Pay what's owed",
    O("A favour, as promised. I did it without comment. He watched me do it and said nothing at all. It was the nearest thing to a blessing.", {"stress": 6}, {"respect": 4, "rep": {"mine": 10}, "heat": 8}),
    O("I paid it, and it cost more than I'd expected. But he nodded, and the account was closed, and I was one of them in a way I had not been before.", {"stress": 8}, {"respect": 4, "rep": {"mine": 8}, "gang_rank": 1})),
  C("Ask for something instead",
    O("I asked for protection for a friend. It was granted, for a price. I'd never known a transaction like it.", {"stress": 4}, {"respect": 2, "rep": {"mine": -4}, "dues": 10}),
    O("I asked for a transfer to a quieter landing. He considered it. It was granted. The look he gave me afterwards was almost respectful.", {"stress": 4}, {"respect": 0, "tension": 0})),
  C("Walk away",
    O("I walked away. He let me. I was hit twice, quickly, in the stairwell, by men who looked embarrassed. It was settled, in the way these things are.", {"health": -6, "stress": 8}, {"gang": "", "respect": -8, "rep": {"mine": -30}}),
    O("I walked. I walked into three months of avoiding stairwells. In the end, nobody could be bothered.", {"stress": 8}, {"gang": "", "respect": -4, "rep": {"mine": -20}})))

F("f.p.old_debt", "🧾", "The man you owed", "He's out now. I heard on the grapevine that he was waiting at the gate for someone else. The man I once owed is sitting on a bench in the visiting room, with his hat on his knee, wanting a word.", [2, 5],
  ["p.debt", "p.cards"], [],
  C("Clear the air",
    O("I told him I'd been wrong. I told him I was sorry, and that if I'd had it, I'd have paid. He nodded for a long time. 'That's all right,' he said. 'I'd have done the same.' We were square.", {"stress": -6, "happiness": 3}, {"dues": -20, "respect": 3}),
    O("I told him. He said he'd forgotten. I'm not sure I believed him. We shook hands.", {"stress": -4}, {"dues": -10})),
  C("Avoid him",
    O("I avoided him until he left. A year later I heard that he'd died. I should have talked.", {"stress": 3, "happiness": -3}, {}),
    O("I avoided him. It worked for three weeks. In the fourth, he found me in the library. We didn't speak, and it was worse.", {"stress": 6}, {"heat": 2})),
  C("Pay him in full",
    O("I'd saved it for years. I counted it into his hand. He stared at it. 'You didn't have to,' he said. I said I did.", {"stress": -6, "money": -300, "karma": 3}, {"dues": -30, "respect": 4}),
    O("I paid every cent, with interest. It cost me everything I had. I slept well.", {"stress": -6, "money": -400, "karma": 4}, {"dues": -30, "respect": 5})))

F("f.p.young", "💌", "A letter from the kid", "A letter arrives with a stamp I don't recognise. It's from the boy I looked out for. He has a job, a flat and a small fierce handwriting. 'I thought you'd like to know,' he says.", [2, 6],
  ["p.young"], [],
  C("Write back at once",
    O("I wrote four pages. I said how proud I was. I said what I'd learned from him. A reply came in a fortnight, and a photograph. It's on the wall above my bunk.", {"happiness": 8, "stress": -4}, {"support": 6}),
    O("I wrote back the same evening. I didn't know I had that many words in me. We have been in touch ever since.", {"happiness": 8, "stress": -4}, {"support": 6})),
  C("Keep it to yourself",
    O("I put the letter under my pillow and read it every night for a month. I told no one. It was the best news I had.", {"happiness": 6}, {"support": 3}),
    O("I kept it private. A man could do worse than have something nobody else knows about.", {"happiness": 5}, {})),
  C("Ask him for a favour",
    O("I asked him to find my daughter. He did. It took him a year, and he sent me her address and a note: 'She's well.' I couldn't breathe.", {"happiness": 8, "stress": 4}, {"support": 10}),
    O("I asked him to send me books. A box arrived within the month. It had a dictionary, a novel and a pack of biscuits.", {"happiness": 5}, {})))

F("f.p.officer", "🕰️", "The officer retires", "{off.first} is retiring. There's a cake in the staff room and a card on the noticeboard that the inmates are not supposed to sign. A line has formed, quietly, behind the officer's station.", [2, 6],
  ["p.officer_kind", "p.officer_cruel"], [],
  C("Sign the card",
    O("I signed my name. It was a small gesture. He read it, silently, and nodded. 'Take care of yourself,' he said. I've not forgotten.", {"happiness": 4}, {"conduct": 2, "respect": -2}),
    O("I signed it. The man behind me wrote a long message. I read it upside down and couldn't stop smiling.", {"happiness": 4}, {"conduct": 2})),
  C("Say nothing",
    O("I said nothing. He left on a Friday. A new man took his place on Monday. I missed him for a long time.", {"happiness": -3}, {}),
    O("I stood at the back and watched. He didn't look at me. Perhaps that was kindness.", {"happiness": -2}, {})),
  C("Ask him for one last thing",
    O("I asked him for a character reference for the board. He said yes, at once. It was the best letter in my file.", {"happiness": 6}, {"parole_mood": 10, "conduct": 2}),
    O("I asked if he'd say a word for me. He said, 'I already have.' I didn't know what he meant. A year later, I did.", {"happiness": 6}, {"parole_mood": 8})),
  roles=OFF)

F("f.p.child", "🎓", "A graduation", "A photograph comes in an envelope. A young person in a gown and a flat hat, squinting into the sun on a lawn. On the back, in pencil, a single line: 'Thought you should see.'", [3, 8],
  ["p.letter_child", "p.kid_visit"], ["kids"],
  C("Frame it",
    O("I had it framed by the workshop man, out of balsa wood. It's the best thing I own. It hangs where the light falls on it at four in the afternoon.", {"happiness": 10, "stress": -6}, {"support": 8}),
    O("I put it up on the wall. I look at it every day. I've never been prouder, and I've never felt so absent.", {"happiness": 8, "stress": -4}, {"support": 6})),
  C("Write a letter of congratulation",
    O("I wrote the best letter of my life. A reply came back, shorter. It said, 'Thanks, Dad.' I read it a hundred times.", {"happiness": 10, "stress": -4}, {"support": 10}),
    O("I wrote it, but I could not think of an ending. I sent it without one. They wrote back and said it was fine.", {"happiness": 8}, {"support": 8})),
  C("Look away",
    O("I looked at it for a long time, and then put it face-down. It was too much. I took it out again that night.", {"happiness": -2, "stress": 6}, {"support": 0}),
    O("I put it away. I couldn't have it near me. I couldn't have it far.", {"happiness": -3, "stress": 6}, {})))

F("f.p.appeal", "⚖️", "The hearing", "The hearing is set for the fourteenth. It will be in a small, wood-panelled court, with a judge, two lawyers and a clerk. My lawyer calls it 'the best chance you will ever have'. I do not sleep.", [1, 3],
  ["p.dna", "p.recant", "p.lawyer_drops", "p.library"], ["inno", "appeal>=25"],
  C("Prepare with the lawyer",
    O("We met four times. We went through every question the prosecutor might ask. On the day, I answered each one in a steady voice. The judge listened for a long time. The ruling was reserved.", {"stress": 10}, {"appeal": 15, "exonerate": True}),
    O("We prepared for six weeks. On the day, the prosecutor made a mistake with a date. My lawyer pounced. It was over in an hour. The judge said, 'I think we've heard enough.'", {"stress": 8, "happiness": 10}, {"appeal": 30, "exonerate": True}),
    O("We prepared hard. On the day, the court rejected the new evidence as inadmissible. It was a disaster, and I went back to my cell and lay down for a week.", {"stress": 14, "happiness": -10}, {"appeal": -15})),
  C("Speak for myself",
    O("I stood up and spoke, without notes. I spoke for eleven minutes. The room was silent. When I sat down, the judge took off her glasses and cleaned them. The ruling came six weeks later.", {"stress": 12}, {"appeal": 25, "exonerate": True}),
    O("I spoke. It was too long, and too angry, and too true. The judge was patient. The prosecutor smiled. It didn't go my way.", {"stress": 12, "happiness": -6}, {"appeal": -5})),
  C("Don't go",
    O("I asked to be excused. The clerk wrote it down. The lawyer represented me. The hearing took an hour, and I spent it in my cell with a book I did not read.", {"stress": 8}, {"appeal": 10}),
    O("I stayed away. My lawyer said later it was just as well. The ruling was reserved, with a note that the court would consider further submissions.", {"stress": 8}, {"appeal": 12})),
  roles=LAW)

F("f.p.deal", "📋", "The deal's long shadow", "It has been a year since the man in the good coat came. The landing has changed. People stop talking when I come in, and the ones who don't are the ones who've decided.", [1, 4],
  ["p.deal"], [],
  C("Keep your head down",
    O("I kept my head down and my back to a wall. A year of that and the air cleared. It never cleared completely.", {"stress": 8}, {"heat": -4, "respect": -2}),
    O("I did exactly what I'd always done. They saw it, eventually, and they decided it was dull. It's the greatest compliment the place can pay.", {"stress": 6}, {"respect": -1})),
  C("Make a new friend",
    O("I found one, an old man in the library who didn't care. We played chess, and he lost every game and told me who to look out for. I've never been more grateful for a man's indifference.", {"happiness": 4, "stress": -4}, {"respect": 2, "friend": 1}),
    O("I made a friend in the infirmary. A man with no future and a very good memory. He told me everything I needed to know.", {"happiness": 3}, {"friend": 1, "intel": ["rumour", "Who is angriest about the deal"]})),
  C("Make it right",
    O("I found the man I'd named. I told him I was sorry. He looked at me for a very long time. Then he spat. Then he sat down, and talked. It was the strangest conversation of my life.", {"stress": 10, "karma": 8}, {"respect": 4}),
    O("I wrote to him. He didn't reply. But three years later, a message came through a chaplain: 'Tell him it's all right.' I wept.", {"stress": 6, "karma": 8}, {"respect": 2})))

F("f.g.favour", "📞", "The sister calls back", "The phone rings on my night off. A woman's voice, unsteady. She introduces herself as the sister of a man on Block B. She says, 'Thank you for what you did.' Then she says, 'There's something else I need to ask.'", [1, 3],
  ["g.favour", "g.bribe", "g.ring"], [],
  C("Hear her out",
    O("She wanted a letter taken in. A small thing. It was a letter and it said 'we love you'. I took it in. I am more at ease with this than I should be, and I am less at ease than I look.", {"stress": 6, "karma": 3}, {"integrity": -3, "corruption": 1, "ia_heat": 3}),
    O("She wanted me to take a message to her brother. I did. It was kind, and it was wrong, and I did it again the following month.", {"stress": 6}, {"integrity": -4, "corruption": 1, "ia_heat": 4})),
  C("Say no, firmly",
    O("I said no. I said I was sorry. She said, 'I understand.' She hung up. I thought about her all night.", {"stress": 4}, {"integrity": 3}),
    O("I said no. I told her I'd done too much already. She thanked me and wished me well. It was the end of a small story, and I didn't like how it felt.", {"stress": 4}, {"integrity": 4})),
  C("Report the call",
    O("I wrote it up in the morning. The sergeant read it and nodded. 'Good,' he said. The brother was moved. I'm not sure I did the right thing. I'm sure I did the correct thing.", {"stress": 6}, {"integrity": 5, "ia_heat": -4}),
    O("I reported it. The sister was cautioned. The brother was transferred. I never learned how they got on.", {"stress": 6}, {"integrity": 5})),
  role="guard")

F("f.g.video", "🎞️", "The footage", "The footage turns up in a review. It's a landing camera, grainy, from March. You are in the frame for eleven seconds. A man in a suit has it paused on the moment where your arm is raised.", [1, 3],
  ["g.force", "g.extraction"], ["force_bad>=1"],
  C("Explain it",
    O("I explained every second of it. He listened. At the end he said, 'Thank you. I can see that.' It was cleared, in the end, with an advisory note. I kept my job and lost my sleep.", {"stress": 10}, {"ia_heat": -10, "integrity": 2}),
    O("I told him what I'd seen, and what I'd felt, and where I'd gone too far. He wrote it down. The union rep winced. The outcome was a warning.", {"stress": 12, "karma": 3}, {"ia_heat": -8, "integrity": 4, "standing": -2})),
  C("Deny it",
    O("I denied it. I said the footage didn't show what it showed. He played it again. It showed exactly what it showed. I was suspended without pay for a fortnight.", {"stress": 14, "money": -1500}, {"ia_heat": 6, "integrity": -6, "standing": -4}),
    O("I denied it, and the denial became a second charge. The case was closed in my favour, on a technicality, and I have never felt so dirty.", {"stress": 12}, {"ia_heat": 8, "integrity": -6})),
  C("Resign",
    O("I resigned. I couldn't face the process. I was gone within the month. I've never gone back, though I've walked past the gates.", {"stress": 8, "happiness": -8}, {"ia_heat": -10}),
    O("I handed in my keys. A younger man took my place. I got a letter that said 'we regret'.", {"stress": 8, "happiness": -8}, {"ia_heat": -20})),
  role="guard")

F("f.g.romance", "💌", "A letter from outside", "A letter arrives at my home address. No return address. It's from the man who was on my wing and who has now been released. It says only, 'I got out. I wanted you to know that I'm doing well. I'm sorry for what I put you through.'", [2, 6],
  ["g.romance", "g.old_inmate"], [],
  C("Burn it",
    O("I burned it in the sink. It was the right thing to do, and it was the saddest thing I did that year.", {"happiness": -4, "stress": 4}, {"integrity": 2}),
    O("I burned it. I did not tell my partner. The ashes went down the plughole, and I stood there for a long time.", {"happiness": -3, "stress": 4}, {"integrity": 2})),
  C("Keep it",
    O("I kept it in a drawer. I read it twice a year, on the anniversary and on the day of his birthday. It's the only secret I have.", {"happiness": 3, "stress": 2}, {"integrity": -1, "ia_heat": 2}),
    O("I kept it. It was the proof that something good had come out of the building. I couldn't throw it away.", {"happiness": 4}, {"integrity": -1})),
  C("Reply",
    O("I replied with three lines. We exchanged four letters in all. It ended, the way these things do. I'm glad I did it, and I'm glad it ended.", {"happiness": 3, "stress": 4}, {"integrity": -3, "ia_heat": 4}),
    O("I wrote back. It was an odd correspondence, between an ex-officer and an ex-inmate. We understood each other better than I'd imagined.", {"happiness": 4, "stress": 3}, {"integrity": -3, "ia_heat": 3})),
  role="guard")

F("f.g.rookie", "🎖️", "Her promotion", "A note on the noticeboard: the recruit I trained eight years ago has been made up to sergeant. She comes to find me in the car park, a bit self-conscious, with a bottle in a paper bag. 'I wanted to say thanks,' she says.", [3, 8],
  ["g.rookie"], [],
  C("Accept the bottle",
    O("We drank it in the car, in the dark, from paper cups. We talked for an hour about nothing and everything. It's one of the three best nights I've had in the job.", {"happiness": 8, "stress": -6}, {"standing": 4}),
    O("I accepted it, and told her to keep her eyes open. 'Second rule's always the first,' she said. I had no idea she'd remembered.", {"happiness": 8, "stress": -6}, {"standing": 5})),
  C("Tell her to save it",
    O("I told her to keep it for a day she'd need it. She laughed and nodded. I think she has.", {"happiness": 4}, {"standing": 2}),
    O("I said, 'Keep it. You'll want it more than I do.' She looked at me, and then at the bottle. 'You're right,' she said.", {"happiness": 3}, {"standing": 2})),
  C("Pass on a warning",
    O("I told her the thing I wish I'd been told: that it gets easier, and that is the problem. She was quiet for a while. 'I know,' she said.", {"happiness": 3, "stress": 2}, {"standing": 3}),
    O("I told her about the cost. I told her what it takes out of you. She listened with her whole face.", {"happiness": 3, "stress": 2}, {"standing": 3})),
  role="guard")

F("f.g.family", "📜", "The letter from the family", "A letter arrives at the staff office, forwarded unopened. It's from the family of the man in cell nineteen. It's two pages. It's handwritten. It begins, 'Dear Officer, we wanted to thank you.'", [1, 4],
  ["g.first_death", "g.suicide_watch", "g.medical"], [],
  C("Read it and keep it",
    O("I read it three times. I've kept it in the lining of my wallet for years. It's the best thing anyone's written to me.", {"happiness": 6, "stress": -6}, {"trauma": -8}),
    O("I read it. I read it to my wife. She cried. I did not, which is itself a kind of fact about me.", {"happiness": 5, "stress": -4}, {"trauma": -6})),
  C("Write back",
    O("I wrote a letter that took me a week. I said what I could. A reply came, shorter. It said, 'Thank you for writing.' I've never been as relieved.", {"happiness": 4, "stress": -4}, {"trauma": -6, "integrity": 2}),
    O("I wrote back. It was a short note. I didn't know what to say. I said what I thought, which was that I was sorry.", {"happiness": 3, "stress": -3}, {"trauma": -4})),
  C("Put it away",
    O("I couldn't face it. I put it in a drawer. In a year I would read it. In ten I would cry.", {"stress": 4}, {"trauma": 2}),
    O("I put it away. There are things you can't carry on a shift.", {"stress": 4}, {"trauma": 2})),
  role="guard")

F("f.g.tip", "🔎", "The tip pays off", "The man who gave me the tip last year has found me on the landing again. He doesn't look happy. 'You owe me,' he says quietly, as though noting the weather.", [1, 3],
  ["g.informant", "g.drone"], [],
  C("Pay in kind",
    O("I did him a small favour: a call to his mother. It didn't seem like much. In his world it was a diamond.", {"stress": 4}, {"integrity": -2, "ia_heat": 2}),
    O("I got him a transfer to a quieter wing. He thanked me with a nod. I felt the new weight on my back, the weight of a debt that wouldn't be repaid.", {"stress": 6}, {"integrity": -3, "ia_heat": 3})),
  C("Pay in protection",
    O("I put him on the list for protective custody. It took a form and a signature. It saved his life, I think. I'll never know.", {"stress": 4, "karma": 4}, {"integrity": 3}),
    O("I kept an eye on him for a year. He had a hard time. He never asked for anything again.", {"stress": 6, "karma": 4}, {"integrity": 3})),
  C("Remind him who's who",
    O("I told him I owed him nothing. It was true. It was also cruel. He nodded. He never spoke to me again.", {"stress": 6, "karma": -3}, {"control": 2, "integrity": -1}),
    O("I told him I'd done my job and he'd done his. He left. A week later he was found with a broken jaw. I'll never know whether that was my fault.", {"stress": 12, "karma": -6}, {"trauma": 8, "control": 0})),
  role="guard")

# ====================================================================== THE ARCS
A("prisoner", 1, "🚪", "Fresh fish",
  "A year. It's a small, hard number. You've learned the count, the queue, the rules about where to put your eyes. You've seen what a man can be broken by and what he can bear. In the yard one evening, an old hand nods at you in a way that means something has changed.",
  C("Nod back",
    O("I nodded. It was the smallest thing. But a landing is made of such things, and from that night on, a few people did not look through me.", {"happiness": 4, "stress": -2}, {"respect": 6}),
    O("I nodded back. It was a signal and I'd answered it. I've learned a language I can't write down.", {"happiness": 4}, {"respect": 5})),
  C("Keep walking",
    O("I kept walking. It's a decision, to stay unseen. For another year I was an empty uniform. It's safe. It's very lonely.", {"stress": 2}, {"respect": 0, "heat": -4}),
    O("I walked on. I was learning that the best way to survive is to leave no mark. It was working.", {"stress": 2}, {"heat": -3})),
  C("Ask what it means",
    O("He laughed. 'It means you're still here,' he said. It was the first thing anyone had told me that day that I believed.", {"happiness": 5}, {"respect": 4, "friend": 1}),
    O("He looked at me for a while. 'It means keep going,' he said. And I did.", {"happiness": 4}, {"respect": 4})))

A("prisoner", 2, "🛡️", "Whose side?",
  "Nobody gets through this place alone. By now you've picked, or been picked, or learned how to be nobody's. A man at the gym says something about it as if it were nothing: 'You can only stand in one place at a time.'",
  C("Stand with the ones who took you in",
    O("I stood with them. It's easy to look down on belonging, until you need it. It cost me what it cost. It gave me something to stand on.", {"happiness": 4, "stress": -4}, {"respect": 5, "rep": {"mine": 8}}),
    O("I stood where I'd been put. A gang is a family you can't leave and don't pick. But it's a family.", {"happiness": 3}, {"respect": 4, "rep": {"mine": 6}})),
  C("Stand alone",
    O("I stood alone. It's a hard way. But there's a respect in it, among the old hands, for a man who asks nothing. I kept my back to the wall for years.", {"stress": 4}, {"respect": 6, "heat": -2}),
    O("I stood alone. It was cold. But I had my own rules, and I knew them by heart, and no one else's name was on me.", {"stress": 4}, {"respect": 5})),
  C("Stand wherever's safest",
    O("I stood where the wind wasn't. It's cowardice and it's wisdom, and in this place they look the same. I was never hurt.", {"stress": -2}, {"respect": -2, "heat": -4}),
    O("I played every side. It's an art. It cost me every friend I had, and kept me alive.", {"stress": 2}, {"respect": 0, "heat": -2})))

A("prisoner", 3, "🌱", "Something to hope for",
  "It isn't a plan, exactly. It's the thing you do when the days have no shape: a course, a project, a letter, a scheme. You have found something, and it is yours, and you've begun to lean on it. An officer notices.",
  C("Share it",
    O("I told the officer. He didn't laugh. He said, 'Good', and wrote down a name for me to ask. A door opened that I hadn't known was a door.", {"happiness": 6, "stress": -4}, {"conduct": 4, "parole_mood": 4}),
    O("I told a friend, and he told another, and soon the whole landing knew. It became, in some small way, ours.", {"happiness": 6}, {"respect": 4})),
  C("Guard it",
    O("I kept it secret. It was mine. I took it out only in the dark and turned it over and over. It kept me alive.", {"happiness": 4, "stress": -4}, {}),
    O("I guarded it like a coal. A man who has nothing else needs one thing to be his. This was mine.", {"happiness": 4}, {})),
  C("Make it bigger",
    O("I took it as far as it would go. I wrote the letter, signed the form, joined the course. When the news came, I was a little less afraid.", {"happiness": 8, "stress": -2}, {"conduct": 4, "appeal": 4, "parole_mood": 4}),
    O("I went all in. I told myself that hope was a discipline, and I practised it. It nearly broke me, and it saved me.", {"happiness": 6, "stress": 2}, {"conduct": 4, "parole_mood": 4})))

A("prisoner", 4, "🧱", "The test of the walls",
  "It happens in an instant: the noise, the hands, the dark. When you come to, someone is kneeling next to you. 'You're all right,' he says. 'Stay down.' You are lying on the floor of the building. You are alive. It has tested you, and you have, for now, passed.",
  C("Get up",
    O("I got up. I've got up since. It's the only thing the walls can't take, in the end.", {"happiness": 3, "stress": 6}, {"respect": 6}),
    O("I got up, shaking. The man who'd knelt next to me nodded. 'That's all it takes,' he said.", {"happiness": 3, "stress": 6}, {"respect": 5})),
  C("Stay down a while",
    O("I stayed down. I breathed. The floor was cold, and the ceiling was a long way up, and I understood that I was lucky.", {"stress": -2, "happiness": 2}, {}),
    O("I lay there for twenty minutes. Nobody moved me. I think the ones around me knew what I was doing: I was learning to be alive again.", {"stress": -3, "happiness": 2}, {})),
  C("Remember it",
    O("I wrote it down that night. I wrote every detail. I read it aloud, once, to a man on the landing. He said, 'You were lucky.' I said I knew.", {"stress": 2, "smarts": 1}, {"parole_mood": 2}),
    O("I memorised it. I knew I'd need to tell it again, to a board, to a judge, to a child.", {"stress": 2}, {"parole_mood": 2})))

A("prisoner", 5, "🚪", "The door",
  "There comes a day when the door seems nearer than the wall. It isn't a thing you can describe. It's a smell, a sound, the angle of the light on the landing. Something is about to change, one way or another. You can feel it in the building and in your own chest.",
  C("Walk toward it, carefully",
    O("I took every step as if it were glass. I kept my head down and my record clean. The nearer the door, the slower I went.", {"stress": 4, "happiness": 4}, {"conduct": 4, "parole_mood": 4}),
    O("I walked toward it like a man crossing a frozen lake. Everyone does. The ones who run are the ones who fall.", {"stress": 4, "happiness": 3}, {"conduct": 3, "parole_mood": 4})),
  C("Run at it",
    O("I could not wait. I did something rash, on a Tuesday. It cost me a year, but I'd have done it a hundred times.", {"stress": 10, "happiness": 2}, {"heat": 14, "conduct": -6}),
    O("I took the risk. It was a mistake. It was also the only thing I've done in this place that felt like mine.", {"stress": 10}, {"heat": 12, "conduct": -6})),
  C("Don't look at it",
    O("I didn't look. It's a technique. I did the days. I did the weeks. I did the years. When the door opened, I wasn't looking.", {"stress": -2}, {}),
    O("I kept my eyes on the floor. A friend told me, much later, that this is how most men do it.", {"stress": -2}, {})))

A("guard", 1, "🔑", "Probation",
  "A year. The probationary period ends with a signature and a handshake, in an office with a view of the car park. The deputy says, 'You'll do.' It's all the ceremony the job allows. He hands you a new, heavier ring of keys.",
  C("Accept the keys",
    O("I took them. They were heavier than I'd expected, in a way that had nothing to do with weight.", {"happiness": 5, "stress": 2}, {"merit": 3, "control": 3}),
    O("I took them. A small, cold thing, and a great deal of trust. I put them on my belt and felt the building take notice.", {"happiness": 5}, {"merit": 3, "control": 3})),
  C("Ask what the keys are for",
    O("He laughed. 'Everything,' he said. 'Nothing. It's whatever you decide.' It's the truest thing anyone has said to me about the job.", {"happiness": 4}, {"merit": 2, "integrity": 3}),
    O("He told me. He told me the cells, the stores, the gates. He didn't say what they open in a person.", {"happiness": 3}, {"merit": 2})),
  C("Hesitate",
    O("I hesitated. It was a moment, no more. He saw it. 'Good,' he said. 'Keep that.' I've kept it.", {"happiness": 2, "stress": 2}, {"integrity": 4, "merit": 1}),
    O("I took a breath before I took them. The deputy nodded. 'I wouldn't trust anyone who didn't,' he said.", {"happiness": 3}, {"integrity": 4})))

A("guard", 2, "🚨", "The first incident",
  "You've been on the wing long enough to know that nothing is routine. This is the day it stops being theory. A man is down, or a door is jammed, or a voice is shouting your name. Everything you've been taught arrives in your hands.",
  C("Do exactly as trained",
    O("I did every step. It worked. Afterwards I filled in the forms with a hand that wouldn't stay still. It was the first time I truly understood what the training was for.", {"stress": 10}, {"merit": 4, "control": 4}),
    O("I followed the procedure. It's strange how a procedure can hold you up, like a rail.", {"stress": 10}, {"merit": 4, "control": 3})),
  C("Improvise",
    O("I did what seemed right, and it worked, and I told no one how close it had been. I was commended for it. I've never been sure I deserved it.", {"stress": 12}, {"merit": 5, "control": 4, "commend": 1}),
    O("I improvised, and the thing I'd done wasn't in the book. It turned out to be exactly right. I've been trying to explain it ever since.", {"stress": 12}, {"merit": 5, "control": 4})),
  C("Freeze",
    O("I froze. For two seconds. It felt like two hours. A colleague pushed past me and did what I should have. We never spoke of it. It's the worst thing I've done, and the most useful.", {"stress": 14, "happiness": -6}, {"trauma": 8, "merit": -2}),
    O("I froze. The incident ended without me. I've been afraid ever since, of the next time, and I'm better for it.", {"stress": 14, "happiness": -4}, {"trauma": 6})))

A("guard", 3, "⚖️", "What kind of officer",
  "At some point, the building decides what you are. It does it without telling you. It notices what you do with the small decisions, the unrecorded ones. A colleague says it quietly, one night, over bad tea: 'You've got a reputation now.'",
  C("Ask what it is",
    O("He told me. It was both better and worse than I thought. Half the wing thought I was fair, and half thought I was soft. I could live with both.", {"stress": 4}, {"integrity": 2, "standing": 2}),
    O("He told me. It was different from what I'd hoped. But it was true, and truth is a kind of gift.", {"stress": 4}, {"integrity": 2})),
  C("Live up to it",
    O("I leaned into it. I became, over time, what they said. It's a strange thing, to be shaped by a rumour.", {"stress": 2}, {"control": 4, "standing": 3}),
    O("I played the part. It was an easy one, and over time it became me.", {"stress": 2}, {"control": 3, "standing": 3})),
  C("Change it",
    O("I set out to be someone else. It took two years. I'm not sure I managed. But the effort did something to me, and not all of it bad.", {"stress": 6}, {"integrity": 4, "standing": -2}),
    O("I tried to change. The wing was suspicious. But eventually a few of them came round, and a few more didn't, and I stopped counting.", {"stress": 6}, {"integrity": 3})))

A("guard", 4, "🎖️", "Stripes",
  "The stripes arrive on a Tuesday. A sergeant now: forty officers on the roster, two hundred inmates on the landing and a radio that never leaves your ear. The deputy shakes your hand. 'Now it gets hard,' he says.",
  C("Lead from the front",
    O("I walked every landing in the first week, every shift. By the end of the month, I knew every name. They knew mine. A building is a lot easier to command when it's looking at you.", {"happiness": 5, "stress": 4}, {"control": 6, "merit": 4, "standing": 3}),
    O("I led from the front. It exhausted me. But the officers followed.", {"happiness": 4, "stress": 5}, {"control": 5, "merit": 4})),
  C("Lead from the office",
    O("I ran it from the control room. It was efficient. It was also remote, and in a year I'd lost touch with the wing. I regret that.", {"stress": 2}, {"control": -2, "merit": 3}),
    O("I delegated. It worked in the short term. In the long term I became a name on a door.", {"stress": 2}, {"control": -3, "merit": 3})),
  C("Lead by asking",
    O("I asked the officers what they needed. They looked at me as if I'd grown another head. But they told me. And I listened.", {"happiness": 5}, {"standing": 5, "union": 4, "merit": 3}),
    O("I asked, and I was told. It wasn't what I expected. It made me a better sergeant than I would otherwise have been.", {"happiness": 5}, {"standing": 4, "union": 4})))

A("guard", 5, "🕰️", "The long shift",
  "You have been here a very long time. The recruits are younger than your children. The building has changed its paint twice, its policy three times and its name once. You walk the landing at night and find you know it better than you know your house.",
  C("Stay to the end",
    O("I stayed. I did my time on the other side of the door. When it was over, I understood something about the men I'd watched: that it's the same time.", {"stress": 2, "happiness": 3}, {"merit": 2}),
    O("I stayed to the end. It was the only decision I could imagine. It was, I think, the right one.", {"stress": 2, "happiness": 3}, {"merit": 2})),
  C("Get out while you can",
    O("I put in my papers. It was a surprise to everyone, including me. The first morning I woke at 5.40 and lay there, listening for the keys.", {"stress": -4, "happiness": 3}, {"burnout": -10}),
    O("I left. The building did not notice. It went on without me, as it will, as it always did.", {"stress": -3, "happiness": 2}, {"burnout": -8})),
  C("Pass it on",
    O("I took a young officer under my wing and taught her everything I knew. When I finally left, she was ready.", {"happiness": 6, "stress": -2}, {"standing": 4, "merit": 2}),
    O("I wrote it all down in a notebook and gave it to a recruit. Years later she wrote to say she still had it.", {"happiness": 6}, {"standing": 4, "merit": 2})))

import prison_lib

# ====================================================================== more echoes
import prison_lib as _pl
F("f.p.after_the_strike", "📣", "What came of it", "Months after the hunger strike, the landing smells different. There are new vegetables in the kitchen, the roof has been patched, and a man in a good coat has been seen talking to the chaplain. Nobody mentions the strike, and everybody is thinking about it.", [1, 3],
  ["p.hunger", "p.heatwave", "p.sports"], [],
  C("Press the advantage",
    O("I wrote up a list of the next three things that needed fixing. I gave it to the chaplain. He gave it to the man in the coat. The roof was done in the spring. The showers took another year.", {"stress": 4, "karma": 3}, {"respect": 4, "budget": 4, "order": 2}),
    O("I organised a petition. A hundred and sixty names. It was received without comment. A month later, there was a new rota for the laundry.", {"stress": 4}, {"respect": 4, "budget": 3})),
  C("Let it settle",
    O("I let it be. Some victories are best left unpressed. The building held its breath, and nothing broke.", {"stress": -2}, {"tension": -4}),
    O("I kept my head down. It was a good year. They don't come often.", {"stress": -3, "happiness": 2}, {"tension": -4})),
  C("Take the credit",
    O("I let it be known that I had been at the heart of it. It was a lie. It got me a seat at a good table and a visit from a man I would rather not have met.", {"stress": 6}, {"respect": 6, "heat": 8}),
    O("I let people think I was behind it. For a month I was somebody. Then someone who actually was walked into the mess hall, and the silence taught me a lesson.", {"stress": 6, "happiness": -3}, {"respect": -4, "heat": 4})))

F("f.p.newfish", "🐟", "The new arrivals", "A new bus. Eleven of them, stumbling off in the grey light with their plastic bags. They're staring at the building as I stared at it. This time I'm the one at the window, with a mug of tea, watching.", [3, 7],
  ["p.first_night", "p.test", "p.chow", "p.shower"], ["served>=3"],
  C("Watch over one of them",
    O("There was a lad, about nineteen, who held his bag in front of him like a shield. I stood next to him in the queue. Nobody touched him. At the end of the month he said, 'Why'd you do that?' I said I didn't know.", {"happiness": 4, "karma": 4}, {"respect": 3, "friend": 1}),
    O("I looked after a quiet man with spectacles. He turned out to be a lawyer. He told me, within a month, three things about my case that nobody else had.", {"happiness": 4, "karma": 3}, {"respect": 2, "appeal": 4, "friend": 1})),
  C("Test them",
    O("I stood in the corridor and asked for a light. I was the one doing it now. A young man gave me a perfect answer. I let him through, and felt both proud and sick.", {"stress": 4, "karma": -3}, {"respect": 4}),
    O("I tested the newest. He cracked. I'm not proud of that. I've never forgotten his face.", {"stress": 6, "karma": -6}, {"respect": 6, "heat": 6})),
  C("Look away",
    O("I looked away. It's what the building does to you. I told myself it was nothing to do with me.", {"stress": 2}, {}),
    O("I looked away. The first few weeks are the worst, and I've no stomach left for them.", {"stress": 2}, {})))

F("f.p.plan_night", "🌙", "The date is set", "It's been decided: the first Saturday after the lockdown lifts. The crew know. The man on the inside knows. In the small hours, in the dark, with the pipes ticking, you realise that there are now four people who could undo you.", [1, 2],
  ["p.crew_wavers", "p.insider_wants", "p.plan_rumour"], ["escape>=3"],
  C("Go early",
    O("I moved it forward by a week. Nobody was ready. It put us ahead of whoever might have talked. I'm not sure it was wise. It was necessary.", {"stress": 12}, {"escape": 1, "heat": 4}),
    O("I told them it was this Thursday. They looked at me, appalled. But they came. It was the best decision I've made, or the worst.", {"stress": 12}, {"escape": 1, "heat": 6})),
  C("Postpone",
    O("I called it off. The crew grumbled. Two of them thought I'd lost my nerve. A month later, one of them was caught with a length of cable. I'd been right.", {"stress": 6}, {"escape": -1, "heat": -4}),
    O("I postponed it by a month. The feeling in my stomach didn't leave. But it didn't get worse.", {"stress": 6}, {"escape": 0})),
  C("Test the inside man once more",
    O("I tested him with a false date. Nothing happened on the night, no extra officers, no search. He was clean. I felt something in me settle.", {"stress": 6}, {"escape": 1, "intel": ["weakness", "The inside man held a false date"]}),
    O("I tested him. He passed. I almost wished he hadn't.", {"stress": 6}, {"escape": 0})))

F("f.g.speaking_up", "🔔", "What it cost", "A year after you spoke up, the building has settled around the fact of it. There are people who won't sit near you in the canteen and a few who will. There is a letter on the noticeboard about a new complaints procedure, and your name is nowhere on it.", [1, 3],
  ["g.warden_clash", "g.inspection", "g.budget", "g.ring"], [],
  C("Keep your head down",
    O("I kept it down for a year. By the end of it the building had other things to be angry about. It's amazing how quickly the anger moves on.", {"stress": -2}, {"standing": 2}),
    O("I kept quiet. A younger officer thanked me, quietly, in the corridor. That was enough.", {"stress": -2, "happiness": 2}, {"standing": 2})),
  C("Run for the union committee",
    O("I put my name down. It surprised everyone, including me. I was elected by eleven votes. The first meeting was a tremendous argument, and I enjoyed it.", {"happiness": 4}, {"union": 12, "standing": 3}),
    O("I ran. I didn't win. But I got two hundred votes, which was a good deal more than I'd expected.", {"happiness": 3}, {"union": 6, "standing": 2})),
  C("Look for a way out",
    O("I applied for a transfer to a training post. It was granted. I spent two years teaching recruits and never regretted a day of it.", {"stress": -6, "happiness": 4}, {"trauma": -6, "control": -10}),
    O("I looked. There was a vacancy in another region. I didn't take it. But knowing I could made the difference.", {"stress": -3}, {"trauma": -3})),
  role="guard")

F("f.g.war_after", "🏳️", "The peace", "It has been quiet on the landing for weeks. A kind of quiet that isn't peace, exactly. A man whom I once wrote up has stopped me in the corridor. 'I wanted to say,' he says, 'you were fair.'", [1, 3],
  ["gg.war", "g.force", "g.extraction"], [],
  C("Thank him",
    O("I said thank you. It was the only thing to say. We shook hands, which is against the rules. Neither of us mentioned it.", {"happiness": 4}, {"control": 3, "integrity": 2}),
    O("I thanked him. He walked on. I stood there for a minute, in the middle of the landing, with a lump in my throat.", {"happiness": 4}, {"control": 3, "integrity": 2})),
  C("Stay professional",
    O("I nodded, and said 'carry on'. He nodded, and carried on. We were two professionals, and it was a strange thing to be.", {"stress": 2}, {"control": 2}),
    O("I said, 'Back to your cell.' He went. I felt like a clerk, and then I felt like a human, and then I went on with the shift.", {"stress": 2}, {"control": 2})),
  C("Ask him why",
    O("He said, 'You never lied to me.' I thought about it all night. I couldn't remember the last time I'd told a lie to an inmate, and I was suddenly very proud of that.", {"happiness": 5}, {"integrity": 4, "control": 3}),
    O("He said, 'You looked at me when you spoke.' It's the simplest thing in the world, and I made a note.", {"happiness": 4}, {"integrity": 3, "control": 3})),
  role="guard")
