from prison_lib import *

# ====================================================================== the inmate economy and the small things (v0.21)

E("p.commissary_day", "🛒", "Commissary day",
  "The list goes round on Thursday. Noodles, stamps, a bar of soap that doesn't smell of the laundry, a pen that works. You have exactly enough for half of what you need.",
  ["served>=1"],
  C("Spend it on food",
    O("Noodles and peanut butter. Two weeks of dinners that taste of something. The wing noticed and I was never short of company at the hot tap.", {"health": 2, "happiness": 2}, {"respect": 1}),
    O("I bought a week of proper calories and lived on tea for the other. Worth it.", {"health": 1, "stress": 2}, {"conduct": 0})),
  C("Buy stamps and write letters",
    O("Six stamps and a good pen. By the end of the month I had answers from three people, and one of them was a surprise.", {"happiness": 4, "stress": -2}, {"support": 6}),
    O("I wrote to everyone. Most never replied. One did, and it made up for the rest.", {"happiness": 3}, {"support": 4})),
  C("Save it for the debt",
    O("A third of what I owed, in an envelope, and a nod from the man who collects. It bought me quiet.", {"stress": -2}, {"dues": -12, "heat": -2}),
    O("I paid down what I could. The balance sat on my chest for weeks, but it was lighter.", {"stress": 1}, {"dues": -8})),
  cooldown=8)

E("p.trustee", "🔑", "Trusted with a key",
  "The senior officer on the landing has a proposal: a trustee post. You'd carry keys to the wing's laundry and stockroom, and you'd answer to her. Men in this building don't like who they see with keys.",
  ["conduct>=45", "served>=3", "job"],
  C("Take the post",
    O("The keys were heavy and so was the look from the yard. After a year, the officer trusted me with the rota. After two, I was the one who knew where everything was.", {"stress": 5, "happiness": 2}, {"conduct": 8, "respect": -4, "heat": -3}),
    O("It saved me a good many hours in the cell. It cost me the man in the next block, who never spoke to me again.", {"stress": 4}, {"conduct": 6, "respect": -6})),
  C("Decline politely",
    O("She nodded. 'That's allowed.' I kept my place and my friends.", {"stress": 1}, {"respect": 2}),
    O("I said no and meant it. A man in the corridor gave me a look I'd earned.", {"stress": 2}, {"respect": 3})),
  C("Ask for something in return",
    O("An extra phone call a week. She said she'd think about it, and, to my surprise, she did.", {"happiness": 2}, {"support": 4, "conduct": 4}),
    O("She laughed. 'You're learning.' She didn't say no.", {"stress": 1}, {"conduct": 2})),
  cooldown=40, once=True)

E("p.library_cart", "📚", "The library cart",
  "The library cart comes round on Tuesdays with a trolley and a woman from the education department. There are forty books, three of them yours by right of having asked.",
  ["served>=1"],
  C("Take something heavy",
    O("A thick history I'd never have read outside. It took the winter. I came out of it with opinions.", {"smarts": 3, "stress": -3}, {"conduct": 1}),
    O("A novel with a sad ending, the best sort. I read it twice.", {"smarts": 1, "happiness": 3, "stress": -3}, {})),
  C("Ask for law books",
    O("She raised an eyebrow and returned the following week with two. I sat up late with a highlighter.", {"smarts": 2, "stress": 2}, {"appeal": 4, "conduct": 1}),
    O("They were out of date. I used them anyway, and learned a great deal about what the law used to say.", {"smarts": 2}, {"appeal": 2})),
  C("Pass the time with a pack of cards",
    O("A game of rummy ran through the spring. I lost a great deal of cigarettes and made two friends.", {"happiness": 3}, {"dues": 4, "respect": 1}),
    O("I won more than I lost, and learned never to play the man in the corner.", {"happiness": 2}, {"respect": 2, "heat": 1})),
  cooldown=10)

E("p.visit_day", "🪑", "Visiting day",
  "The tables are bolted down and the vending machine takes only coins you can't carry through. A name is called. You wash your face for no reason and go through the door.",
  ["served>=1", "support>=25"],
  C("Give the hour entirely to them",
    O("We talked about nothing. The kind of nothing that is the only real thing. When the bell went I held on a second too long.", {"happiness": 8, "stress": -6}, {"support": 6}),
    O("My visitor cried and I held it together. It cost more than it looked.", {"happiness": 4, "stress": 3}, {"support": 8})),
  C("Ask for what you need",
    O("Money for the phone account, a coat, a number to ring. All of it was agreed in the first ten minutes. After that we could just be.", {"happiness": 3}, {"support": 3}),
    O("I asked, and I could see them doing the sum. I felt cheap afterwards.", {"happiness": -2, "stress": 3}, {"support": 2})),
  C("Pretend everything is fine",
    O("I told them it was easy. They knew I was lying. We both played along.", {"happiness": 1, "stress": 3}, {"support": 4}),
    O("It worked. I walked back to the wing feeling like I'd acted in a play.", {"stress": 4}, {"support": 3})),
  cooldown=6)

E("p.letter_bad", "✉️", "The letter",
  "The envelope is thin. You know what that means before you open it. A paragraph, a signature and a decision someone else has made.",
  ["served>=2", "partner"],
  C("Read it twice, then put it away",
    O("I put it under the mattress, and for three days I was nobody's anything. Then I wrote back, kindly.", {"happiness": -10, "stress": 6}, {"support": -8}),
    O("I read it until the words stopped meaning anything. Then I went to work.", {"happiness": -8, "stress": 4}, {"support": -6})),
  C("Ask for a call",
    O("They accepted. It was short and honest and the kindest thing we ever did for each other.", {"happiness": -4, "stress": 3}, {"support": 2}),
    O("They declined. I understood. It still stung.", {"happiness": -8, "stress": 5}, {"support": -4})),
  C("Throw yourself into something",
    O("I took on the gym, the class and the extra shifts. By the end of the winter I was in the best shape of my life, and there was nobody to tell.", {"health": 3, "stress": 4, "happiness": -3}, {"conduct": 4}),
    O("I filled the days. It worked until the lights were out.", {"stress": 6, "happiness": -4}, {"conduct": 2})),
  cooldown=40, once=True)

E("p.gym_rival", "🏋️", "The man at the bench",
  "He's been there every day for a month. He doesn't speak. He re-racks your weights in a way that is either politeness or a message.",
  ["served>=1", "respect<=65"],
  C("Introduce yourself",
    O("We spotted each other for a year. He turned out to be a plumber from the north who read thrillers. We never said what he was in for.", {"happiness": 3, "health": 2}, {"respect": 3}),
    O("A grunt, then a name. Within a month he'd become the closest thing I had to a friend.", {"happiness": 3}, {"respect": 2})),
  C("Challenge him",
    O("A lift-off. I lost. He didn't gloat. By the end of the week, half the wing had stopped to watch.", {"stress": 2, "health": 1}, {"respect": 4, "heat": 2}),
    O("It turned into an argument. An officer ended it. We both lost privileges.", {"stress": 5}, {"conduct": -4, "respect": -2})),
  C("Move to a different time",
    O("I changed my routine. Nothing happened. That was the point.", {"stress": 1}, {"heat": -2}),
    O("I started going at dawn. It was quieter, and I liked the light.", {"happiness": 2, "stress": -2}, {})),
  cooldown=15)

E("p.cell_search", "🔦", "Spin the cell",
  "It happens at dawn. A torch in the eyes, a voice that does not say please, and your belongings in a heap on the landing. They are looking for something, and they say they know where.",
  ["stash"],
  C("Stay silent and still",
    O("They found nothing, because there was nothing to find. I put my things back in the order they'd been in and slept badly.", {"stress": 4}, {"heat": -2}),
    O("They found the edge of it. A warning, and a mark against me. It could have been worse.", {"stress": 6}, {"conduct": -4, "heat": 4, "stash": -1})),
  C("Protest the search",
    O("The officer wrote my name down, slowly, in the way officers do.", {"stress": 6}, {"conduct": -5, "heat": 5}),
    O("A supervisor came, listened and shrugged. The search finished. The mood did not.", {"stress": 5}, {"conduct": -2})),
  C("Offer to help them look",
    O("The officer stopped. 'Don't be clever.' A pause. They moved on. I'd overplayed it and survived.", {"stress": 5}, {"heat": 2, "respect": 1}),
    O("They took it as an insult. I spent a week in the segregation unit thinking about my choices.", {"stress": 8}, {"conduct": -8, "heat": 6})),
  cooldown=12)

E("p.anniversary", "🕯️", "The anniversary",
  "It is the date. The one that follows you around the calendar whatever else you do. The wing knows better than to ask what it is.",
  ["served>=3"],
  C("Mark it quietly",
    O("A candle I wasn't allowed. I lit the sunlight instead, by the window at three. It was enough.", {"happiness": -4, "stress": -2}, {"conduct": 1}),
    O("I wrote it down and then I tore it up. It was the first time I'd put it on paper.", {"happiness": -3, "stress": -3}, {})),
  C("Talk to the chaplain",
    O("He said very little, and all of it right. I left feeling like I'd put something down.", {"happiness": 2, "stress": -6}, {"conduct": 3}),
    O("I sat with the chaplain for an hour and said nothing. He didn't mind.", {"stress": -4}, {"conduct": 2})),
  C("Pick a fight with the day",
    O("I trained until I couldn't stand. Nobody asked why.", {"health": 1, "stress": 3}, {"respect": 1}),
    O("I lost my temper over a thing that didn't matter. It cost me a week of privileges.", {"stress": 6, "happiness": -3}, {"conduct": -5, "heat": 4})),
  cooldown=20)

E("p.guard_kindness", "🍬", "A small kindness",
  "A young officer you barely know slides a sweet through the hatch on the night your sentence is read aloud on the telly. He says nothing. He shuts the hatch.",
  ["served>=1"],
  C("Say thank you in the morning",
    O("He said 'Don't mention it.' He didn't mean 'don't thank me'. He meant 'don't tell anyone'.", {"happiness": 3}, {"conduct": 2, "respect": -1}),
    O("A nod and a word. For the rest of my time there, he was the officer who looked at me like a person.", {"happiness": 4}, {"conduct": 3, "respect": -1})),
  C("Keep it to yourself",
    O("I told nobody. It stayed small, which is what made it big.", {"happiness": 3}, {}),
    O("I kept the wrapper. It's in my book now.", {"happiness": 3}, {})),
  C("Wonder what he wanted",
    O("I never found out. Years later I decided he hadn't wanted anything. That was harder to believe.", {"stress": 3}, {"heat": 0}),
    O("The next week he asked me a favour. A small one. I did it. I'm still not sure who won.", {"stress": 4}, {"conduct": 1, "heat": 3})),
  cooldown=40, once=True)

E("p.reentry_plan", "🧰", "The plan for the outside",
  "The case worker has a form headed 'Release planning'. It has a box for 'accommodation', a box for 'employment' and a box for 'support'. All three are empty.",
  ["served>=4", "conduct>=35"],
  C("Fill in all three, properly",
    O("A cousin's spare room, a letter from the workshop foreman, a name for support. It took a month and a lot of phone calls. It was the best month of my sentence.", {"stress": 3, "happiness": 3}, {"conduct": 5, "support": 4, "parole_mood": 6}),
    O("I filled in two and left the third honest. The board's report called me 'realistic'.", {"stress": 2}, {"conduct": 3, "parole_mood": 4})),
  C("Leave it for later",
    O("Later became the week of the hearing. I filled it in on the back of a leaflet.", {"stress": 5}, {"conduct": -1, "parole_mood": -4}),
    O("I put it off. The case worker reminded me twice and then stopped reminding me.", {"stress": 3}, {"parole_mood": -3})),
  C("Ask the chaplain to help",
    O("He knew a hostel and a baker. They didn't ask what I'd done. They asked if I was punctual.", {"happiness": 3}, {"conduct": 3, "support": 3, "parole_mood": 5}),
    O("He made three calls from his own phone. Two came to nothing and one came to everything.", {"happiness": 2}, {"support": 3, "parole_mood": 3})),
  cooldown=20)
