# Exec'd by gen_pets.py (shares E, C, O, F and HOME). Pets Life v1.3: the pack, litters, and more days.

PK = {"pet": ["pack"]}
ADULT = {"pet": ["pack", "adult"]}

E("pk.bowl", "🥣", "Whose bowl",
  "There are two bowls by the back door and one of them is clearly the better bowl. {~Nobody has ever said so|It has been the better bowl since the day it arrived}. {~Everyone knows|The whole house knows}.",
  PK,
  C("Take the good bowl",
    O("I went in first and ate slowly. The others waited. It was a small, brutal victory, and I tried not to enjoy it.", {"happiness": 3}, {"standing": 5, "belonging": -3}),
    O("I got it by being quicker. They shifted aside. They'll remember.", {"happiness": 2, "stress": 2}, {"standing": 4, "belonging": -2})),
  C("Let the other one have it",
    O("I moved aside. It was a courtesy, and everybody noticed. I ate from the old bowl and it tasted the same.", {"happiness": 2}, {"standing": -3, "belonging": 5}),
    O("I deferred. It's easier to keep the peace than the best bowl. They gave me a long, careful look afterwards.", {"stress": -1}, {"standing": -2, "belonging": 4})),
  C("Eat from both",
    O("I made a nuisance of myself with both. Order broke down. We were all told off, which at least was fair.", {"stress": 3, "happiness": 1}, {"standing": 0, "belonging": 2}),
    O("I went from one to the other, and nobody could say anything. It was chaos and I'd do it again.", {"happiness": 3}, {"standing": 1, "instinct": 2})),
  cooldown=10)

E("pk.newcomer", "🐾", "A new smell in the hall",
  "There's a carrier in the hall and something is breathing in it. The people are being very bright and very quiet. Whatever's in there, it's staying.",
  {"pet": ["pack", "has_home"]},
  C("Meet it at the door",
    O("I put my nose to the grille. It put its nose to mine. That was the first thing, and in some ways the whole thing. We worked out the rest by Thursday.", {"happiness": 4}, {"belonging": 6, "packmate": 1}),
    O("I was calm, and polite, and clear about my position. It took the point. The new one learned the house from me.", {"happiness": 3}, {"standing": 4, "packmate": 1})),
  C("Sulk for a week",
    O("I withdrew to a high place and did not come down. The new one had my bed. Eventually I had to concede that it was a good bed for two.", {"stress": 6, "happiness": -3}, {"belonging": 2, "packmate": 1}),
    O("I made it clear I had been wronged. It took six days and a lot of treats for me to forgive anybody.", {"stress": 5}, {"bond": -2, "packmate": 1})),
  C("Test it",
    O("A growl, a snap, a retreat. We did a lot of this. By the end of the month we had a pecking order and a cold war and a secret friendship.", {"stress": 4, "happiness": 2}, {"standing": 3, "packmate": 1}),
    O("I tried it with the shoe, the food, the bed. It passed most of them. I respect that.", {"stress": 2, "happiness": 2}, {"belonging": 4, "packmate": 1})),
  cooldown=40)

E("pk.leader", "👑", "The one in charge",
  "There's one of us the others watch. {~The leader has never needed to growl|The leader barely has to look up}. Today they're asleep in the doorway, and everyone is stepping carefully round them.",
  PK,
  C("Step over them",
    O("I stepped over them. One eye opened. It closed again. I took a note.", {"happiness": 1}, {"standing": 5, "instinct": 2}),
    O("I walked across. They let me. Whatever was supposed to happen didn't, and the room noticed.", {"stress": 2}, {"standing": 6})),
  C("Go round",
    O("I went round the long way, like everyone else, and felt the old order settle again like a warm blanket.", {"stress": -2}, {"standing": -1, "belonging": 3}),
    O("I took the long way. Nobody said anything. Good order is something you can feel in the floor.", {"stress": -2}, {"belonging": 3})),
  C("Lie down next to them",
    O("I lay in the warm bit next to the leader and was allowed to stay. A quiet kind of promotion.", {"happiness": 4, "stress": -4}, {"standing": 4, "belonging": 6}),
    O("They shifted a bit to make room. It's the nicest thing anyone has done for me all year.", {"happiness": 4}, {"belonging": 7})),
  cooldown=12)

E("pk.loss", "🕯️", "The empty place",
  "There's a spot on the sofa that nobody is sitting in. The people keep looking at it. {~The bowl by the door is the wrong shape of empty|The smell in the hall is going, day by day}.",
  PK,
  C("Lie in their spot",
    O("It still smelled of them. I lay in it for a week, and when the smell was gone I stayed anyway.", {"happiness": -4, "stress": -3}, {"belonging": 4, "bond": 3}),
    O("I took their place on the sofa. The humans looked at me and didn't move me.", {"happiness": -2, "stress": -4}, {"bond": 4})),
  C("Look for them",
    O("I checked every room, twice a day. Eventually I stopped. I haven't stopped checking, entirely.", {"happiness": -6, "stress": 4}, {"belonging": -3}),
    O("I went to the door and waited. Nobody came. A person sat on the step with me, and we didn't talk about it.", {"happiness": -4}, {"bond": 5})),
  C("Press on",
    O("I played, because that's what you do. It was a bit hollow at first. After a while it wasn't.", {"happiness": 1}, {"fitness": 3}),
    O("I got on with things. I ate, I slept, I chased the usual. I slept closer to the people.", {"happiness": -1}, {"bond": 4})),
  cooldown=40)

E("pk.mate", "💞", "The one at the fence",
  "A {~sleek|scruffy|determined} someone has been at the fence every afternoon for a week. I find that my attention has narrowed to a single point. This is, I understand, a thing that happens.",
  {"pet": ["adult", "has_home"]},
  C("Follow your nose",
    O("It was the best week of my life. I'd be lying to say I'd planned anything.", {"happiness": 8}, {"instinct": 4, "litters": 0}),
    O("We met at the gate and it was inevitable. I have thoughts about it still.", {"happiness": 6, "stress": 3}, {"instinct": 4})),
  C("Stay by the people",
    O("I stayed in. I sat by the window. I'll admit it hurt a little to be sensible.", {"happiness": -3, "stress": 4}, {"bond": 3, "obedience": 3}),
    O("I looked at the fence all afternoon, and then at {o.first}, and decided to be good. It cost something.", {"happiness": -2}, {"bond": 4, "obedience": 3})),
  C("Make a break for it",
    O("I got out. It was glorious. I came home after two days with leaves in my coat and a look on my face that fooled no one.", {"happiness": 6, "stress": 4}, {"escapes": 1, "instinct": 5, "territory": 4}),
    O("I was gone before anyone saw the gate open. I came back. I'd like it known that I came back.", {"happiness": 5, "stress": 3}, {"escapes": 1, "territory": 4})),
  roles=OWN, cooldown=12)

E("pk.pups", "🍼", "The first night with the pups",
  "{~They are not much bigger than a hand|They are warm and blind and loud}, and they're mine, and they smell of milk. It's three in the morning, and one of them has just discovered its voice.",
  {"pet": ["pups"]},
  C("Keep them close",
    O("I curled round them, all night, every night, for a fortnight. I did not eat properly and I didn't care.", {"happiness": 6, "health": -2, "stress": 3}, {"bond": 3, "belonging": 6}),
    O("I wouldn't let anyone near them for a week. Eventually I was talked round by a hand and a bowl of something good.", {"happiness": 5, "stress": 4}, {"belonging": 5})),
  C("Let {o.first} help",
    O("{o.first} sat on the floor for hours, with a towel and a hot-water bottle and a lot of patience. I let them. It was the right call.", {"happiness": 6}, {"bond": 8}),
    O("I let them hold one. I watched like a hawk. {o.first} said afterwards that I was the best parent they'd ever seen.", {"happiness": 5}, {"bond": 6})),
  C("Leave them to it",
    O("I took a break. A short one. I felt awful, then lighter, then awful again. They were fine.", {"happiness": 2, "stress": -2}, {"bond": -1}),
    O("I went off for the afternoon and slept in the sun. I came back to a chorus. It was the best sound I'd ever heard.", {"happiness": 4, "stress": -3}, {})),
  roles=OWN, cooldown=12)

E("pk.rehome", "📦", "Homes for them",
  "People are coming to look at the pups. A woman with a clipboard, a boy who can't keep his hands still, a quiet man with a very good coat. Each of them is holding one of mine.",
  {"pet": ["pups"]},
  C("Watch each one carefully",
    O("I stood and watched. The right ones were the ones who looked at the pup, not at me. It went well. I'd like to think I was a good judge.", {"happiness": 2, "stress": 4}, {"bond": 2}),
    O("I reviewed each of them with a fixed stare. Three were rejected. They didn't know why, and neither did {o.first}.", {"happiness": 1, "stress": 5}, {"standing": 2})),
  C("Hide one",
    O("I took the smallest into the cupboard and sat in front of it. {o.first} found us, and sighed, and put a note on the list: 'staying'.", {"happiness": 6}, {"bond": 5, "belonging": 4, "packmate": 1}),
    O("I tucked one behind the sofa. It stayed. It's here now. It has my ears.", {"happiness": 6}, {"belonging": 5, "packmate": 1})),
  C("Let them go",
    O("They left one by one, in arms and boxes and on a lead. By the last, I was just watching. The house was very quiet.", {"happiness": -3, "stress": 3}, {"belonging": -3}),
    O("I let them go. I think I understood. The house was quiet. I slept very late the next day.", {"happiness": -2}, {"bond": 3})),
  roles=OWN, cooldown=12)

E("pk.street", "🌆", "The crew",
  "{~Three of us|Four of us|Five of us} run the stretch behind the market. We've got a spot, a schedule and a way of working the bins. A new one has turned up at the end of the alley, thin and watchful.",
  {"pet": ["homeless"]},
  C("Let it in",
    O("Another body, another pair of eyes. It was good with the lorries. Within a month it was one of us.", {"happiness": 3}, {"belonging": 6, "packmate": 1}),
    O("I let it share the warm vent. It remembered. Some debts are good ones to have.", {"happiness": 3}, {"belonging": 5, "packmate": 1})),
  C("Drive it off",
    O("A noisy, vicious few minutes. The new one left. I won, and I felt it all night.", {"stress": 4, "happiness": -2}, {"standing": 5, "instinct": 4}),
    O("It left. The alley stayed ours. Nobody was friendly with me for a day or two, though.", {"stress": 3}, {"standing": 3})),
  C("Test it with a bone",
    O("I dropped a scrap and watched. It waited, took it only when I'd gone. Good manners. It stayed.", {"happiness": 2}, {"belonging": 4, "packmate": 1}),
    O("It took it, and fought for it, and lost. It still limped after us, and I had to respect that.", {"happiness": 1, "stress": 2}, {"standing": 2})),
  cooldown=12)

E("pk.hierarchy", "📊", "The long argument",
  "It's been building all week. {~A look over a bowl|A snap on the stairs|A growl at the door} and then a rumble, a stand-off, and now the whole room is leaning to see what happens next.",
  {"pet": ["pack", "adult"]},
  C("Stand your ground",
    O("I stood tall and I made myself big, and said, in every way I know, that I was not moving. They moved.", {"stress": 4, "happiness": 2}, {"standing": 8}),
    O("I didn't blink. It went on for a long time. In the end it didn't need to be a fight.", {"stress": 5}, {"standing": 6})),
  C("Back down",
    O("I looked away first. It didn't hurt as much as I'd expected. The room relaxed.", {"stress": -2}, {"standing": -6, "belonging": 4}),
    O("I conceded, and went to my bed. Nobody said anything. The day went on.", {"stress": -2}, {"standing": -5, "belonging": 3})),
  C("Make a noise and run",
    O("I created a distraction with a considerable amount of shouting. Everything stopped. We all looked at the person coming to see what was going on.", {"happiness": 2, "stress": 2}, {"standing": 1, "mischief": 1}),
    O("I yelled the house down and skidded round the corner. The whole argument evaporated into a tangle of laughing and shouting.", {"happiness": 3}, {"belonging": 3, "mischief": 1})),
  cooldown=10)

E("old.quiet", "🌙", "The long quiet",
  "I sleep more than I used to. I find that I'm just as content in the sun as I ever was in the run. The younger ones race around me, and I watch them, and I think: I was that, once.",
  {"pet": ["senior", "pack"]},
  C("Teach the young ones",
    O("I showed one of them where the warm spot is, and the best way to get a treat. They listened more than I had expected.", {"happiness": 4}, {"standing": 3, "belonging": 5}),
    O("I gave them the old lessons. They're better at them than I was. I told them so.", {"happiness": 4}, {"belonging": 5})),
  C("Let them go on without me",
    O("I let the runners run. I lay in the shade and watched the shape of the afternoon.", {"happiness": 3, "stress": -4}, {"belonging": 3}),
    O("I let them play. From the sofa the world is a fine place and I'm happy to watch it.", {"happiness": 3, "stress": -4}, {})),
  C("Stay close to the people",
    O("I spent the months on the sofa, at someone's feet, a heavy warm weight. I think they liked the weight.", {"happiness": 5, "stress": -5}, {"bond": 6}),
    O("A lap, a rug, the same low chair. It's all I need.", {"happiness": 5, "stress": -5}, {"bond": 5})),
  cooldown=12)

# --- more ordinary days, for every animal in a home
E("day.delivery", "📦", "The box",
  "A large cardboard box has arrived and the people have taken what was inside and left the box. The box is empty. The box is on the floor. I regard this as an invitation.",
  HOME,
  C("Get in",
    O("I was in it before they'd put the tape down. It was a perfect fit. I would be unreachable for the rest of the afternoon.", {"happiness": 5, "stress": -4}, {"bond": 2}),
    O("I got in, turned round three times, and sat. {o.first} took a photograph. It was, I'm told, a hit.", {"happiness": 4}, {"bond": 3})),
  C("Destroy it",
    O("It took four minutes, and the carpet is now a snowfield. I regret nothing.", {"happiness": 4}, {"mischief": 2, "instinct": 3}),
    O("I took it apart with a degree of purpose. {o.first} stood in the doorway and said my name in a particular way.", {"happiness": 3}, {"mischief": 2, "bond": -1})),
  C("Ignore it",
    O("It was a box. I'm an adult. I looked at it for several minutes before I got in.", {"happiness": 2}, {"obedience": 1}),
    O("I walked past it with an air of indifference. At night, when no one was watching, I sat in it.", {"happiness": 3}, {})),
  roles=OWN, cooldown=10)

E("day.visitor", "🧳", "Someone's brought a suitcase",
  "There's a stranger in the house and they have a suitcase and a habit of sitting in my chair. The people are delighted. I'm assessing the situation.",
  HOME,
  C("Win them over",
    O("A well-timed sigh. A head on the knee. I had them within the hour, and they were in my debt by the end of the week.", {"happiness": 4}, {"bond": 2}),
    O("I did the face. It is a very good face. By the weekend, we were close.", {"happiness": 4}, {"bond": 2})),
  C("Guard the house",
    O("I stood between the stranger and the stairs for most of a day. They were very patient with me. By evening I conceded they were allowed to use the toilet.", {"stress": 4}, {"obedience": -2, "instinct": 3}),
    O("I patrolled, and growled, and reported to the window. They were allowed, eventually, to stay.", {"stress": 3}, {"instinct": 3})),
  C("Hide",
    O("Under the bed. For three days. The stranger left and I came out, and it was as though nothing had happened.", {"stress": 6, "happiness": -2}, {}),
    O("I found a place behind the curtain and watched everything from there. A useful education.", {"stress": 4}, {})),
  roles=OWN, cooldown=12)

E("day.vet2", "💉", "The waiting room",
  "A room full of animals, all of whom are pretending not to be afraid. Someone's cat is making a low continuous noise. The floor smells of something that isn't quite food.",
  {"pet": ["has_home", "owner"]},
  C("Be good",
    O("I sat on {o.first}'s feet and looked at the wall. When my name was called I went in as though it were my idea. I got a biscuit.", {"stress": 3, "happiness": 2}, {"obedience": 3, "bond": 2}),
    O("I was perfect, which was a shock to everyone. The vet said I was an example to the others.", {"stress": 2, "happiness": 3}, {"obedience": 4})),
  C("Make it known",
    O("I told the entire room how I felt. The cat answered. A small dog joined in. {o.first} apologised to everybody.", {"stress": 4, "happiness": 1}, {"obedience": -2, "instinct": 2}),
    O("I protested at some length and at some volume. The vet was unmoved, and good with their hands.", {"stress": 5}, {"obedience": -1})),
  C("Try to leave",
    O("I got as far as the door. A kind receptionist caught me with a biscuit. It was a trap, and a fair one.", {"stress": 6}, {"escapes": 0, "obedience": -2}),
    O("I wedged myself under the chair. It took two people to remove me. I'll be remembered.", {"stress": 6, "happiness": -1}, {"obedience": -3})),
  roles=OWN, cooldown=8)

E("day.walk2", "🍂", "The new route",
  "We're going a different way today. The usual turn is behind us and ahead there's a street that smells of things I've never smelled. {o.first} seems unsure. I am not.",
  {"pet": ["has_home", "owner", "dog"]},
  C("Lead the way",
    O("I pulled, gently, towards the park with the pond. {o.first} laughed and let me. We found a bench and a man with sandwiches.", {"happiness": 5}, {"territory": 5, "bond": 3}),
    O("I took the lead and we found a lane I'd only ever smelled from a distance. I put a nose on every post.", {"happiness": 5}, {"territory": 6})),
  C("Stay close",
    O("I stayed at heel. It was a slower walk, but I saw things properly: the bakery, the cat in the window, the old man's chair.", {"happiness": 3}, {"obedience": 3, "bond": 3}),
    O("I kept to {o.first}'s side. The world was big and I was glad of the lead.", {"happiness": 3}, {"bond": 4})),
  C("Go home",
    O("I turned round and sat down. We went home, by the usual way. Some things are as they should be.", {"happiness": 1}, {"bond": 1}),
    O("I sat on the kerb and wouldn't move. We went back. I'm creature of habit and proud of it.", {"happiness": 1}, {"obedience": -1})),
  roles=OWN, cooldown=8)

E("day.sunbeam", "☀️", "The best spot",
  "A square of sunlight is crossing the floor, and a chair, and a sofa arm. At exactly four o'clock it will be in the corner of the room. I know this. I intend to be there.",
  HOME,
  C("Get there first",
    O("I was there at 3:50, flat on my side, one eye open, as the light arrived. I was warm in a way that is hard to describe.", {"happiness": 5, "stress": -6}, {}),
    O("I took the best spot and made myself look comfortable. No one challenged me. It's a gift.", {"happiness": 5, "stress": -6}, {"standing": 2})),
  C("Share it",
    O("I moved aside. A packmate climbed in. We lay together in the one warm patch in the house, in perfect silence.", {"happiness": 6, "stress": -5}, {"belonging": 5}),
    O("I shared the patch with {o.first}'s foot. It was a very good arrangement.", {"happiness": 5}, {"bond": 3})),
  C("Wait for a better one",
    O("I waited. The light moved. I got a better spot, in the end, and it was mine alone.", {"happiness": 4, "stress": -4}, {}),
    O("I moved on to the kitchen floor, where it was cooler. I'm a connoisseur.", {"happiness": 3}, {})),
  roles=OWN, cooldown=6)
