from prison_lib import *

G = "guard"

# ====================================================================== the first years
E("g.first_day", "🗝️", "The first day",
  "{sup.first}, your sergeant, hands you a ring of keys and a radio, and says the same sentence he says to every recruit: 'Nobody knows. Not me. Not the warden. You'll learn it faster if you stop pretending you do.'",
  ["served<=1"],
  C("Listen and learn",
    O("I shadowed him all week. He did a hundred small things without seeming to think about them: the tilt of a head, a half step to the left. By Friday I could recognise the shape of a bad afternoon before it happened.", {"smarts": 2, "stress": -2}, {"merit": 3, "control": 4}),
    O("I wrote everything down in a notebook I kept in my sock. It was an odd thing to do, and I still have it. The things I wrote on the first day are the things that matter most.", {"smarts": 1}, {"merit": 2, "integrity": 2})),
  C("Show you're not afraid",
    O("I walked down the middle of the landing as if I owned it. A man said something about my boots. I smiled at him. I'd done everything right in the wrong order.", {"stress": 5}, {"control": -3, "merit": 1}),
    O("I walked the landing at a deliberate pace. The wing watched. A man at the end nodded, once, in a way that said he'd decided something about me.", {"stress": 3}, {"control": 3, "merit": 2})),
  C("Keep your head down",
    O("I did my job and said nothing. By the end of the first month, no one on the wing could tell you my name. This is its own kind of failure, and its own kind of safety.", {"stress": -1}, {"control": -2, "merit": 1}),
    O("I kept my head down and my radio on. It was slow, safe and entirely forgettable. For a first year, that's no bad thing.", {"stress": 0}, {"merit": 2, "integrity": 1})),
  role=G, roles=SUP, cooldown=40, once=True)

E("g.lesson", "🎓", "The rules nobody wrote",
  "{co.first}, who has done fourteen years, takes you aside after your third week. 'There are two sets of rules in here,' {co.he} says. 'The ones in the book and the ones that keep you alive. Want to hear the second set?'",
  ["served<=2"],
  C("Yes, tell me",
    O("{co.first} taught me: who to talk to, who to leave alone, how to stand in a doorway so a man can see your hands. Some of it was wisdom and some of it was habit that had calcified, and I couldn't always tell which.", {"smarts": 2}, {"merit": 3, "control": 3}),
    O("It was a list. Don't take food from the inmates. Don't tell anyone where you live. Never be the last officer on a landing. Never be alone with one of them if you can help it. I've kept all four.", {"smarts": 1, "stress": -2}, {"merit": 2, "integrity": 2})),
  C("Say you'll go by the book",
    O("{co.first} looked at me for a moment, and nodded. 'Good,' {co.he} said, 'and when you find out the book isn't enough, come and find me.' I did, about six weeks later.", {"stress": 2}, {"integrity": 3, "merit": 1}),
    O("I said I'd stick to the book. {co.first} said nothing, but I saw a look. By the end of the year I knew what it meant.", {"stress": 3}, {"integrity": 4})),
  C("Ask what the catch is",
    O("{co.first} laughed. 'There's always a catch,' {co.he} said. 'The catch is that you start using the second set for yourself.' I wrote that down.", {"smarts": 2}, {"merit": 2, "integrity": 2}),
    O("{co.first} said, 'You'll do.' It was the most generous thing anyone had said to me that month.", {"happiness": 3}, {"merit": 2, "union": 4})),
  role=G, roles=COG, cooldown=30, once=True)

E("g.first_death", "🕯️", "The first one",
  "At 4.50 in the morning, on a routine check, I find a man on the floor of cell nineteen. He's cold. His face is calm. The alarm goes up, and I do everything I was trained to do, and none of it matters.",
  ["served>=1"],
  C("Do everything by the book",
    O("I did the checks, I called the code, I started compressions and kept going until the nurse touched my arm. The report was clean. The sound of the ribs is not in the report.", {"stress": 14, "happiness": -6, "karma": 2}, {"trauma": 10, "merit": 3, "incident": 1, "control": 2}),
    O("The book saved me, as it does. I followed every step. The coroner found no fault. I found a great deal.", {"stress": 12, "happiness": -5}, {"trauma": 9, "merit": 3, "incident": 1})),
  C("Break down afterwards",
    O("I got through the shift. I went to the car park, sat in the front seat, and shook for twenty minutes. Nobody came. Nobody does.", {"stress": 12, "happiness": -8}, {"trauma": 14, "incident": 1}),
    O("I wept in the locker room. {sup.first} found me there, sat next to me, said nothing for a minute, and then told me about his first one. I've never felt less alone.", {"stress": 6, "happiness": -3}, {"trauma": 7, "union": 5, "incident": 1})),
  C("Ask to talk to someone",
    O("The service offered a counsellor, a tired man in a small room, with a box of tissues and a clock. He listened. It helped, a little, and I went back more than I expected to.", {"stress": 4, "happiness": 2}, {"trauma": 4, "incident": 1}),
    O("I asked for a day off and got a form. By the time it was approved I'd done another three shifts. Nothing came of it, but I filed it.", {"stress": 10}, {"trauma": 12, "incident": 1})),
  role=G, roles=SUP, cooldown=30, once=True)

E("g.extraction", "🚪", "The cell extraction",
  "A man in cell twelve has barricaded the door with his mattress and a bed frame. He says he has a blade. The shift supervisor wants the extraction team. You are the newest on it.",
  ["served>=1", "tension>=40"],
  C("Go in first, by the book",
    O("We went in as trained. Shield, bar, shield, bar. It took four minutes. He was uninjured and the officers were uninjured and the report says that everyone did as they were told. That's the nearest thing to a good day there is.", {"stress": 10, "happiness": 2}, {"control": 6, "merit": 4, "incident": 1}),
    O("I went in first. The blade was real, and a small one. A hand struck my arm, a quick flash, a lot of noise. I came out with a gash and a medal of sorts.", {"health": -8, "stress": 10}, {"control": 6, "merit": 5, "commend": 1, "incident": 1})),
  C("Hang back",
    O("I stayed on the second line. It was the safe position and nobody commented. Later, I found I had not been picked for the next team.", {"stress": 8}, {"control": -2, "merit": -2, "incident": 1}),
    O("I let the others go in. Afterwards nobody said anything about it, which was worse than if they had.", {"stress": 8, "happiness": -3}, {"union": -4, "incident": 1})),
  C("Try to talk him out",
    O("I spoke to him through the hatch, for forty minutes. I said his name, which I'd learned from the file. He came out at last with the blade held loosely. It was a terrible, tiring kind of triumph.", {"stress": 10, "karma": 4}, {"control": 6, "integrity": 4, "merit": 5, "incident": 1, "commend": 1}),
    O("I tried, and he talked back, and for a few minutes it worked. Then he heard the shields in the corridor and everything broke. It ended the way the other way would have, only longer.", {"stress": 12}, {"control": 2, "incident": 1})),
  role=G, roles=SUP, cooldown=12)

# ====================================================================== force and its consequences
E("g.force", "🥊", "A fight on the landing",
  "Two inmates are on the floor, one on top, hitting hard. The one underneath has stopped moving. I am the nearest officer and my radio is already shouting.",
  ["served>=1"],
  C("Wade in with all the force I have",
    O("I got between them in two steps and put the man on top onto the floor face-down. It took a lot of force. It took more than I had a right to. The report called it 'proportionate'. I am the only one who knows.", {"stress": 10, "happiness": -4}, {"control": 6, "merit": 3, "force_bad": 1, "ia_heat": 8, "incident": 1}),
    O("I put him down, hard, with a knee in the back. The medics said afterwards that it was necessary, and I said it was. I looked at my hands later.", {"stress": 10}, {"control": 6, "merit": 3, "force_bad": 1, "incident": 1, "ia_heat": 5})),
  C("Use the minimum, and wait for backup",
    O("I used the baton as a barrier, and my voice, and a hand on the man's collar. It took ninety seconds and it was ugly. The man on the floor lived. The report was long and clean.", {"stress": 8, "karma": 3}, {"control": 4, "integrity": 4, "merit": 4, "incident": 1, "commend": 1}),
    O("I got between them. I took a punch for it. When the others arrived, it was over, and I had a split lip and a good report.", {"health": -3, "stress": 8, "karma": 3}, {"control": 3, "integrity": 3, "merit": 3, "incident": 1})),
  C("Wait for the others",
    O("I waited. I know that 'wait' is in the book. It was eleven seconds. When I looked at the man on the floor afterwards, I counted them again.", {"stress": 12, "happiness": -6, "karma": -3}, {"control": -4, "trauma": 6, "incident": 1}),
    O("I stood at the rail and waited for the response team. By the time they arrived, it was too late for the man underneath. The inquiry cleared me. I didn't feel cleared.", {"stress": 14, "happiness": -8}, {"control": -5, "trauma": 10, "incident": 1, "ia_heat": 6})),
  role=G, cooldown=8)

E("g.force_inquiry", "🕵️", "The inquiry",
  "A man from Internal Affairs sits across the table in the small interview room. He has a tape recorder, a notebook and my incident report from March, which he turns to face me.",
  ["force_bad>=1", "ia_heat>=12"],
  C("Tell it exactly as it was",
    O("I said what I did and why I did it, and where I thought I'd gone too far. He wrote it down without comment. Nothing came of it that year. I think he found it unusual to hear it said.", {"stress": 10, "karma": 4}, {"integrity": 5, "ia_heat": -15, "standing": -2}),
    O("I told him all of it. The union rep winced. I was given a written warning, which is the lightest thing they have. I slept better than I had in months.", {"stress": 8, "karma": 5}, {"integrity": 6, "ia_heat": -10, "standing": -4})),
  C("Stick to the report",
    O("I stuck to it, word for word, and he kept looking at me. In the end he closed the notebook. 'Thank you,' he said. I knew he knew. I knew I knew.", {"stress": 12}, {"ia_heat": -6, "integrity": -3}),
    O("I said what the report said. He asked if I wanted to add anything. I said no. It was true, and it was not the truth, and it cost me.", {"stress": 10, "happiness": -3}, {"ia_heat": -4, "integrity": -4})),
  C("Let the union handle it",
    O("The union rep spoke for me for most of the hour. He's very good at it. The matter was closed 'without findings', and I owed him a drink and a great deal more.", {"stress": 6}, {"ia_heat": -12, "union": -3, "standing": -1}),
    O("The rep sat beside me and said 'no comment' on my behalf nine times. It worked. I never got over how easy it was.", {"stress": 6, "happiness": -2}, {"ia_heat": -10, "integrity": -2})),
  role=G, cooldown=14)

# ====================================================================== temptation
E("g.favour", "🎁", "A small favour",
  "An inmate I've known for two years catches my eye in the corridor. 'Boss,' he says, 'would you ring my sister and tell her I'm all right? She worries.' He gives me a number on a scrap of paper.",
  ["served>=1", "integrity>=30"],
  C("Make the call",
    O("It was a thirty-second call to a woman in a kitchen. She cried. I said, 'He's fine, he's eating,' and hung up. It was a breach of three separate rules, and it was the best thing I did that week.", {"stress": 6, "karma": 4}, {"corruption": 1, "integrity": -3, "ia_heat": 3}),
    O("I made the call. She said thank you eleven times. A week later the inmate stopped me and said something quiet, and I realised I had acquired a friend and a debt.", {"stress": 6}, {"integrity": -2, "corruption": 1, "union": 0})),
  C("Refuse, but kindly",
    O("I told him I couldn't. I told him why. He nodded, and said, 'Fair.' Two weeks later he warned me about a thing that was going to kick off on the east landing. I think he'd respected that I said no.", {"stress": 2}, {"integrity": 3, "intel": ["plan", "Something is being arranged on the east landing"]}),
    O("I said no, and meant it. He didn't ask again. But I thought about the sister, in the kitchen, for a long time.", {"stress": 4}, {"integrity": 3})),
  C("Report the approach",
    O("I wrote it up. By the book. It was the right thing to do, and I felt like a bastard. He was moved to a different wing a month later, and nobody told me why.", {"stress": 6}, {"integrity": 5, "union": -2, "merit": 1}),
    O("I reported it. The supervisor thanked me and made a face. 'You'll get a name for that,' he said, and I did.", {"stress": 5}, {"integrity": 5, "standing": -2, "merit": 1})),
  role=G, cooldown=10)

E("g.bribe", "💷", "An envelope",
  "It's on the passenger seat of my car. It wasn't there when I parked. No note. There's $800 in it, and a Post-it with the name of an inmate, a landing and a word: 'Thursday'.",
  ["served>=2"],
  C("Take it, and do what it asks",
    O("Thursday came. I looked at the wall for eleven minutes. Something went through a hatch. The next week, there was a second envelope. I have never been more afraid and more relieved.", {"stress": 12, "happiness": -3}, {"bribe": 800, "integrity": -4}),
    O("I took it and did it. I told myself it was one time. By October it was a regular arrangement, and by Christmas I had a second set of keys in my head.", {"stress": 10}, {"bribe": 800, "ring": 3, "integrity": -6})),
  C("Leave it where it is",
    O("I left it on the seat and drove home. The next morning it was gone. Nobody said anything. For a week, I looked at every inmate I walked past.", {"stress": 8}, {"integrity": 3}),
    O("I left it, and drove to the station, and sat in the car park for a quarter of an hour. Then I went in and did my shift. Nothing happened. That was worse.", {"stress": 8}, {"integrity": 3, "ia_heat": -2})),
  C("Report it",
    O("I took it to my sergeant. He looked at it for a long time and then at me. 'Good,' he said. The inmate was transferred, and I had a month of cold shoulders from the wing. It's the best decision I made that year.", {"stress": 8, "karma": 6}, {"integrity": 8, "standing": 3, "union": -4, "ia_heat": -8, "intel": ["corruption", "A trafficking route into the east wing"]}),
    O("I took it to Internal Affairs. A man named {sup.first} sent me for coffee while he made calls. I was given a recommendation and a list of enemies.", {"stress": 10, "karma": 6}, {"integrity": 9, "standing": 4, "union": -6, "ia_heat": -10, "intel": ["corruption", "A trafficking route into the east wing"]})),
  role=G, roles=SUP, cooldown=12)

E("g.ring", "🕸️", "The staff who aren't",
  "{co.first} has been buying rounds for three months with notes I haven't seen before. Tonight {co.he} says, 'There's something you ought to be in on.'",
  ["served>=3", "integrity<=65"],
  C("Hear them out",
    O("It was a small ring: four officers, a trusted trade-in of phones and tobacco, a share for everyone. The money was real. The way it was explained made it sound like a pension plan.", {"stress": 8}, {"bribe": 1500, "ring": 4, "union": 8}),
    O("I listened, and said I'd think. For a month, I was both outsider and insider. At the end of it I had a hard choice and no easy way out.", {"stress": 8}, {"intel": ["corruption", "A ring of four officers on the east landing"]})),
  C("Say no, and say nothing",
    O("I said no. {co.first} nodded, and said nothing more. The following week my locker was moved. The week after that, someone put a dead rat in it. I was never invited again.", {"stress": 8}, {"integrity": 4, "union": -6, "intel": ["corruption", "A ring of four officers on the east landing"]}),
    O("I said no and walked away. The silence in the canteen the next day was a physical thing. I ate my sandwich in the car.", {"stress": 6, "happiness": -3}, {"integrity": 4, "union": -4})),
  C("Go to Internal Affairs",
    O("I took notes for two weeks and handed them to a woman in a grey suit. Eight months later the ring was dismantled. I was never named. Everyone knew.", {"stress": 12, "karma": 8}, {"integrity": 10, "standing": 2, "union": -12, "ia_heat": -12, "whistle": True}),
    O("I told IA. They asked me to wear a wire. I did. I'll say no more. I'd do it again, and I'd never do it twice.", {"stress": 16, "karma": 8}, {"integrity": 10, "union": -15, "ia_heat": -15, "whistle": True})),
  role=G, roles=COG, cooldown=20)

E("g.romance", "💘", "Too much attention",
  "An inmate who has been on the wing for three years has begun leaving his work station to talk to you. He's clever, and kind, and I find that I am listening for the sound of his voice.",
  ["served>=3", "integrity>=20"],
  C("End it now",
    O("I told him I couldn't talk to him except about the job. He said, 'I understand,' and, to his credit, did. The rest of the year was a lot quieter and a lot colder.", {"stress": 6, "happiness": -4}, {"integrity": 4}),
    O("I had myself moved to another landing. A month later I had a note, handwritten, from him, saying thank you. I never learned what for.", {"stress": 5, "happiness": -2}, {"integrity": 5, "control": -4})),
  C("Report myself",
    O("I told my sergeant. He looked at me for a while. 'Thank you,' he said. 'That's the bravest thing you'll do this year.' I was reassigned.", {"stress": 8, "happiness": -3}, {"integrity": 7, "standing": 2, "merit": 1}),
    O("I walked into the deputy's office and said it. The deputy said nothing for a minute, and then helped me do what had to be done. It was the best bit of management I ever saw.", {"stress": 8}, {"integrity": 8, "standing": 3})),
  C("Let it go on",
    O("It was a year. It was a long, strained, secret year, and it ended in a shared look across a corridor and the smell of floor polish. He was transferred. I was found out.", {"stress": 14, "happiness": -8}, {"integrity": -15, "ia_heat": 20, "corruption": 1}),
    O("I let it go on, and I paid for it for years. I'd do almost anything to get one more hour of that, and it was the worst thing I've done.", {"stress": 12, "happiness": -4}, {"integrity": -14, "ia_heat": 18, "corruption": 1})),
  role=G, roles=INM, cooldown=30, once=True)

# ====================================================================== the job
E("g.overtime", "⏱️", "Short-staffed",
  "Three officers are off sick and another two are on leave. The roster has a hole in it that the supervisor is trying to fill with names. He's looking at me.",
  ["served>=1"],
  C("Take the double",
    O("Sixteen hours. The wing is different at four in the morning: quieter, closer. I made a rule of walking the whole of it twice. I got home at six and fell asleep in the car.", {"stress": 8, "money": 900}, {"trauma": 4, "merit": 2, "control": 2}),
    O("I took it. It was my fourth that month. My wife said nothing at all when I got home, which she says only when she's furious.", {"stress": 10, "happiness": -3, "money": 900}, {"trauma": 6, "merit": 2})),
  C("Say you can't",
    O("I said I couldn't. He nodded, and said, 'No problem', in a voice that said there was. Someone else took the shift. It was the right decision, and a small, hard one.", {"stress": 3}, {"merit": -1, "union": 2}),
    O("I said I'd promised my daughter. He made a face and wrote something. I got the weekend, and she got a father.", {"happiness": 4}, {"merit": -1, "trauma": -3})),
  C("Organise the union",
    O("I called a meeting, and fifty officers came. It became a letter, and then a bulletin, and then a headline. I was not popular upstairs.", {"stress": 6}, {"union": 14, "standing": -3, "merit": -1}),
    O("I wrote to the union rep. He wrote to the warden. The warden wrote to the minister. In the end we got four more officers, none of whom had been trained.", {"stress": 4}, {"union": 10, "merit": 1})),
  role=G, roles=SUP, cooldown=8)

E("g.promotion_board", "📈", "The board",
  "The promotion board is three people at a table and a flipchart. They have read your record, your reports and the comments of the officers who work with you. One of them asks, 'What is the hardest decision you've made in this job?'",
  ["merit>=20", "rank<=5"],
  C("Tell the truth about a mistake",
    O("I told them about the landing in March. I told them what I'd have done differently. They looked at each other. The chair said, 'That's the right answer', and wrote something down.", {"stress": 6, "happiness": 3}, {"merit": 6, "integrity": 3}),
    O("I told them I'd made a mistake. I'd assumed it would cost me, and instead it won me their trust. That's the most surprising thing I've found about authority.", {"stress": 5}, {"merit": 5})),
  C("Describe a success",
    O("I told the story of the hostage, and the radio, and the chaplain. It's a good story. It was the right one for a promotion board. I was promoted within the month.", {"happiness": 5}, {"merit": 8, "standing": 2}),
    O("I told them what I'd done well. It was true. It was also what everybody tells a board, and the chair's face betrayed no surprise.", {"stress": 3}, {"merit": 3})),
  C("Say the question is unfair",
    O("I said that no decision in this job is only one decision. They liked that, in a way. They liked it less in the notes.", {"stress": 5}, {"merit": 2, "integrity": 2}),
    O("I said that. It was true. I did not get the promotion that year, and the one who did was a man who'd answered the question.", {"stress": 8, "happiness": -4}, {"merit": -2})),
  role=G, cooldown=12)

E("g.inspection", "📋", "The inspectors",
  "A delegation from the ministry arrives with clipboards. The warden has told all staff to be on their best behaviour. The wing has been cleaned in the night. Nobody has told the inmates what's happening, but they know.",
  ["served>=2"],
  C("Follow the script",
    O("I did exactly what was asked. I said the right things, in the right order, to the right people. The report was glowing, and utterly false.", {"stress": 4}, {"merit": 3, "integrity": -2, "order": 4}),
    O("I followed the script. Inspectors look for what they've been told to look for, and we gave it to them. It's an art, and I had learned it.", {"stress": 3}, {"merit": 2, "order": 4})),
  C("Tell an inspector the truth",
    O("I stopped one of them in a corridor. I told her about the staffing, the broken locks on the east landing, the ratio. She wrote it down. A year later, there were eight more officers.", {"stress": 8, "karma": 4}, {"integrity": 6, "standing": -3, "budget": 6, "merit": 1}),
    O("I told the truth. It cost me a year of good evaluations. It bought four months of better staffing, and it was worth it.", {"stress": 8, "karma": 3}, {"integrity": 5, "standing": -4, "budget": 4})),
  C("Make sure an inmate gets heard",
    O("I made sure the inspector's route went past cell thirty. A man there handed her a letter. It was a good letter. He was moved to another wing the next week, and I never learned how he got on.", {"stress": 6, "karma": 3}, {"integrity": 4, "tension": 2}),
    O("I steered her to a man with a long list of complaints, all legitimate. He told her everything. I spent a month defending myself, and I'd do it again.", {"stress": 8, "karma": 4}, {"integrity": 5, "standing": -3, "tension": 3})),
  role=G, cooldown=12)

E("g.budget", "✂️", "The memo",
  "A memo has been pinned to the staff-room noticeboard. It uses the words 'efficiencies' and 'rationalisation'. By lunch, everybody has worked out that it means fewer officers and more inmates.",
  ["budget<=50"],
  C("Complain loudly",
    O("I was one of forty who complained. The memo was reissued with a different word on the second line. Nothing else changed.", {"stress": 4}, {"union": 4}),
    O("I wrote to my MP. The reply came in six weeks and was one paragraph long. But the writing felt like doing something.", {"stress": 2}, {"union": 3, "standing": -1})),
  C("Cope and adapt",
    O("We covered the gaps. We always do. Every officer on the wing took another post. The wing was quieter, and more brittle, and a lot more dangerous.", {"stress": 8}, {"trauma": 4, "control": -3, "tension": 6}),
    O("We found workarounds. The workarounds became the system. A year later, nobody could say how the wing had ever been staffed any other way.", {"stress": 6}, {"trauma": 3, "tension": 4})),
  C("Look for another job",
    O("I applied to three other services. I didn't get any of them. I stayed. The not-getting stayed too.", {"stress": 4, "happiness": -3}, {"merit": -1}),
    O("I applied for a transfer to an easier prison. I got it, and found that every prison is the same prison. I came back, eventually, to the one I knew.", {"stress": 6}, {"control": -8})),
  role=G, cooldown=14)

E("g.rookie", "🧑‍🎓", "The new one",
  "A new recruit has been assigned to my wing. She's twenty-two. She's very good at the written tests and very scared of everything else. She calls me 'sir' and I can't make her stop.",
  ["rank>=2"],
  C("Teach her properly",
    O("I taught her what I'd been taught. I stood next to her through the first fortnight. By the end of it she could read a landing. I've never been so proud of anything I haven't done myself.", {"happiness": 5}, {"standing": 4, "merit": 2, "control": 2}),
    O("I took her under my wing, and showed her the things nobody had shown me. She became a good officer. She wrote me a card on her tenth anniversary that said 'second rule is always the first'.", {"happiness": 6}, {"standing": 5, "merit": 2})),
  C("Leave her to sink or swim",
    O("She swam. I'd like to say it was because of me, but it was because she was good. I watched her from a distance for a year.", {"stress": 2}, {"standing": -1}),
    O("She sank. She resigned in the fourth month. I didn't speak to her about it, and have not stopped thinking about that.", {"stress": 5, "happiness": -4, "karma": -3}, {"standing": -2})),
  C("Test her",
    O("I put her into a situation I knew would be difficult. She handled it well. When I told her she'd been set up, she looked at me for a long time. 'Thank you,' she said, and meant it.", {"stress": 3}, {"standing": 2, "merit": 2}),
    O("I put her into the middle of a fight to see what she'd do. She froze. We never discussed it, but she asked for a different wing the next month.", {"stress": 6, "karma": -3}, {"standing": -3})),
  role=G, cooldown=14)

E("g.escape_try", "🏃", "Something's wrong with the count",
  "The count is one short. It is 4.10 on a Friday and the roll call is wrong. I count again. There are 412 inmates in the building and 411 in front of me. Somewhere there is a man who isn't where he should be.",
  ["served>=2"],
  C("Raise the alarm at once",
    O("I called it in. The siren went. Within eleven minutes the man was found in the laundry, in a cart, under a pile of sheets, with a very surprised expression. He'd been trying to get out through the van.", {"stress": 10, "karma": 2}, {"merit": 6, "control": 4, "commend": 1, "incident": 1}),
    O("I raised the alarm. The count was repeated. He was found by the dogs two hours later, in the culvert beyond the second fence, wet and furious.", {"stress": 12}, {"merit": 6, "control": 4, "incident": 1, "tension": 4})),
  C("Check quietly first",
    O("I checked the likely places. It took twenty minutes, and when I found him, he was asleep in the boiler house. Nobody ever knew. I've been very, very careful about the count ever since.", {"stress": 8}, {"control": 2, "integrity": -2, "incident": 1}),
    O("I checked quietly for half an hour. He was gone. By the time I raised the alarm he was a mile away. I was investigated and the finding was 'negligence'.", {"stress": 16, "happiness": -6}, {"merit": -8, "ia_heat": 12, "incident": 1})),
  C("Cover for a colleague",
    O("It was {co.first}'s count. I changed the number. Eleven minutes later he turned up in the library. We never discussed it. It's the nearest I've come to a debt of honour.", {"stress": 8}, {"union": 8, "integrity": -4, "ia_heat": 4}),
    O("I fixed the count, and it caught up with us both in a week. A man in a grey suit asked me what I had been thinking. I said, 'About a friend.'", {"stress": 12}, {"union": 4, "integrity": -5, "ia_heat": 12})),
  role=G, roles=COG, cooldown=14)

E("g.suicide_watch", "🕊️", "On watch",
  "A man on my landing has been put on constant observation. He's sitting on the edge of the bunk with a blanket. He hasn't spoken in two days. It's three in the morning and I'm the only officer awake.",
  ["served>=1"],
  C("Sit and talk",
    O("I pulled up a chair to the door and talked about nothing: the football, the weather, a nickname I'd heard. At five he said, 'It's not the football.' We talked till the light came up. He is still alive.", {"stress": 8, "karma": 6, "happiness": 3}, {"integrity": 4, "trauma": 4, "commend": 1, "lives_saved": 1}),
    O("I talked, and he talked back, a little. I wrote it all down. In the morning I gave the chaplain a note. It wasn't enough. But it was something, and it was all of me.", {"stress": 8, "karma": 5}, {"integrity": 3, "trauma": 5})),
  C("Do the checks and nothing more",
    O("I did the checks every fifteen minutes, as the order said. By dawn I'd done them all, and he was still there. It's what the book requires, and I tell myself it's enough.", {"stress": 6}, {"trauma": 4}),
    O("I did the checks. At 6.10 the nurse arrived and took over. I never found out what happened to him. I wrote 'no concerns' on the sheet and I'd like not to think about it.", {"stress": 8, "happiness": -3}, {"trauma": 6})),
  C("Call a nurse",
    O("I called the duty nurse, who came in her slippers and sat down on the floor outside the door. She was there for three hours. She was better at it than I was.", {"stress": 4, "karma": 4}, {"integrity": 3, "trauma": 2, "lives_saved": 1}),
    O("I called, and the duty nurse took forty minutes. The man didn't wait. It was the first time I understood how thin the whole thing is.", {"stress": 14, "happiness": -8}, {"trauma": 14})),
  role=G, cooldown=14)

E("g.family", "🏠", "What you bring home",
  "Your partner says it quietly, at breakfast, over a cooling cup of tea. 'You've changed.' It's not an accusation. It's more like a doctor reading a chart.",
  ["partner", "trauma>=30"],
  C("Talk about it",
    O("I told her about the man in cell nineteen. I told her about the sound. I had never said it aloud. She held my hand across the table, and we sat there until the tea was cold.", {"stress": -8, "happiness": 4}, {"trauma": -8}),
    O("I told her some of it. Not all. She heard the rest in the pauses. It was the first night in a year I slept through.", {"stress": -6, "happiness": 3}, {"trauma": -6})),
  C("Say you're fine",
    O("I said I was fine. She said 'OK'. She said it in the way people say OK when it isn't. A year later she said it again, and I knew it was the last time.", {"stress": 4, "happiness": -3}, {"trauma": 3}),
    O("I said it was only work. She nodded. It was a lie, and she knew, and we both agreed to live with it.", {"stress": 3}, {"trauma": 2})),
  C("Take leave",
    O("I booked two weeks. We went to the coast. For the first three days I woke at 5.40. On the fourth, I slept till nine.", {"happiness": 6, "stress": -10}, {"trauma": -12, "merit": -1}),
    O("I took a week. I came back with a tan and a sense of how long it had been since I'd noticed the weather.", {"happiness": 4, "stress": -6}, {"trauma": -8})),
  role=G, cooldown=12)
