from prison_lib import *

# ====================================================================== prisoner: more of the life
E("p.gang_order", "🎯", "A name and an instruction",
  "The man I answer to hands me a name on a scrap of paper, folded small. 'Before the end of the month,' he says. 'You'll know how.' It is somebody I've eaten next to for a year.",
  ["gang", "served>=2"],
  C("Do it",
    O("I did it in the stairwell at the change of shift. It took eleven seconds and it will take the rest of my life. I was promoted that week. I don't recommend it.", {"stress": 16, "happiness": -10, "karma": -12}, {"gang_rank": 1, "respect": 10, "heat": 20, "rep": {"mine": 15}, "sentence": 4}),
    O("I did a version of it. I broke an arm and a rib, and I made sure he was not killed. The gang was satisfied. The man I'd hurt never spoke to me again.", {"stress": 12, "karma": -8}, {"respect": 6, "heat": 14, "rep": {"mine": 8}})),
  C("Refuse",
    O("I handed the paper back. 'I can't,' I said. He looked at me for a very long time. 'Then you can't be here,' he said. I was out within the week, and in danger for a year.", {"stress": 14, "karma": 6}, {"gang": "", "respect": -12, "rep": {"mine": -40}, "attack": 1}),
    O("I told him no. It was a bad week. I took two beatings from men I'd called friends. But I kept the thing I would have lost otherwise.", {"stress": 12, "karma": 6, "health": -6}, {"gang_rank": -1, "respect": -4, "rep": {"mine": -20}})),
  C("Warn the target",
    O("I gave him a look and a sentence in the mess hall. He understood. Within a week he'd asked to be moved to protective custody. The gang wondered, and I wondered if they'd guessed.", {"stress": 12, "karma": 5}, {"respect": -2, "heat": 6, "rep": {"mine": -8}}),
    O("I warned him, and it was not enough. He was hurt badly by somebody else. I was never sure whether I'd made it worse.", {"stress": 14, "karma": -2}, {"respect": 0, "heat": 8})),
  cooldown=14)

E("p.hole", "🕳️", "After the hole",
  "I've been out of segregation for eleven days. I'm doing the things a person does: eating, walking, talking. They don't feel like mine. When an officer speaks to me, I take half a second to answer.",
  ["solitary_before"],
  C("Take it slowly",
    O("I made myself do one thing a day, and no more. A walk. A page. A conversation about nothing. In six weeks I was almost a person.", {"stress": -6, "happiness": 3}, {"conduct": 2}),
    O("I lay on my bunk and looked at the ceiling. It was a good ceiling. I learned to love the ceiling again, slowly.", {"stress": -4}, {})),
  C("Ask for the counsellor",
    O("A tired woman with a mug and a notebook. She listened, and nodded. 'It's very common,' she said. I'd never been so glad to be common.", {"stress": -8, "happiness": 4}, {"program": "therapy", "conduct": 3, "parole_mood": 3}),
    O("She had a waiting list. I was seen in March. I told her about the hole. She wrote it down, and thanked me. It was something.", {"stress": -4}, {"conduct": 2})),
  C("Throw yourself into something",
    O("I joined the workshop and worked twelve hours a day for a month. I built a table. It was a very good table. I slept for the first time in a year.", {"stress": -4, "smarts": 1}, {"conduct": 3}),
    O("I took up the gym and ran in place. My body hardened. My mind, slowly, caught up.", {"stress": -3, "health": 3}, {"respect": 2})),
  cooldown=14)

E("p.funeral", "⚰️", "The form",
  "The chaplain brings the news and the form. My mother died on Tuesday. The form is a request for 'compassionate temporary release', escorted, for the funeral. There's a box for my reasons, and it is three lines long.",
  ["bereaved>=1", "served>=1"],
  C("Fill it in properly",
    O("I filled it in in my best handwriting. The answer came back in four days: approved, with two officers and cuffs. I stood at the back of the church. My sister couldn't look at me. I didn't blame her.", {"stress": 10, "happiness": -8}, {"support": 4, "conduct": 2}),
    O("I wrote what I felt, in three lines. It was denied: 'security considerations'. I stood at the cell window at eleven o'clock and watched the sky.", {"stress": 12, "happiness": -10}, {"support": -4})),
  C("Don't ask",
    O("I couldn't bear the cuffs in the church. I stayed in my cell, and had my own service, in my head, and counted the hymns. A man on the landing slid a card under my door.", {"stress": 10, "happiness": -8}, {"support": -3}),
    O("I didn't ask. I told myself it was for her sake. It was for mine.", {"stress": 8, "happiness": -8}, {"support": -4})),
  C("Write the eulogy to be read",
    O("I wrote it over three nights. A cousin read it aloud. She told me afterwards that the church was silent. It was the best thing I've ever written, and I'd give it all not to have written it.", {"stress": 8, "happiness": -4}, {"support": 8}),
    O("I wrote it, and the chaplain posted it. It was read out between the second hymn and the third. I'm told that people wept.", {"stress": 8, "happiness": -4}, {"support": 6})),
  cooldown=30)

E("p.parole_prep", "⚖️", "Before the board",
  "The hearing is in nine days. There is a statement to write, a lawyer's letter to chase, an officer who may or may not give a reference. In the library, a man with experience tells you the thing nobody tells you: the board decides in the first four minutes.",
  ["hearing_due"],
  C("Write it honestly",
    O("It took me a week. I wrote what I'd done and what I thought about it. I wrote that I didn't deserve to be forgiven, and that I hoped to deserve to be trusted. I read it out to a mirror.", {"stress": 8, "karma": 3}, {"parole_mood": 10}),
    O("I wrote what I felt, in plain words. My chaplain read it and cried. 'Say it exactly like that,' he said.", {"stress": 6, "karma": 3}, {"parole_mood": 8})),
  C("Write what the board wants to hear",
    O("I wrote it carefully, with a vocabulary I'd gathered from the other men's statements. It was a competent document. It had no heart at all, and the board will know.", {"stress": 6}, {"parole_mood": 3}),
    O("I wrote what they wanted. It read like a leaflet. I have never felt so much like a fraud, and it's probably the most useful thing I'll ever write.", {"stress": 6}, {"parole_mood": 4})),
  C("Ask an officer for a reference",
    O("{off.first} said yes, then no, then yes. The letter was two lines. It said I'd been 'no trouble'. It's a very good letter.", {"stress": 4}, {"parole_mood": 8, "conduct": 2}),
    O("I asked {off.first}. He looked at me for a long time. 'I'd like to,' he said. 'I'll see what I can write.' It was a good letter.", {"stress": 4}, {"parole_mood": 9, "conduct": 2})),
  roles=OFF, cooldown=3)

E("p.denied", "🚪", "Not this time",
  "The envelope is thin. I know before I open it. 'Parole is denied.' There are three paragraphs of reasons and a date for the next review, and a sentence at the bottom that says I may appeal.",
  ["denied>=1", "served>=3"],
  C("Throw yourself into the next year",
    O("I enrolled on two courses. I took the library job. I wrote to my daughter every week. I made myself a plan and followed it. By the next hearing, I'd become a different person, or so the file said.", {"stress": 4, "smarts": 2}, {"conduct": 6, "parole_mood": 6, "program": "ged"}),
    O("I worked. I did every programme they'd put in front of me. When the next hearing came, the file was twice as thick.", {"stress": 4}, {"conduct": 5, "parole_mood": 5})),
  C("Break down",
    O("It took me three weeks. I stopped eating and talking and answering the officers. A counsellor was called. I was put on observation. It was the lowest point of the sentence, and it ended, as these things do, without ceremony.", {"stress": 14, "happiness": -12}, {"conduct": -4, "heat": 6}),
    O("I wept. I punched a wall. I got a week in the hole for the wall. The wall did not seem to mind.", {"stress": 12, "happiness": -10, "health": -3}, {"conduct": -5, "heat": 10})),
  C("Plan to leave without permission",
    O("I thought about it for the first time as a real thing, in the dark, in a cell. I said it to nobody. But the idea sat there, and grew.", {"stress": 6}, {"escape": 0, "intel": ["rumour", "The perimeter at night, as seen from the yard"]}),
    O("I stopped believing in the board. Not all at once, but with a quiet finality. I began to count the fence posts.", {"stress": 6, "happiness": -4}, {"intel": ["patrol", "The tower's rhythm at the change"]})),
  cooldown=10)

E("p.recant", "📞", "A witness remembers",
  "The call comes through the prison's legal-visits line. The investigator at the clinic sounds out of breath. 'One of the witnesses from your trial has been found. She wants to talk. She says she was pressured, and she's not sure of what she saw.'",
  ["inno", "appeal>=30", "served>=3"],
  C("Fund the investigation",
    O("It cost every cent I had. The investigator travelled to three states. The witness signed a statement in front of a notary. It's on a form with a stamp on it. It's real.", {"stress": 6, "happiness": 8, "money": -400}, {"appeal": 25, "intel": ["case", "A witness who recants"]}),
    O("I paid for the travel. It was the best money I've ever spent. The statement was short, and it had four sentences that I'd waited nine years to hear.", {"stress": 6, "happiness": 8, "money": -300}, {"appeal": 22})),
  C("Wait for the clinic",
    O("I waited. The clinic took four months to get to it. The witness had changed her mind again by then.", {"stress": 8, "happiness": -4}, {"appeal": 8}),
    O("I waited. It was slow, but it was thorough, and when it came it was solid.", {"stress": 6}, {"appeal": 18})),
  C("Meet her",
    O("They let her come to the legal-visits room. We sat across a table. She looked at me for a long time. 'I'm sorry,' she said. 'I was twenty. I thought they knew.' I didn't say anything for a minute.", {"stress": 12, "happiness": 4, "karma": 4}, {"appeal": 25, "intel": ["case", "A witness who recants"]}),
    O("We met. She was nervous and kind. She apologised in a way that could have been a script and wasn't. The statement was signed by the end of the hour.", {"stress": 10, "happiness": 4}, {"appeal": 22})),
  cooldown=40, once=True)

E("p.hunger", "🍽️", "A hunger strike",
  "The food has been getting worse for months, then worse again. On Monday, forty men on Block B refuse their trays. By Wednesday, it's two hundred. They are looking at the rest of us.",
  ["budget<=45", "tension>=40"],
  C("Join them",
    O("I put my tray down untouched. By Friday I was dizzy. By Sunday I was lying on the bunk, in a quiet, bright place. The warden came on the seventh day with a list of concessions. It was a small victory, and I ate a slice of bread like a feast.", {"health": -8, "stress": 6, "happiness": 2}, {"respect": 8, "heat": 10, "tension": -12, "budget": 6}),
    O("I joined. It's a stupid, wonderful thing to do. They fed us properly for three months afterwards, and then it slid.", {"health": -6, "stress": 4}, {"respect": 6, "heat": 8, "tension": -8, "budget": 4})),
  C("Eat your tray",
    O("I ate. It was bad, and I ate it, in front of them. I didn't think about it much at the time. I thought about it for years.", {"stress": 6}, {"respect": -6, "conduct": 2}),
    O("I ate my meal and said nothing. A man on the next table threw a roll at me. It was a gentle gesture, by the standards of the place.", {"stress": 5}, {"respect": -4, "conduct": 1})),
  C("Help organise it",
    O("I drew up the list of demands: food, medical, the roof. I got it to the warden through a chaplain. It was read, and it was acted on. Not enough, but acted on.", {"stress": 8, "karma": 3}, {"respect": 10, "heat": 12, "tension": -10, "budget": 8}),
    O("I wrote the demands in my best handwriting. I got three days in the hole as a ringleader. When I came out, the food was better.", {"stress": 8, "karma": 3}, {"respect": 12, "heat": 18, "tension": -8, "budget": 6, "solitary": 1})),
  cooldown=24)

E("p.talent", "🎤", "The talent show",
  "Once a year the chaplain organises a show in the chapel. It's the only night the wings mix. A man I don't know is about to sing, and someone is looking at me and saying, 'You should do something.'",
  ["served>=2"],
  C("Take the stage",
    O("I did a poem I'd written, standing in the glare of a lamp. There was a silence, and then a sound I hadn't heard in years: the sound of two hundred men clapping because they wanted to.", {"happiness": 10, "stress": -8}, {"respect": 4, "conduct": 2}),
    O("I sang. I'm no singer. But I sang my mother's song, and the room joined in on the second verse, and for a minute it wasn't a prison.", {"happiness": 9, "stress": -8}, {"respect": 4})),
  C("Help from the wings",
    O("I did the lights and the chairs and the tea. A man cried at the end, and I held the door for him. It was the best night of the year.", {"happiness": 6, "stress": -5}, {"conduct": 2}),
    O("I helped set up. I saw things from behind the curtain that I'd never have seen from the floor: how scared people are before they perform.", {"happiness": 5}, {"conduct": 2})),
  C("Stay in your cell",
    O("I stayed in. The sound of the clapping came through the vents. I told myself it was nothing to do with me.", {"stress": 2, "happiness": -2}, {}),
    O("I stayed away. The next day, a man who'd been there told me what I'd missed. He was kind about it.", {"happiness": -1}, {})),
  cooldown=14)

E("p.kid_visit", "👧", "The first visit",
  "She was two when I came in. She is eleven now, and she's sitting across a table from me with a bag of crisps and a face that is a mixture of my mother's and her mother's. 'Hi,' she says. 'Mum says you're my dad.'",
  ["kids", "support>=30", "served>=5"],
  C("Tell her the truth",
    O("I told her what I did. I used the plainest words. She asked three questions, and the third was 'Are you sorry?'. I said yes. She nodded, and ate a crisp. We've written ever since.", {"happiness": 6, "stress": 6, "karma": 4}, {"support": 12}),
    O("I told her some of it. The rest I'll tell her when she's older. She said, 'OK,' and asked about my cell. It was the first normal conversation I'd had in years.", {"happiness": 6, "stress": 4}, {"support": 10})),
  C("Tell her it was a mistake",
    O("I said it had all been a mistake. She looked at me for a long moment. She is very like her mother. 'That's what they all say,' she said. I've thought about that sentence for years.", {"happiness": -2, "stress": 8}, {"support": 2}),
    O("I told her. She was kind enough to believe me. I felt like a thief.", {"happiness": 2, "stress": 6}, {"support": 4})),
  C("Make it about her",
    O("I asked about school. About her friends. About the dog. She talked for forty minutes, and I listened, and it was the best forty minutes of my life.", {"happiness": 8, "stress": -4}, {"support": 14}),
    O("I asked her everything. She answered everything. At the end, she hugged me over the table, the guard looking away. I'll never forget the smell of her hair.", {"happiness": 9, "stress": -4}, {"support": 14})),
  cooldown=40, once=True)

E("p.divorce", "📄", "The papers",
  "An envelope from a solicitor arrives with a window in it and my name typed on the front. It has a form and a pen and a note that says I need not attend. The date on the last page is three weeks ago.",
  ["partner", "served>=3", "support<=60"],
  C("Sign",
    O("I signed. I did it in the visiting room, with a pen the officer lent me, and I gave the form back and said thank you. I went to the yard and walked round it four times.", {"happiness": -12, "stress": 8}, {"support": -12}),
    O("I signed it that night. It took me two hours to find the right way to hold the pen. I slept on the floor.", {"happiness": -12, "stress": 8}, {"support": -12})),
  C("Contest",
    O("I wrote a letter. I said what I felt, in four pages. She replied with one: 'I've waited as long as I can.' I signed the next day.", {"happiness": -8, "stress": 8}, {"support": -6}),
    O("I contested it for a year. It wasn't about the marriage. It was about being asked.", {"happiness": -6, "stress": 8}, {"support": -8})),
  C("Ask for one more visit",
    O("She came. We sat there. We said nothing that mattered and everything that did. 'I'm sorry,' she said. 'So am I,' I said. And it was over.", {"happiness": -4, "stress": 6}, {"support": 0}),
    O("She wouldn't. I understood. I signed the form and gave it back.", {"happiness": -8, "stress": 6}, {"support": -10})),
  cooldown=40, once=True)

E("p.five_years", "🪞", "Five years",
  "Today is the anniversary. Nobody mentions it. I mention it to nobody. I stand at the window with my forehead on the cool glass and try to remember the person who walked in.",
  ["served>=5"],
  C("Take stock",
    O("I made a list of what I'd done: what I'd learned, who I'd lost, who I'd met. It was longer than I expected. I put it in the Bible.", {"happiness": 3, "stress": -4}, {"conduct": 2}),
    O("I counted the good things. There were four. I counted the bad. There were seventy. I put the paper away and began again the next morning.", {"stress": 2}, {})),
  C("Mark it",
    O("I wrote a letter to myself in five years' time, and gave it to the chaplain. He promised to keep it. He has.", {"happiness": 3}, {"parole_mood": 2}),
    O("I made a mark on the wall, by the bed, with a pin. There are other marks. I'm not the first.", {"happiness": 0}, {})),
  C("Pretend it's another day",
    O("I did the day as usual. I ate and worked and slept. In the evening a man I barely knew put a biscuit on my bunk and left without a word.", {"happiness": 3}, {"respect": 1}),
    O("I did the day as usual. It's the best way, I think.", {"stress": 1}, {})),
  cooldown=40, once=True)

E("p.last_year", "🔑", "The last year",
  "There are twelve months left. It's strange how heavy they are. A man in the next cell has stopped sleeping. Another has started to cry at nothing. The closer the gate, the louder the walls.",
  ["remaining<=1", "served>=3"],
  C("Prepare",
    O("I started a list: a room, a job, a bank account. I wrote to a hostel. I asked the chaplain to find me a name. By the last month I had something I'd almost call a plan.", {"stress": 4, "happiness": 3}, {"conduct": 3, "parole_mood": 2}),
    O("I did the programmes the staff recommended: the resettlement course, the job club. A woman from a charity said she'd meet me at the gate. I didn't believe her until she did.", {"stress": 3, "happiness": 3}, {"conduct": 3})),
  C("Panic",
    O("I did something stupid. I broke a rule I'd never broken before, for no reason at all, and was put on report. It isn't uncommon. It's the building saying goodbye.", {"stress": 8}, {"heat": 10, "conduct": -6}),
    O("I did nothing at all for six months. I lay on the bunk. A friend took me by the hand and walked me round the yard, and said, 'You're going to be fine.' He was wrong. But he was kind.", {"stress": 6, "happiness": -3}, {})),
  C("Say goodbye",
    O("I spent the last weeks saying goodbye to every person I had met. It was an exhausting, joyful, ridiculous kind of tour.", {"happiness": 4}, {"respect": 2}),
    O("I gave away my things: the radio, the books, the plastic mug. I kept the picture. On the last night I wrote down every name I could remember.", {"happiness": 4}, {"respect": 2})),
  cooldown=40, once=True)

# ====================================================================== the plan
E("p.crew_wavers", "😰", "Cold feet",
  "One of the crew is not sleeping. In the exercise yard {c.first} keeps looking at the fence and then at his feet. When he sees me, he starts, as if I'd come up behind him.",
  ["crew", "plan"],
  C("Reassure him",
    O("I took him aside and told him the whole thing, again, step by step. By the end he was nodding. I couldn't tell if I'd calmed him or if I'd made it worse.", {"stress": 6}, {"escape": 0, "respect": 2}),
    O("I told him what it would be like on the other side. His eyes filled. 'I want to see my kids,' he said. 'So do I,' I said.", {"stress": 6, "happiness": 2}, {"respect": 2})),
  C("Cut him loose",
    O("I told him he was out. He took it badly. For a week he stared at me across the mess hall, and I watched my own back.", {"stress": 10}, {"crew": 0, "heat": 4, "respect": -2}),
    O("I told him he was out, and I told the others why. It was necessary, and I felt like a bastard, and a week later there was a message under my door that said 'thanks'.", {"stress": 8}, {"respect": 2})),
  C("Make sure he can't talk",
    O("I made it clear to him what would happen if he did. I did it with a calm voice and an open face, and he understood. I didn't like what I'd become.", {"stress": 10, "karma": -6}, {"respect": 4, "heat": 6}),
    O("I had a friend of mine speak to him. He was very persuasive. The man did not speak to anyone for a month.", {"stress": 8, "karma": -4}, {"respect": 2, "heat": 4})),
  roles=CELL, cooldown=8)

E("p.insider_wants", "🗝️", "More than we agreed",
  "The man on the inside has asked for more. It's a message in a library book: the original price plus half again, and a favour I don't understand. 'Things have got harder,' he says. They always have.",
  ["plan", "escape>=3"],
  C("Pay it",
    O("I paid. I sold everything I could sell and borrowed the rest. He took it with a calm face. I did not feel the plan was safer, only dearer.", {"stress": 8, "money": -500}, {"dues": 20}),
    O("I paid. The price of a thing like this has no ceiling. It's the one law I'm sure of.", {"stress": 8, "money": -400}, {"dues": 15})),
  C("Refuse",
    O("I told him no. For a week I heard nothing at all. Then a note said 'OK', and nothing more. I don't know if it's good news.", {"stress": 10}, {"escape": -1}),
    O("I said no. He said he'd think about it. The silence that followed felt like a decision.", {"stress": 10}, {})),
  C("Tell him I know about him",
    O("I let him know that I knew what he was. He went pale. 'There's no need for that,' he said. It worked. It also taught him exactly how I'd behave if it went wrong.", {"stress": 8}, {"heat": 8, "intel": ["weakness", "A bent officer in debt"]}),
    O("I let him know what I could say. It was a threat, and a bad one. He paid it back in kind, within the week.", {"stress": 12}, {"heat": 14, "attack": 1})),
  cooldown=10)

E("p.plan_rumour", "👂", "People are talking",
  "A man I barely know stops me on the stairs. 'I hear you've got something planned,' he says, pleasantly, as though he were asking about the football. He looks at the wall behind me and says, 'Just so you know.'",
  ["plan"],
  C("Deny everything",
    O("I said it was nonsense. I said it in a flat voice. He nodded, and smiled, and walked on. A day later the whole of my landing was in a particular kind of silence.", {"stress": 10}, {"heat": 6}),
    O("I laughed. It was a poor laugh. He laughed too. We both knew.", {"stress": 8}, {"heat": 4})),
  C("Make him a partner",
    O("I brought him in. He was clever, and useful, and a liability. But a man who knows is safest when he's inside.", {"stress": 8}, {"crew": 1, "respect": 2}),
    O("I told him I'd think about it. A week later I added him to the crew, with some misgivings. They were justified.", {"stress": 8}, {"crew": 1})),
  C("Shut him up",
    O("I paid him in tobacco. He took it. He didn't say another word about the plan, but he looked at me differently ever after.", {"stress": 6}, {"dues": 10, "heat": -2}),
    O("I did what had to be done. I'm not going to describe it. I'd call it a cost.", {"stress": 12, "karma": -10}, {"heat": 14, "respect": 4})),
  cooldown=10)

# ====================================================================== on the run
E("pf.knock", "🚪", "A knock on the door",
  "A knock on the door at nine in the evening. Two knocks, a pause, a third. It isn't the landlady's. I stand with my back to the wall and my hand on the back of a chair, and I don't breathe.",
  ["fugitive"],
  C("Don't answer",
    O("I stood there for a quarter of an hour. The knock came again, once, and then footsteps going away. In the morning there was a leaflet for a pizza place on the mat.", {"stress": 8}, {"heat": -4}),
    O("I waited. They went away. I never found out who they were. I moved the next day.", {"stress": 10}, {"heat": -6})),
  C("Open it on the chain",
    O("A woman from the flat below, with a parcel that had been left with her. She smiled and said 'Hello, neighbour' and went away. I had to sit down.", {"stress": 6, "happiness": 2}, {"heat": -2}),
    O("A young man with a clipboard, from the council, wanting to ask if I was on the electoral roll. I said I wasn't. He wrote it down. I moved the next day.", {"stress": 8}, {"heat": 6})),
  C("Go out the back",
    O("I was over the wall and into the lane before the second knock. I walked until it got light. It was a false alarm. I moved on anyway.", {"stress": 8}, {"heat": -6}),
    O("I went out the back and into the arms of a cat, a dustbin and a lot of mud. It wasn't dignified. It was safe.", {"stress": 8}, {"heat": -4})),
  role="prisoner", cooldown=6)

E("pf.recognised", "👁️", "Someone looked twice",
  "In a corner shop a woman looks at me, then at the rack of newspapers, and then at me again. She doesn't say anything. She is holding a loaf of bread, and she hasn't moved.",
  ["fugitive"],
  C("Leave calmly",
    O("I put down my basket and walked out. I walked for an hour in a loop, and then another hour in a different loop, and got home by a route no one could follow. I do not know whether she called.", {"stress": 10}, {"heat": 8}),
    O("I left without hurry. In the mirror of a parked car I saw her at the window. She was on the phone.", {"stress": 12}, {"heat": 12})),
  C("Talk to her",
    O("I said, 'I know what you're thinking.' She said, 'I think you're a man who looks like someone I saw on the news.' I said 'People tell me that.' She smiled, and bought her bread, and I walked out.", {"stress": 8}, {"heat": 2}),
    O("I told her something close to the truth. She listened. She said, 'I won't say anything,' and she didn't. I'll never know why.", {"stress": 8, "happiness": 3}, {"heat": 0})),
  C("Move on that night",
    O("I was on a bus by midnight. I changed again at dawn. By the time anyone looked, I was in another county.", {"stress": 8}, {"heat": -10}),
    O("I left that night, with a rucksack and no plan. It was the wrong thing and I knew it, and the right thing too.", {"stress": 10}, {"heat": -8})),
  role="prisoner", cooldown=6)

E("pf.old_friend", "🤝", "A voice from before",
  "The phone in the hall rings and rings. On the eleventh I pick it up and say nothing. 'It's me,' says a voice I have known for twenty years. 'I know where you are. I'm not going to say.'",
  ["fugitive", "support>=20"],
  C("Hear them out",
    O("We talked for an hour. They told me about everyone. They told me the investigators had been, twice. They said they hadn't said a word. I believed them, and that was the only thing in the world I did.", {"happiness": 8, "stress": 4}, {"support": 10, "heat": 10}),
    O("They told me to run. They told me the name of a person in another city. I wrote it on my hand.", {"happiness": 5, "stress": 6}, {"support": 8, "heat": 6, "pay": 400})),
  C("Hang up",
    O("I hung up. They called back four times. I did not answer. I moved the next day.", {"happiness": -6, "stress": 8}, {"support": -4, "heat": -6}),
    O("I hung up, and cried for an hour. I could not afford to be found, even by someone who loved me.", {"happiness": -8, "stress": 8}, {"support": -4, "heat": -8})),
  C("Ask for money",
    O("They sent what they had, in an envelope with no return address. It was a lot. It was too much. I knew I'd regret it.", {"stress": 6}, {"pay": 1200, "heat": 14, "support": 4}),
    O("They sent a few hundred. It came to a poste restante. I checked it three times before I collected it.", {"stress": 6}, {"pay": 500, "heat": 8})),
  role="prisoner", cooldown=8)

# ====================================================================== guard: more of the job
E("g.informant", "🤫", "A tip",
  "An inmate stops me at the end of the landing and speaks without moving his lips. 'Boss. Friday. The laundry. That's all I'll say.' He is already walking away.",
  ["served>=2"],
  C("Act on it at once",
    O("I searched the laundry that night with two officers. We found a stash: tools, a phone, a very long length of cord. It was the second-best catch of my year. The inmate who gave me the tip got a better cell.", {"stress": 6}, {"merit": 5, "control": 4, "commend": 1, "intel": ["plan", "A stash in the laundry"]}),
    O("I acted on it. We found something, though it wasn't what I expected. It was a lot of cigarettes and a note that said 'Nice try'. He had been playing a game.", {"stress": 6}, {"merit": 2, "control": 2})),
  C("Wait and watch",
    O("I waited and watched. On Friday I saw exactly what he'd meant. A parcel changed hands in the laundry. I let it go, to see where it went. It went to a man I hadn't suspected.", {"stress": 8, "smarts": 1}, {"merit": 5, "intel": ["plan", "A handover route through the laundry"]}),
    O("I waited. Nothing happened on Friday. On Saturday, a man was found with a broken arm in the laundry. I was told, afterwards, that I should have acted.", {"stress": 8}, {"merit": -2, "trauma": 4})),
  C("Ignore it",
    O("I ignored it. On Friday, in the laundry, a man was stabbed. It's in the file as an unforeseeable incident. I've never been able to accept that.", {"stress": 14, "happiness": -6, "karma": -4}, {"trauma": 10, "merit": -3, "incident": 1}),
    O("I ignored it. Nothing happened. I'll never know whether that's luck, or whether he was lying.", {"stress": 4}, {})),
  role="guard", roles=INM, cooldown=10)

E("g.old_inmate", "🧓", "The man who is going home",
  "{i.first} has been on my wing for nine years. He is leaving on Friday. He asks if I'd shake his hand. It's against a number of rules.",
  ["served>=5"],
  C("Shake his hand",
    O("I shook it. His hand was dry and small and warm. 'Look after the young ones,' he said. I said I'd try. I've never forgotten the way he said it.", {"happiness": 5, "stress": -2}, {"integrity": 3, "ia_heat": 2}),
    O("I shook it, in the corridor, behind the door, where no camera could see. He cried, and so did I, and we both pretended not to.", {"happiness": 6}, {"integrity": 3})),
  C("Keep to the rules",
    O("I said, 'Good luck.' He nodded. I watched him go through the gate, small and grey, with a plastic bag. I felt like a clerk.", {"stress": 4, "happiness": -2}, {}),
    O("I kept to the rules. He understood. He walked out with his head up. It was a good dignity, and I took none of it.", {"stress": 3}, {"integrity": 1})),
  C("Give him your number",
    O("I wrote it on the back of a bus ticket. It was the worst possible idea. He called me from a payphone six years later, and said, 'I wanted to say thanks.' He'd opened a garage.", {"happiness": 6, "stress": 4}, {"integrity": -3, "ia_heat": 8, "corruption": 0}),
    O("I gave him a number. I regretted it every day for a month. Then I forgot. Then he called, a year later, from a pub, drunk and happy.", {"happiness": 5, "stress": 4}, {"integrity": -3, "ia_heat": 6})),
  role="guard", roles=INM, cooldown=14)

E("g.drone", "🛸", "Over the wall",
  "A small black drone is crossing the yard at dusk, trailing something. The tower shouts. It drops a package behind the workshop and rises over the wire. There's a man at the window of Block D with his hand over his mouth.",
  ["served>=2"],
  C("Recover the package",
    O("We found it in four minutes. Phones, drugs, a razor. The investigation took six months and led nowhere. The drone is in a glass cabinet in the staff room now.", {"stress": 6}, {"merit": 4, "control": 3, "incident": 1}),
    O("I got there first. There were three phones, a bag of white powder and an envelope with my name on it. I will not say who it was from.", {"stress": 10}, {"merit": 2, "integrity": -2, "ia_heat": 6, "incident": 1})),
  C("Let it lie",
    O("I let the package lie. Someone else would pick it up. I had a wife and mortgage and I didn't want the paperwork. A week later, a man on Block D had a phone.", {"stress": 6}, {"integrity": -3, "control": -3}),
    O("I looked away. It's a decision I make about twice a year. It's never the right one and it's never the wrong one.", {"stress": 6}, {"integrity": -4})),
  C("Take a share",
    O("I took a phone. It was the most expensive thing I ever bought. I was never discovered, but I walked the landing for a year afraid of the sound of my own keys.", {"stress": 10, "money": 300}, {"corruption": 1, "integrity": -10, "ia_heat": 8}),
    O("I took a share. I took it quietly and I told no one. I've never forgiven myself, and I've never been found out.", {"stress": 8, "money": 300}, {"corruption": 1, "integrity": -10, "ia_heat": 8})),
  role="guard", cooldown=14)

E("g.strike", "✊", "Walk out",
  "The union has called a walk-out. The government has called it illegal. On the wing, the inmates have heard, and the building has the particular hush of a place that's wondering what you'll do.",
  ["union>=40", "budget<=55"],
  C("Walk out",
    O("I walked out with forty others. We stood at the gate in the rain with banners. The press came. The government blinked, eventually, and we got six more officers. I got a letter on my file and a story to tell.", {"stress": 8, "happiness": 4}, {"union": 12, "standing": -4, "merit": -2, "budget": 8}),
    O("I walked out. It lasted three days. We got a promise and a pay rise of two per cent. Two officers lost their jobs. I've never been sure if it was worth it.", {"stress": 10}, {"union": 10, "merit": -3, "budget": 6})),
  C("Cross the line",
    O("I crossed the picket. A colleague spat at my feet. I was thanked by the governor and avoided by the staff room for three years.", {"stress": 10, "happiness": -4}, {"union": -20, "standing": -4, "merit": 3}),
    O("I went in. I told myself it was for the inmates. It was partly true. It was also partly for the pension.", {"stress": 10}, {"union": -15, "merit": 3})),
  C("Call in sick",
    O("I stayed at home. It was a quiet, cowardly sort of solidarity. Nobody blamed me, and nobody thanked me.", {"stress": 4}, {"union": 2}),
    O("I called in sick, and spent three days in the garden. For the first time in eight years I heard the birds.", {"stress": -4, "happiness": 3}, {"union": 2, "merit": -1})),
  role="guard", cooldown=20)

E("g.lawsuit", "⚖️", "Served",
  "A process server finds me in the car park and hands me a thick envelope. An inmate has sued me, personally, in federal court. He says I denied him medical treatment on a night in October. I remember that night. I remember it very well.",
  ["served>=4", "incidents>=1"],
  C("Fight it",
    O("I hired a lawyer. The case took two years. In the end, the judge found for me on every count. I felt neither relief nor vindication. I'd have paid the man to say sorry.", {"stress": 12, "money": -2000}, {"ia_heat": 2, "union": 4}),
    O("I fought it. The union paid. We won. The inmate was sent a letter, and wrote back, and I read it at my kitchen table for an hour.", {"stress": 10}, {"union": 6, "standing": -2})),
  C("Settle quietly",
    O("It was settled for a sum I would have found unspeakable a year before. The lawyer said it was the clever thing. I felt that it was a confession.", {"stress": 8, "money": -3000}, {"integrity": -1, "ia_heat": -2}),
    O("I settled. The sum was a year's salary. It bought silence, and I paid the price of knowing what it was for.", {"stress": 8, "money": -4000}, {"integrity": -1})),
  C("Tell the truth in court",
    O("I took the stand. I said what had happened, including the part that wasn't in the report. The jury was out for forty minutes. They found against me. I was not surprised, and I was oddly relieved.", {"stress": 14, "karma": 6, "money": -5000}, {"integrity": 8, "standing": -3, "ia_heat": 6}),
    O("I told the truth. It cost me the case and a year of my life. Afterwards, the inmate came up and shook my hand in the corridor of the court. I've never understood why.", {"stress": 12, "karma": 6, "money": -4000}, {"integrity": 7, "standing": -2})),
  role="guard", cooldown=40, once=True)

E("g.kid_asks", "🧒", "What do you do at work",
  "My daughter's school has a 'what our parents do' week. She's asked me three times what to say. I've said 'public service'. She says that's not an answer. Tonight she says: 'Do you hurt people, Dad?'",
  ["served>=4", "kids"],
  C("Tell her the truth",
    O("I sat on the edge of her bed and told her. I told her that the people I look after have done bad things, that some of them are very sad, and that my job is to keep everyone safe. She asked if I was scared. I said sometimes.", {"stress": -4, "happiness": 4}, {"trauma": -4}),
    O("I told her. She listened with great seriousness. 'I'll tell them you keep people safe,' she said. I was far too moved to answer.", {"stress": -4, "happiness": 5}, {"trauma": -4})),
  C("Change the subject",
    O("I changed the subject. She noticed. She always does. She told her class I worked in an office, and the teacher, who knew, said nothing.", {"stress": 2}, {"trauma": 2}),
    O("I told her it was boring, grown-up stuff. She sighed, and drew a picture of me in a cap. It looked like an airline pilot.", {"stress": 1}, {})),
  C("Show her the keys",
    O("I let her hold them, in the kitchen. She weighed them in both hands. 'They're heavy,' she said. 'Yes,' I said. It's the best thing I've ever said about the job.", {"stress": -3, "happiness": 4}, {"trauma": -3}),
    O("I showed her the keys, and she hung them on the doorknob and said they were the best keys in the world. I've never forgotten.", {"stress": -3, "happiness": 4}, {"trauma": -3})),
  role="guard", cooldown=30, once=True)

E("g.retire_dinner", "🍽️", "The dinner",
  "They hold the retirement dinner on a Thursday in a function room above a pub. There is a cake in the shape of a set of keys. The speech is shorter than it should be, and several people say my name wrong. I find that I'm not sure what I feel.",
  ["served>=20"],
  C("Make a speech",
    O("I stood, and said thirty years in a sentence, and everyone laughed at the right place. Then I said something true, and the room went quiet. I thanked the ones who weren't there to hear it.", {"happiness": 6, "stress": -4}, {"standing": 4}),
    O("I made a short speech. I thanked the night staff. I thanked the inmates, which no one had expected. The room clapped for a long time.", {"happiness": 5, "stress": -4}, {"standing": 3})),
  C("Slip out early",
    O("I left after the cake. In the car park I sat in my car and did nothing for twenty minutes. I wasn't sad, exactly. I was waiting for something to stop.", {"stress": 2}, {}),
    O("I went home before the speeches. My wife said nothing and made a cup of tea.", {"stress": -1}, {})),
  C("Sit with the ones who stayed",
    O("I sat with five officers, from the years before, and we talked about the dead and the dying and the ones who got away. It was the best evening I've had in twenty years.", {"happiness": 7, "stress": -6}, {"union": 4}),
    O("I sat with the old team. We told each other the stories. They got bigger and funnier. By midnight we were laughing about things that had made us weep.", {"happiness": 7, "stress": -6}, {"union": 4})),
  role="guard", cooldown=40, once=True)
