from prison_lib import *

# ====================================================================== SET PIECE: the riot (prisoner)
T("pr.riot.1", "🔥", "It starts",
  "It starts with a sound that doesn't belong: a tray, thrown. Then another, and a roar, and a banging along the whole length of the landing. The lights flicker. Somewhere below, a door gives. Every man in the building understands, at the same instant, that tonight is different.",
  C("Go to the front",
    O("I ran with them. It's a thing that happens in the legs. The corridor was a river of men, and I was in it, and for the first time in years I was part of something larger than my own fear.", {"stress": 12, "happiness": 3}, {"respect": 8, "heat": 20, "riot": 1, "then": "pr.riot.2a"}),
    O("I went to the front and found a place at the edge of the front. The feeling was that of being a very small part of a very large decision.", {"stress": 12}, {"respect": 6, "heat": 18, "riot": 1, "then": "pr.riot.2a"})),
  C("Lock myself in and stay down",
    O("I pulled the mattress over me and put my back against the wall. The noise went on for hours. I counted the bangs. By dawn, I'd lost count, and the door had held.", {"stress": 14}, {"riot": 1, "then": "pr.riot.2b"}),
    O("I stayed in my cell and listened. A man I didn't know was crying for his mother. I couldn't help him. I've thought about it since.", {"stress": 14, "karma": -2}, {"riot": 1, "then": "pr.riot.2b"})),
  C("Get the vulnerable out",
    O("I found three of them in the laundry, the youngest and the oldest and one who'd been in solitary. I got them up the back stairs to the chapel and bolted the door. We spent the night praying to a God none of us knew.", {"stress": 14, "karma": 8}, {"respect": 4, "riot": 1, "then": "pr.riot.2c"}),
    O("I went along the landing opening doors for the ones who couldn't. Some wouldn't leave. Some wouldn't stop thanking me. Nobody touched us.", {"stress": 14, "karma": 7}, {"respect": 5, "riot": 1, "then": "pr.riot.2c"})),
  C("Use the confusion",
    O("A riot is a hole in the map. I went for the laundry stairs, with my head down, through the one door I knew would be open. It wasn't. I was at the wire before I knew what I'd done.", {"stress": 16}, {"escape": 0, "riot": 1, "then": "pr.riot.2d"}),
    O("I used the chaos to get to the records office. I took a file. It was mine. I read it by torchlight, and what it said I will not repeat.", {"stress": 10}, {"appeal": 6, "intel": ["case", "My original file, read in the riot"], "riot": 1, "then": "pr.riot.2d"})))

T("pr.riot.2a", "🔥", "The landing",
  "The landing is a bonfire of mattresses, a storm of shouting, a dozen men with whatever they could find. Somewhere behind them are the officers, and a line of shields, and the sound of canisters. Someone hands you a pipe.",
  C("Take it and hold the line",
    O("I took it. I stood where I was told. A canister landed ten feet away, and I was coughing and blinded and holding a pipe, and an officer I had never seen came through the smoke with a baton. I do not remember much after that.", {"health": -10, "stress": 14}, {"respect": 8, "heat": 15, "attack": 1, "then": "pr.riot.3"}),
    O("I took it and stood at the back. When the line broke, I ran. I got as far as the stairs.", {"stress": 14}, {"respect": 4, "heat": 12, "then": "pr.riot.3"})),
  C("Put it down and slip away",
    O("I put it down on the floor, politely, as though I'd been handed a cup of tea, and walked into a side corridor. Nobody stopped me. I was in my cell, with my back against the door, before the lights went out.", {"stress": 10}, {"respect": -5, "heat": 8, "then": "pr.riot.3"}),
    O("I put it down. A man next to me noticed, and said nothing. Later he came to my cell and said, 'You did right.' It was a strange benediction.", {"stress": 10}, {"respect": -2, "then": "pr.riot.3"})),
  C("Talk to the officers through the smoke",
    O("I shouted. I said there were men who wanted to give up. An officer I knew by sight stopped, raised a hand, and the line paused. A dozen of us walked out of the smoke with our hands on our heads.", {"stress": 14, "karma": 4}, {"respect": -6, "conduct": 8, "heat": -5, "then": "pr.riot.3"}),
    O("I tried to talk. Nobody heard. I was hit by a thrown bottle and dragged out by two men I had never met. I was grateful, and so were they.", {"health": -6, "stress": 14}, {"respect": 2, "then": "pr.riot.3"})))

T("pr.riot.2b", "🔥", "The night in the cell",
  "The cell door holds. The noise doesn't stop. At two in the morning a face appears at the hatch: a man from the next landing, bloodied, asking to be let in. He can't be. He's holding a blade.",
  C("Let him in",
    O("I let him in. He sat on the floor and shook. He'd done something that night he couldn't undo. We said nothing for three hours. In the morning I told the officers he'd been with me all night. It was a lie. He's still alive.", {"stress": 14, "karma": -2}, {"respect": 4, "then": "pr.riot.3"}),
    O("I let him in. He gave me the blade. I threw it out of the hatch. I never learned what he'd done with the other one.", {"stress": 14}, {"respect": 3, "heat": 4, "then": "pr.riot.3"})),
  C("Keep the door shut",
    O("I kept it shut. He banged on it for a long time. Then he stopped. I don't know what became of him. I've decided I don't want to know.", {"stress": 16, "happiness": -6, "karma": -6}, {"then": "pr.riot.3"}),
    O("I shut the hatch. He shouted my name through it. It was the loneliest few minutes I've ever spent.", {"stress": 14, "happiness": -4, "karma": -5}, {"then": "pr.riot.3"})),
  C("Shout for the officers",
    O("I shouted. An officer came, and the man ran, and the officer thanked me through the hatch, in a voice that was almost kind. I was a snitch from that moment, in the eyes of the landing.", {"stress": 10}, {"conduct": 6, "respect": -10, "then": "pr.riot.3"}),
    O("I called out. The man was grabbed and dragged away, struggling. I watched through the gap. I felt both vindicated and sick.", {"stress": 12}, {"conduct": 4, "respect": -8, "then": "pr.riot.3"})))

T("pr.riot.2c", "🕯️", "The chapel",
  "The chapel door is held shut with a pew. There are four of us on the floor, and one of them is bleeding from the scalp. Outside, someone is trying the handle, patiently, as a man tries the handle of his own front door.",
  C("Open it",
    O("It was an old man with a bible and a bruise. He sat down among us. We shared a bar of chocolate, and a prayer none of us really meant, and it was as holy a night as any I've known.", {"stress": 6, "happiness": 4, "karma": 4}, {"respect": 3, "then": "pr.riot.3"}),
    O("It was a man with a pipe. He looked at the four of us on the floor, and the bleeding one, and lowered it. 'Not in here,' he said, and left. I will remember that sentence.", {"stress": 10, "karma": 3}, {"respect": 4, "then": "pr.riot.3"})),
  C("Hold the door",
    O("We held it. We held it for six hours. Whoever it was gave up. It was, I think, the hardest I've worked at anything, and I never saw what I was working against.", {"stress": 12}, {"respect": 4, "then": "pr.riot.3"}),
    O("I held it with my back and my feet. At dawn there was a silence, and a gentle knock, and a voice that said, 'Officers.' I wept.", {"stress": 12, "happiness": 4}, {"respect": 3, "then": "pr.riot.3"})),
  C("Pray",
    O("I prayed. I don't know to whom. It was the first prayer I'd said since childhood. It wasn't answered, but it didn't need to be.", {"stress": -2, "karma": 2}, {"then": "pr.riot.3"}),
    O("I prayed with them. The bleeding one was a believer. He thanked me in the morning. I said I hadn't done anything. 'Yes you did,' he said.", {"stress": 2, "karma": 3}, {"then": "pr.riot.3"})))

T("pr.riot.2d", "🌫️", "The wire",
  "The wire is a long way off in the dark, and above it the floodlights make a bright rectangle in the wet. A figure is running toward the fence from the other side of the yard. An officer in the tower has seen him.",
  C("Run for it",
    O("I ran. There's a point where a body knows more than the mind does. The light caught me when I was twenty feet from the fence. I stopped and lay down. They were very calm.", {"stress": 16, "health": -4}, {"respect": 6, "heat": 25, "solitary": 1, "sentence": 1, "then": "pr.riot.3"}),
    O("I ran, and I got to the fence, and I got a hand on it. I felt the old fear come up, and I let go. I'm not sure whether it was cowardice.", {"stress": 16}, {"heat": 14, "respect": 2, "then": "pr.riot.3"})),
  C("Go back to the cell",
    O("I walked back through the smoke with my head down and lay on the bunk. It was the right decision, and nobody can tell me otherwise.", {"stress": 8}, {"then": "pr.riot.3"}),
    O("I went back, and I regretted it for eleven years.", {"stress": 8, "happiness": -3}, {"then": "pr.riot.3"})),
  C("Help the one who's running",
    O("I shouted a direction. He turned. He was a boy, and he vanished into the dark. I never found out. I told nobody.", {"stress": 10, "karma": 3}, {"respect": 5, "heat": 10, "then": "pr.riot.3"}),
    O("I went to him. He was already on the ground. An officer reached us at the same time. He was hurt but not badly. I stayed with him until the medics arrived.", {"stress": 12, "karma": 6}, {"respect": 3, "then": "pr.riot.3"})))

T("pr.riot.3", "🌅", "The morning after",
  "At dawn the building is quiet in a way I have never heard. The yard is full of smoke. A man in a suit is walking from cell to cell with a clipboard, asking each of us what we saw.",
  C("Say I saw nothing",
    O("I said it a hundred times that day, in the same words. A man in the next cell was removed in the afternoon, and I never saw him again. Nobody spoke to me for a fortnight.", {"stress": 10}, {"respect": 4, "heat": 6, "tension": -20}),
    O("I said I'd been in my cell. The investigator wrote it down and smiled, and I understood that he'd known the answer already.", {"stress": 8}, {"respect": 2, "tension": -20})),
  C("Tell them what happened",
    O("I told him. I told him the names. I told him everything I'd seen, and it was an inventory of the worst night of my life. I was moved to a different wing that afternoon, with an escort.", {"stress": 14, "karma": 3}, {"conduct": 10, "respect": -25, "tension": -20, "heat": -10}),
    O("I told him about the ones who'd been hurt. I didn't give a name that I didn't have to. It's a fine line, and I walked it, and I don't know where it led.", {"stress": 10, "karma": 4}, {"conduct": 5, "respect": -6, "tension": -20})),
  C("Blame the officers",
    O("I said what the building had done to us. I said it in a measured voice. He wrote it all down, and I was told later that the report used my words. The warden was gone within the year.", {"stress": 8, "karma": 3}, {"respect": 8, "heat": 8, "tension": -20, "order": -8}),
    O("I told him it was inevitable. He agreed, quietly. He said that was the problem.", {"stress": 6}, {"respect": 4, "tension": -20})))

# ====================================================================== SET PIECE: the riot (guard)
T("gd.riot.1", "🔥", "The alarm",
  "The alarm is a sound I've heard in drills a hundred times and never once like this. On the monitors, Block C is moving as one body. The wing sergeant's voice on the radio is thin. 'All available. All available. This is not a drill.'",
  C("Go to the line",
    O("I ran. I was in the second rank at the stairwell with a shield and a baton and a radio shouting my number. The first rush hit and held, and it was an animal sound, and it was terrifying. I have never been so clear.", {"stress": 14}, {"control": 4, "incident": 1, "riot": 1, "then": "gd.riot.2a"}),
    O("I went to the line. We held the stairwell. Behind me an officer was shouting commands in a voice I'd never heard her use. I held until the cry came to fall back.", {"stress": 14}, {"control": 4, "incident": 1, "riot": 1, "then": "gd.riot.2a"})),
  C("Fall back to the control room",
    O("I locked the control-room door behind me, as I'd been trained. On the monitors I watched my colleagues fall back in order. Nobody blamed me. I blamed me.", {"stress": 12, "happiness": -4}, {"control": -3, "incident": 1, "riot": 1, "then": "gd.riot.2b"}),
    O("I went to the control room. I did my job there, on the radio, directing the response. It was necessary. It did not feel like it was.", {"stress": 10}, {"control": 0, "merit": 2, "incident": 1, "riot": 1, "then": "gd.riot.2b"})),
  C("Go back for the officer who is cut off",
    O("{co.first} was on Block C when it went. I went in against the order, through the side stairs, with a master key. I found {co.him} in a cell with the door jammed. We came out together.", {"stress": 16, "health": -6}, {"control": 4, "commend": 1, "incident": 1, "lives_saved": 1, "union": 10, "riot": 1, "then": "gd.riot.2c"}),
    O("I went in for {co.first}. We got out, both of us, with scrapes. I was written up for leaving my post and commended for the same act on the same day.", {"stress": 16, "health": -4}, {"control": 4, "commend": 1, "incident": 1, "lives_saved": 1, "union": 8, "standing": -2, "riot": 1, "then": "gd.riot.2c"})),
  roles=COG, role="guard")

T("gd.riot.2a", "🛡️", "Holding",
  "The line has been holding for an hour. The inmates are throwing everything they have: trays, pipes, burning bedding. Behind us the response team is gearing up. The supervisor asks if you can hold another ten minutes.",
  C("Hold",
    O("We held. It was seventeen minutes in the end. Someone near me went down, and someone else stepped in, and the rank closed. When the team came through, they were met by a silence and a wall of shields and a line of spent men.", {"stress": 14, "health": -5}, {"control": 4, "merit": 4, "trauma": 6, "commend": 1}),
    O("I held, with the rest. It was the worst quarter of an hour of my life and also the most certain.", {"stress": 14, "health": -4}, {"control": 5, "merit": 4, "trauma": 6})),
  C("Pull back for a breather",
    O("We pulled back a few steps and a gap opened. Three men came through it. They were stopped. It was close, and nobody was hurt, and the supervisor said nothing.", {"stress": 10}, {"control": -2, "trauma": 4}),
    O("We withdrew in order. It was the right tactic, and it gave the inmates a yard of ground they didn't need to have.", {"stress": 10}, {"control": -3, "trauma": 3})),
  C("Try to talk to them",
    O("I shouted over the noise, using a name. A man at the front stopped. He looked at me for a long moment, raised a hand and sat down in the middle of the stairwell. Eight others followed.", {"stress": 12, "karma": 4}, {"control": 6, "integrity": 3, "merit": 5, "trauma": 4, "commend": 1}),
    O("I tried. No one heard. A pipe hit my shield. The man who threw it later told me he was sorry.", {"stress": 12}, {"control": 2, "trauma": 6})), role="guard")
T("gd.riot.2b", "📡", "The control room",
  "The monitors show everything, in grey. On one, a group of inmates has taken three officers hostage on the second landing. On another, a fire is spreading in the laundry. The warden asks you what the priority should be.",
  C("The hostages",
    O("I sent the response team to the second landing. The fire spread. It was put out two hours later, with the loss of the laundry and a lot of paperwork. All three officers were recovered, bruised and alive.", {"stress": 12}, {"merit": 6, "control": 3, "commend": 1, "lives_saved": 3}),
    O("I sent them for the hostages. We lost the laundry. We saved the officers. In the report, it said 'appropriate prioritisation', and I could not eat for two days.", {"stress": 12}, {"merit": 6, "control": 3, "lives_saved": 3})),
  C("The fire",
    O("I sent the fire team first. It was put out in twenty minutes. The hostages were released by the inmates, who, having made their point, were hungry. It could have gone the other way.", {"stress": 14}, {"merit": 2, "trauma": 4}),
    O("I sent them for the fire. When they reached the second landing, one of the officers had been badly hurt. I will think about that for a long time.", {"stress": 16, "happiness": -6}, {"merit": -2, "trauma": 10})),
  C("Split the team",
    O("I split them. Half to the fire, half to the hostages. It was a gamble. Both worked. It's the closest I've ever come to being right by luck.", {"stress": 12}, {"merit": 7, "control": 4}),
    O("I split the team. Both missions failed to the degree they were underpowered. It was a lesson in a particular kind of arithmetic.", {"stress": 14}, {"merit": 1, "trauma": 6})), role="guard")
T("gd.riot.2c", "🩸", "The cut-off wing",
  "You and your colleague are in a stairwell on Block C with a cell door that won't open and a crowd of angry men coming up from below. {co.first} is bleeding from a gash above the eye. There is a window.",
  C("Go through the window",
    O("It was a thirty-foot drop to the roof of the kitchen. We made it. {co.first} landed badly. We crawled along the roof to the next block and in through a skylight. It's the stupidest thing I've ever done and I'd do it again.", {"stress": 14, "health": -8}, {"control": 2, "merit": 3, "union": 6}),
    O("I got us out through the window, onto the roof. We sat there, in the dark and the smoke, till the response team arrived. {co.first} held my hand. Neither of us has ever mentioned it.", {"stress": 12, "health": -4}, {"union": 6, "merit": 3})),
  C("Stay and fight it out",
    O("We stood in the stairwell, back to back, and held it for twenty minutes. Nobody got past. It was a victory of a kind. We both had to be stitched.", {"stress": 14, "health": -10}, {"control": 4, "merit": 4, "union": 6, "commend": 1}),
    O("We fought. I'm not proud of it. I did what I had to. I saw faces I knew, and I saw them see me.", {"stress": 16, "health": -8, "karma": -3}, {"control": 4, "trauma": 8, "union": 6})),
  C("Talk to them",
    O("An inmate named {i.first} came up the stairs first, and he knew me. He stopped the others. 'Not these two,' he said. I will remember that for the rest of my career, and I will never know why.", {"stress": 10, "karma": 4}, {"integrity": 4, "control": 6, "merit": 4, "lives_saved": 1}),
    O("I talked. It worked, partly. It bought us enough time for the team to arrive. The man who stood closest to me spat on the floor.", {"stress": 12}, {"control": 3, "merit": 3})),
  roles={"co": {"relation": "co_guard"}, "i": {"relation": "inmate"}}, role="guard")

T("gd.riot.3", "📝", "The inquiry",
  "The riot lasted nineteen hours. The damage is estimated at four million. The review board has set up in the staff canteen with a flipchart and a very large pot of coffee. They would like your account.",
  C("Give your honest account",
    O("I told it plainly. I said what I'd seen and what I'd done. The panel wrote it all down. A line in the report says 'a clear and credible officer'. I'll take that.", {"stress": 8}, {"integrity": 4, "merit": 4, "ia_heat": -4}),
    O("I told them everything I'd seen. It included things I wasn't supposed to say. The report was a lot more critical than the one before it. The warden's replacement is grateful.", {"stress": 10, "karma": 3}, {"integrity": 5, "standing": -2, "union": -3, "budget": 5})),
  C("Stick to the official line",
    O("I said what everyone said. The board nodded. It was the sort of account that closes a file. A month later I was commended for my 'steady conduct'.", {"stress": 6}, {"merit": 2, "integrity": -2, "union": 4}),
    O("I said what the briefing said. It was true, and it wasn't the truth, and I knew the difference.", {"stress": 6}, {"integrity": -3, "union": 3})),
  C("Blame the budget",
    O("I told them it had been coming for years. I listed the vacancies, the locks, the staffing levels. It was all in a report I'd read in March. They looked at me with real alarm.", {"stress": 8}, {"budget": 8, "standing": -3, "union": 6}),
    O("I said it was the cuts. They wrote that down, and the next year, a few of the cuts were reversed. It's the nearest I've come to changing something.", {"stress": 6}, {"budget": 6, "union": 5})), role="guard")

# ====================================================================== hostage, war, lockdown, warden
E("g.hostage.1", "🧷", "Cell fourteen",
  "At 2.15 an inmate in cell fourteen has taken a nurse. He has a sharpened toothbrush against her neck. The wing is quiet in a way I haven't heard in years. The specialist team is forty minutes away. You are the nearest officer with training.",
  ["served>=2"],
  C("Talk him down",
    O("I sat on the floor outside his door and used the voice. I said his name. I said I would listen. I listened for forty minutes.", {"stress": 14},
      {"then": "gd.hostage.talk"}),
    O("I sat on the floor, and I asked him what he needed. He said he needed to speak to his daughter. The next forty minutes were the longest of my life.", {"stress": 14},
      {"then": "gd.hostage.talk"})),
  C("Rush him",
    O("I went in with two others. It was a bad idea executed well. The nurse was uninjured. The man was injured, badly, and it is in the report that the force was necessary. I do not look at the report.", {"stress": 16, "health": -4}, {"control": 4, "merit": 3, "force_bad": 1, "ia_heat": 8, "incident": 1, "lives_saved": 1}),
    O("I went in. The nurse was cut. She lived. She never spoke to me again, and I understood.", {"stress": 18, "happiness": -8, "health": -4}, {"control": 2, "trauma": 12, "incident": 1})),
  C("Wait for the team",
    O("I held the corridor and waited. Forty minutes is a very long time. The nurse was brought out by the team. She was unharmed. I was the one who needed to sit down.", {"stress": 12}, {"control": 2, "merit": 2, "incident": 1, "lives_saved": 1}),
    O("I waited. The team arrived late. The nurse had been cut by then. 'You did what the procedure said,' someone told me. It didn't help.", {"stress": 16, "happiness": -6}, {"trauma": 8, "incident": 1})),
  role="guard", weight=0.5, cooldown=30)

T("gd.hostage.talk", "🗣️", "Talk him down",
  "He says nothing for a minute, and then, in a flat voice, he starts to talk. What he says will tell you what he needs.",
  C("Take the conversation seriously",
    O("It is a long conversation.", {"stress": 6},
      {"flag": "talked"},
      play={"id": "pr_standoff", "kind": "pr_branch", "params": {"skill": 60, "difficulty": 1.0}, "need": 0.55,
            "win": {"icon": "🕊️", "title": "He put it down", "text": "He opened the door at 3.04 with the toothbrush in his open hand and his other hand over his face. The nurse walked out. He said, 'Is that it?' I said it was. We stood there in a pool of light, the two of us.", "effects": {"happiness": 6, "karma": 6, "stress": -4}, "pr": {"merit": 8, "control": 4, "commend": 1, "lives_saved": 1, "incident": 1, "integrity": 3}},
            "lose": {"icon": "🩸", "title": "It broke", "text": "It went wrong at the end, over a word. He pressed. The nurse cried out. We went in. It was messy and fast and when it was over there was a cut and a ruined cell and a hush. She lived.", "effects": {"stress": 14, "happiness": -6}, "pr": {"control": -2, "trauma": 10, "incident": 1}}}),
    O("I took it seriously. It went the way these things go.", {"stress": 6}, {"flag": "talked"},
      play={"id": "pr_standoff", "kind": "pr_branch", "params": {"skill": 55, "difficulty": 1.1}, "need": 0.55,
            "win": {"icon": "🕊️", "title": "He put it down", "text": "It took until dawn. When he opened the door, he asked for the chaplain. The nurse was unharmed. I was told afterwards that I'd saved a life. I thought only of the man.", "effects": {"happiness": 6, "karma": 6, "stress": -4}, "pr": {"merit": 8, "control": 4, "commend": 1, "lives_saved": 1, "incident": 1, "integrity": 3}},
            "lose": {"icon": "🩸", "title": "It broke", "text": "He stopped listening at 3.40. The team arrived late. It was bad. The report says 'a tragic outcome', which is the sort of sentence you read for years.", "effects": {"stress": 14, "happiness": -6}, "pr": {"control": -2, "trauma": 10, "incident": 1}}})),
  C("Mention what he wants",
    O("I said I could get his daughter on the phone. I wasn't sure I could. He said, 'Do it.' I got her.", {"stress": 8}, {"flag": "talked"},
      play={"id": "pr_standoff", "kind": "pr_branch", "params": {"skill": 60, "difficulty": 0.9}, "need": 0.4,
            "win": {"icon": "📞", "title": "A phone call", "text": "A child's voice came through the speaker in the corridor. It was all it took. He sat down, very slowly, and put the toothbrush on the floor. I've never known a quieter minute.", "effects": {"happiness": 6, "karma": 6, "stress": -4}, "pr": {"merit": 8, "control": 4, "commend": 1, "lives_saved": 1, "incident": 1, "integrity": 3}},
            "lose": {"icon": "🩸", "title": "She didn't answer", "text": "The phone rang out. He heard it ring. I watched the thing go out of his face.", "effects": {"stress": 14, "happiness": -6}, "pr": {"control": -2, "trauma": 10, "incident": 1}}}),
    O("I promised it. It was a risk. I got the call made.", {"stress": 8}, {"flag": "talked"},
      play={"id": "pr_standoff", "kind": "pr_branch", "params": {"skill": 60, "difficulty": 1.0}, "need": 0.45,
            "win": {"icon": "📞", "title": "A phone call", "text": "It was the right instinct. The call, the voice, the sitting-down. I filled in the paperwork, afterwards, with my hand shaking.", "effects": {"happiness": 6, "karma": 6, "stress": -4}, "pr": {"merit": 8, "control": 4, "commend": 1, "lives_saved": 1, "incident": 1, "integrity": 3}},
            "lose": {"icon": "🩸", "title": "Too late", "text": "I couldn't reach her. He saw me with the phone, and read it on my face. It was over quickly after that.", "effects": {"stress": 14, "happiness": -6}, "pr": {"control": -2, "trauma": 10, "incident": 1}}})),
  C("Stay silent and let him talk",
    O("I said almost nothing. A man who hasn't been heard for a year will talk if you give him the silence. It took two hours. When he stopped, he put down the toothbrush.", {"stress": 8, "karma": 4}, {"flag": "talked"},
      play={"id": "pr_standoff", "kind": "pr_branch", "params": {"skill": 65, "difficulty": 0.9}, "need": 0.35,
            "win": {"icon": "🕊️", "title": "Heard", "text": "He talked until his voice failed. Then he opened the door and sat down. It was the longest silence I ever kept, and the best.", "effects": {"happiness": 6, "karma": 6, "stress": -4}, "pr": {"merit": 8, "control": 4, "commend": 1, "lives_saved": 1, "incident": 1, "integrity": 3}},
            "lose": {"icon": "🩸", "title": "Not enough", "text": "Silence isn't always a gift. He read mine as contempt, and acted. The rest is in a report.", "effects": {"stress": 14, "happiness": -6}, "pr": {"control": -2, "trauma": 10, "incident": 1}}}),
    O("I listened. He cried, and then he shouted, and then he cried again. I held the line.", {"stress": 8}, {"flag": "talked"},
      play={"id": "pr_standoff", "kind": "pr_branch", "params": {"skill": 55, "difficulty": 1.0}, "need": 0.4,
            "win": {"icon": "🕊️", "title": "Heard", "text": "He put it down. I put out a hand and he took it. It was not in any procedure.", "effects": {"happiness": 6, "karma": 6, "stress": -4}, "pr": {"merit": 8, "control": 4, "commend": 1, "lives_saved": 1, "incident": 1, "integrity": 3}},
            "lose": {"icon": "🩸", "title": "Not enough", "text": "It wasn't enough. I'll never know what would have been.", "effects": {"stress": 14, "happiness": -6}, "pr": {"control": -2, "trauma": 10, "incident": 1}}})),
  C("Let the team handle it from here",
    O("I stood down. The team arrived within a quarter of an hour. It was over in four minutes, and I stood in the corridor and watched my hands.", {"stress": 8}, {"flag": "talked"}),
    O("I handed it over. It was the right call. It didn't feel like a call I'd made.", {"stress": 8}, {"flag": "talked"})),
  role="guard")

E("p.hostage", "🧷", "In the yard",
  "A man on the landing above has taken an officer. I can see him from the yard: a blade, an arm round a neck, a crowd gathering. The officer is a man I've never liked. His eyes find mine.",
  ["served>=2", "tension>=50"],
  C("Try to help the officer",
    O("I shouted up. I said the man's name. He looked down. I said, 'You don't want this.' Somehow it worked. The officer was released with a bruise, and I was beaten up by my own side that evening.", {"stress": 14, "karma": 6}, {"conduct": 10, "respect": -12, "heat": -5}),
    O("I walked up the stairs with my hands open. I talked to him for twenty minutes. He gave up the blade. It's the nearest I've come to being a hero, and it cost me everything I had on the landing.", {"stress": 14, "karma": 7}, {"conduct": 12, "respect": -15, "heat": -8})),
  C("Stay out of it",
    O("I watched. Everyone watched. It ended without me, with a team and a lot of noise. The officer lived. I felt nothing, and then I felt it later.", {"stress": 8}, {"respect": 2}),
    O("I stayed where I was. It was over in an hour. The officer never forgot who watched.", {"stress": 8}, {"heat": 4})),
  C("Encourage him",
    O("I shouted nothing, but I was seen not to. Whatever happened, I'd be remembered on one side or the other.", {"stress": 8, "karma": -5}, {"respect": 6, "heat": 10}),
    O("I yelled with the crowd. It was an ugly thing to do. The officer was hurt, not badly. I got three days in the hole for it, and a name I'd rather not have.", {"stress": 10, "karma": -8}, {"respect": 8, "heat": 15})),
  weight=0.5, cooldown=30)

E("pg.war", "⚔️", "The war",
  "Two gangs have fallen out. It began with a card game and a remark, and by Thursday it's a policy. Every landing is divided. The mess hall is a map of who is allowed to sit where.",
  ["war"],
  C("Stay out of it",
    O("I stayed in my cell, ate in my cell and spoke to no one. A war is a thing that happens to other people for as long as it can.", {"stress": 6}, {"respect": -2, "heat": -3}),
    O("I kept to myself. Two men on my landing were hurt. Neither of them was me. I know how fragile that is.", {"stress": 8}, {"respect": -1})),
  C("Pick a side",
    O("I picked the side with the cleaner hands. It turned out they had none. But I belonged, and belonging in a war is warm.", {"stress": 8}, {"respect": 6, "heat": 8, "rep": {"mine": 10}}),
    O("I went in with my own gang. It's what we're for. Two weeks, four injuries, one death. The war ended with a handshake.", {"stress": 12, "karma": -4}, {"respect": 8, "heat": 12, "attack": 1})),
  C("Try to broker peace",
    O("I talked to both sides. It took weeks, and a lot of tobacco. The war cooled. I was not thanked, but I was remembered by both.", {"stress": 10, "karma": 4}, {"respect": 8, "tension": -10, "heat": 4}),
    O("I tried. They laughed, politely, and then someone sent a message that I should mind my own business. I did. I'd learned something.", {"stress": 8}, {"respect": 2, "heat": 5})),
  cooldown=12)

E("gg.war", "⚔️", "A war on the wings",
  "Two gangs have fallen out, and it is spreading. There have been three assaults in a week. On the staff side, the question is who to move, who to lock down and who to leave alone.",
  ["war"],
  C("Lock down the troublemakers",
    O("I recommended a targeted lockdown. It worked, in the short term. The target wings were furious. For two months, every inmate on those landings looked at me as if I owed them.", {"stress": 8}, {"control": 5, "merit": 4, "tension": -8, "standing": -2}),
    O("I recommended it. The warden agreed. It cost us a month of good will, and it prevented, I think, a death.", {"stress": 8}, {"control": 4, "merit": 4, "tension": -8})),
  C("Talk to the senior men",
    O("I went to see the shot-callers on each side. I did it alone, without a radio. I said what I'd seen. I said that if it went on, we would all lose. They heard it. It went quiet for a year.", {"stress": 10, "karma": 3}, {"control": 6, "integrity": -2, "tension": -12, "merit": 5}),
    O("I talked to them, and made a few promises I could not keep. It bought us six months. I've never been entirely sure what I traded for it.", {"stress": 10}, {"control": 5, "integrity": -4, "tension": -10, "merit": 3, "corruption": 1})),
  C("Let it play out",
    O("I looked the other way. Four men were hurt. One of them was a man I'd been trying to help. I wrote it up as 'inmate-on-inmate violence', which is a phrase that does a lot of work.", {"stress": 10, "karma": -5}, {"control": -4, "trauma": 6, "tension": 6}),
    O("I did nothing, and the war burned itself out in three weeks. A man died. It is in the file as an incident, and it is in me as something else.", {"stress": 12, "karma": -6}, {"control": -4, "trauma": 8, "tension": 4})),
  role="guard", cooldown=12)

E("pg.warden", "🏛️", "A new warden",
  "A new warden has been appointed. At the first staff meeting, she says three things in a quiet voice: that things will change, that she does not intend to be liked, and that she has read every file in the building.",
  [],
  C("Wait and see",
    O("I waited. Within six months, the changes were real: the lockdowns were shorter, the visits longer, a new rec yard planned. The building began, almost imperceptibly, to loosen.", {"stress": -2}, {"order": 4, "tension": -6}),
    O("I waited. Within six months it was clear that she was the real thing. A building can take years to know that.", {"stress": -2}, {"order": 6, "tension": -6})),
  C("Test her",
    O("I tested her. She was exactly as she'd said. It cost me a month of suspicion and gained me a strange sort of respect.", {"stress": 6}, {"order": 0, "heat": 4}),
    O("I tested her, and she saw it, and she wasn't offended. She asked for my opinion on the east landing. It was the first time a warden had.", {"stress": 4}, {"order": 4})),
  C("Plan around her",
    O("I took the long view. A new warden is a new regime, and a new regime is a new chance. I adjusted my plans.", {"stress": 4}, {"intel": ["warden", "A new regime: shorter lockdowns, longer visits"]}),
    O("I planned around her. If she was reformist, there'd be slack. If she was strict, there'd be gaps. Either way, I'd be ready.", {"stress": 4}, {"intel": ["warden", "A new regime"]})),
  role=["prisoner", "guard"], not_tags=["fugitive"], cooldown=30)
