#!/usr/bin/env python3
"""Authored setting scenes and conservative availability annotations.
No runtime keyword substitution: reviewable year gates live on each event.
"""
import json,re
from pathlib import Path
R=Path(__file__).resolve().parents[2]
events=[]
def scene(key,path,title,text,options,era=None,career=None):
    cond={'age':[12,2000],'life':path}
    if era: cond['context']={'timeline':str(era)}
    if career: cond['career']=career
    choices=[]
    for label,good,bad in options:
        fx={'happiness':3,'stress':2}
        if career: fx['skill']=2
        choices.append({'label':label,'outcomes':[{'weight':2,'text':good,'effects':fx},{'weight':1,'text':bad,'effects':{'happiness':-2,'stress':4}}]})
    events.append({'id':'setting.'+key,'icon':'⌛' if era else '📖','title':title,'text':text,'conditions':cond,'themes':['setting',career or path],'weight':8,'cooldown':12,'choices':choices})
TIMES={
1850:[('telegram','A message priced by the word','The telegraph office will transmit a family message, but each extra word costs money. You need to explain something delicate.','Choose the essential words','A carefully shortened message reached its destination intact.','The recipient misunderstood the one detail I had cut.','Send a longer letter','My letter arrived with enough context to be understood.','By the time the letter arrived, the decision had already been made.','Wait for someone travelling there','A traveller delivered it in person and brought news back.','The traveller changed their route; the message stayed in a coat pocket.'),
('rail','The station that might change the town','A proposed railway promises work and easier journeys. Its route would cut through a neighbour’s land.','Listen to the affected households','The meeting produced a safer crossing and an amended route.','The company heard us out, then laid the original route anyway.','Ask about the new work','I learned what the job involved before making promises.','The promised work was shorter and harder than the notice suggested.','Keep clear of the argument','I kept my routine while the town changed around me.','I discovered too late that my own route had disappeared.'),
('pump','The water everyone shares','Several households fall ill after drawing from the same street pump. Certainty is scarce; the queue still forms.','Seek another water source','We carried clean water farther and helped a frail neighbour.','The extra journey exhausted us and did not answer every question.','Tell the local physician what I noticed','My account gave the physician a pattern worth investigating.','The physician dismissed the pattern; I still had to choose where to drink.','Follow the ordinary routine','Nothing happened to me, though the worry stayed.','I fell ill and regretted treating familiarity as evidence.')],
1920:[('radio','A room listening together','A neighbour has assembled a wireless set. The signal fades just as the evening programme begins.','Help adjust the aerial','A clearer signal turned the room into a small shared celebration.','We chased interference through the whole evening.','Bring a story of my own','When the signal faded, my story kept the room listening.','My story met polite silence and a request to try the dial again.','Listen from the doorway','I enjoyed the programme without taking over the gathering.','The crowded doorway made me feel more outside than I expected.'),
('car','A motorcar on a narrow street','A motorcar breaks down where carts and pedestrians need to pass. Its owner is embarrassed and impatient.','Help push it clear','We freed the street before anybody had to raise their voice.','Moving it took more effort than the owner admitted.','Fetch someone who repairs engines','A mechanic found the fault and taught me what to look for.','The mechanic could not get a replacement part that week.','Wait for the street to clear','The delay became a conversation with someone I had never met.','I missed the appointment I thought could wait.'),
('hall','The music through the hall door','A local dance hall has a new band. A friend wants company, though tomorrow’s work starts early.','Go and leave at a sensible hour','We caught the best set and still made the morning.','One more tune became a very short night.','Find a quieter table','I heard the music and a friend’s news without shouting.','Every table was full; the quiet plan lasted minutes.','Invite them another evening','We made a plan neither of us had to rush.','They went without me, and our next plan never quite happened.')],
1970:[('cassette','A recording nobody labelled','A friend lends you a cassette with a handwritten track list. One song sounds like somebody from your town.','Find out who made it','I found a local musician and a reason to attend their next show.','The trail ended at another unlabelled copy.','Make a copy to share','A carefully made copy started a new conversation between friends.','The tape tangled halfway through the song everyone wanted.','Return it with a note','My note mattered more to my friend than I expected.','I returned it before listening to the last side.'),
('fuel','The queue at the fuel station','A supply interruption has made fuel uncertain. People trade rumours while the queue barely moves.','Arrange a shared journey','We used less fuel and discovered a route that worked.','The shared timetable clashed with everyone’s shifts.','Ask for reliable information','The station gave me a realistic time to return.','The delivery was delayed again after I had rearranged the day.','Keep my usual journey','I arrived on time because the queue finally moved.','I spent the morning waiting and still left without enough fuel.'),
('payphone','Coins for one more call','You need to reach someone from a public telephone. Your change will not buy a long conversation.','Explain the important part first','They understood what mattered before the coins ran out.','The line cut off before I heard their answer.','Ask someone nearby for change','A small kindness bought enough time to sort things out.','Nobody had the right coins, and the shop was closing.','Arrange to meet in person','The conversation was easier when we could see each other.','I waited at the wrong entrance with no easy way to call.')]
}
for era,rows in TIMES.items():
 for key,title,text,*x in rows: scene(str(era)+'.'+key,'traveler',title,text,[x[i:i+3] for i in range(0,9,3)],era)
PATHS={
'pirate':[('chart','A coast missing from the chart','The lookout sees rocks where the chart promises deep water. The tide is turning.','Heave to and sound the water','A patient approach saved the hull and corrected our chart.','The delay let another ship reach the anchorage first.','Trust the lookout and change course','We cleared the reef and the lookout earned the crew’s trust.','The safer course led into weather nobody had seen.','Follow the chart','We found a narrow passage and came through.','The keel struck; repairs consumed the next voyage’s time.')],
'colonist':[('air','The seal that will not stay quiet','A habitat air sensor keeps reporting a slow leak. The patch held yesterday; it has not held tonight.','Isolate the section and check every seal','We found the damaged gasket before the reserve became critical.','The search used up a shift and delayed essential maintenance elsewhere.','Ask another shift for a second diagnosis','A fresh pair of eyes found the fault our routine had missed.','The second diagnosis contradicted the first; we had to test both.','Keep watch and wait for morning','The readings stabilised and we repaired it in daylight.','The alarm worsened during the night and nobody slept.')],
'royal':[('petition','The petition beyond the gates','A household affected by an official decision asks to be heard. Advisers prefer a ceremonial answer.','Hear the household’s account','A specific injustice became harder for the court to ignore.','My interest raised expectations I could not fulfil alone.','Ask for an independent review','The review found a practical correction without making a spectacle.','The review took months while the household kept waiting.','Send the customary response','The ceremony was orderly and the household felt acknowledged.','The polished response answered nothing they had asked.')],
'vampire':[('keeper','The person who keeps the curtains closed','Someone who knows your secret has begun ageing. They worry about who will protect it after them.','Make a careful succession plan','We found a trusted person and recorded the rules together.','Trust could not be transferred as neatly as the papers.','Let them decide who to tell','Their choice gave the next keeper a reason to care.','They chose someone who needed more convincing than either of us expected.','Keep the burden to myself','They slept easier after handing the secret back.','Their absence left a practical gap I had refused to plan for.')],
'witch':[('garden','A remedy with a living ingredient','The ingredient you need grows in a neighbour’s neglected garden. Harvesting it would make the next spell easier.','Ask and share what I make','The neighbour agreed and a careful remedy helped us both.','They asked a question my explanation could not safely answer.','Grow my own and wait','The slower answer left me with a dependable supply.','The first seedlings failed and the spell had to wait.','Look for a substitute','An ordinary ingredient worked better than I expected.','The substitute changed the spell in a way I had not planned.')],
'super':[('identity','A rescue that exposes the ordinary life','A witness recognises something about your civilian identity during a rescue. They ask to speak privately.','Talk honestly within safe limits','They protected the secret and understood why it mattered.','They wanted guarantees I could not honestly give.','Ask them to focus on the people rescued','The story they told gave the survivors the attention.','A small identifying detail still made it into the account.','Disappear before they can ask again','The unanswered question faded while another story took over.','My abrupt departure made the witness more curious.')],
'revenant':[('record','A record that says you are gone','A clerk finds your death record while checking an ordinary form. You are standing at the counter.','Explain what I can calmly','The clerk found a way to handle the form without announcing me.','The explanation attracted a supervisor and a locked office.','Bring someone who remembers me','A familiar witness gave my impossible story a human anchor.','The witness was more frightened than I had realised.','Leave the paperwork for another day','I found another way to manage the immediate problem.','The unresolved record followed me into the next task.')]
}
for path,rows in PATHS.items():
 for key,title,text,*x in rows: scene(path+'.'+key,path,title,text,[x[i:i+3] for i in range(0,9,3)])
CAREERS={
'actor':('The continuity mistake','A scene has been filmed with a detail that contradicts the next one. Reshooting costs time.','Discuss it with the script supervisor'),
'musician':('The venue’s missing ramp','A listener cannot enter the venue where your set begins in an hour.','Work with the venue on access'),
'athlete':('The teammate after the injury','A teammate returns from injury but cannot keep the old training pace.','Train alongside them at their new pace'),
'politician':('The promise with no budget','A popular proposal reaches your desk without a credible way to fund it.','Publish the cost and revise the promise'),
'mafia':('The person behind the debt','A debtor has disappeared from work after a family emergency. Your crew wants an immediate answer.','Find out what happened before escalating'),
'hustler':('Someone using your pitch','A newcomer repeats your pitch on your usual street. The crowd notices.','Talk and agree on room for both'),
'astronaut':('The checklist nobody wants to delay','A preflight reading sits just outside tolerance. The launch window is narrowing.','Request a verification before clearance'),
'model':('The image that changes the brief','A proposed edit changes how your body appears in a campaign.','Ask to see and approve the final edit'),
'fighter':('The sparring partner who is hiding pain','A training partner keeps shaking out one hand between rounds.','Stop and ask the coach to assess it'),
'director':('The scene the crew cannot finish safely','Your planned shot needs another exhausted night of work.','Rewrite the shot around safe working hours'),
'agent':('The source whose story is too tidy','An informant’s account fits your expectations almost perfectly.','Verify the account through another channel')
}
for career,(title,text,label) in CAREERS.items():
 scene('career.'+career,['human','royal','vampire','witch','super','revenant','traveler'],title,text,[(label,'The slower decision exposed something the easy answer had missed. I earned trust by explaining the work.','The extra check was necessary, but the delay still had consequences.'),('Ask a colleague to challenge my assumptions','A colleague noticed the detail I had stopped seeing. The plan became more workable.','We disagreed about the priority and had to start again.'),('Carry on with the existing plan','The familiar plan held together this time.','The ignored detail returned as a problem I could no longer delegate.')],career=career)
(R/'data/events/settings.json').write_text(json.dumps(events,ensure_ascii=False,indent=1)+'\n')
# Annotate technology by explicit earliest year. Broad patterns err on preventing
# anachronism; event authors can inspect and tighten each annotation in JSON.
RULES=[(2004,r'\b(social media|influencer|livestream|streamer|viral|online dating|podcast|smartphone|app|apps|rideshare)\b'),(1995,r'\b(internet|online|email|website|webcam|crypto|bitcoin|wifi)\b'),(1985,r'\b(laptop|software|computer|coding|video game|video games|console)\b'),(1957,r'\b(astronaut|spacewalk|satellite)\b'),(1930,r'\b(television|tv|antibiotic|antibiotics)\b'),(1903,r'\b(airplane|airport|flight attendant)\b'),(1890,r'\b(car|cars|automobile|radio|motorcycle)\b')]
for f in (R/'data/events').glob('*.json'):
 if f.name=='settings.json': continue
 defs=json.loads(f.read_text());changed=False
 for d in defs:
  t=json.dumps([d.get('text',''),d.get('title',''),d.get('choices',[])],ensure_ascii=False)
  yrs=[y for y,pat in RULES if re.search(pat,t,re.I)]
  if yrs and int(d.get('available_from',0))<max(yrs): d['available_from']=max(yrs);changed=True
 if changed:f.write_text(json.dumps(defs,ensure_ascii=False,indent=1)+'\n')
print(len(events),'setting scenes')
